### ISSUE TITLE
UnhandledError Error During Provision: KeyError

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#1047]
```text
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 77, in run     self.daemon(child_args)
File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 123, in daemon     self.provision_handler.run()
File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 83, in run     self.provision(ovf_env)
File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 193, in provision     self.config_user_account(ovfenv)
File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 225, in config_user_account     self.deploy_ssh_pubkeys(ovfenv)
File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 250, in deploy_ssh_pubkeys     self.osutil.deploy_ssh_pubkey(ovfenv.username, pubkey)
File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/osutil/default.py", line 232, in deploy_ssh_pubkey     fileutil.mkdir(dir_path, mode=0o700, owner=username)
File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/utils/fileutil.py", line 98, in mkdir     chowner(dirpath, owner)
File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/utils/fileutil.py", line 104, in chowner     owner_info = pwd.getpwnam(owner) KeyError: 'getpwnam(): name not found: --name--'
```

**Comment by boumenot** [comment]
useradd rejects `--name--` as an invalid user name.  It's unfortunate that an invalid user name was allowed to get this far into the agent.  I suspect a better fix is to detect this fact a little further upstream, and reject it at that point  instead of progressing to pwd.getpwnam(`--name--`).

**Comment by boumenot** [comment]
This issue only appears on agent version 2.1.4, which is out of support, FreeBSD, or Marketplace distros.
