### ISSUE TITLE
UnhandledError in Provision: No such file or directory '/etc/sysconfig/network-scripts/ifcfg-eth1'

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#1048]
```text
Traceback (most recent call last):   File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 77, in run     self.daemon(child_args)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 123, in daemon     self.provision_handler.run()
File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 83, in run     self.provision(ovf_env)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 199, in provision     self.osutil.publish_hostname(ovfenv.hostname)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/osutil/redhat.py", line 116, in publish_hostname     super(RedhatOSUtil, self).publish_hostname(hostname)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/osutil/default.py", line 891, in publish_hostname     self.set_dhcp_hostname(hostname)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/osutil/redhat.py", line 90, in set_dhcp_hostname     'DHCP_HOSTNAME={0}'.format(hostname))
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/utils/fileutil.py", line 170, in update_conf_file     conf = read_file(path).split('\n')
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/utils/fileutil.py", line 61, in read_file     with open(filepath, mode) as in_file: IOError: [Errno 2] No such file or directory: '/etc/sysconfig/network-scripts/ifcfg-eth1' 
```

**Comment by boumenot** [comment]
This issue appears to be particular to Red Hat / CentOS.  The interface switches from eth0 to eth1 as part of bootup, and it looks like an appropriate ifcfg-eth1 configuration file is not created as a result.

```text
[    4.216315] hv_netvsc 000d3a50-035d-000d-3a50-035d000d3a50 eth0: VF registering: eth1
[snip]
[    4.834828] IPv6: ADDRCONF(NETDEV_UP): eth1: link is not ready
[    4.893795] IPv6: ADDRCONF(NETDEV_UP): eth1: link is not ready
[    4.898179] hv_netvsc 000d3a50-035d-000d-3a50-035d000d3a50 eth0: VF up: eth1
[    4.902904] hv_netvsc 000d3a50-035d-000d-3a50-035d000d3a50 eth0: Data path switched to VF: eth1
[    4.908464] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
[snip]
2018/04/03 13:26:16.246408 INFO Primary interface is [eth1]
2018/04/03 13:26:16.246949 INFO interface [lo] has flags [73], is loopback [True]
2018/04/03 13:26:16.247411 INFO Interface [lo] skipped
2018/04/03 13:26:16.248891 INFO interface [eth1] has flags [4163], is loopback [False]
2018/04/03 13:26:16.249462 INFO Interface [eth1] selected
2018/04/03 13:26:16.299066 ERROR Event: name=WALinuxAgent, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 77, in run
    self.daemon(child_args)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 123, in daemon
    self.provision_handler.run()
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 83, in run
    self.provision(ovf_env)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 199, in provision
    self.osutil.publish_hostname(ovfenv.hostname)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/osutil/redhat.py", line 116, in publish_hostname
    super(RedhatOSUtil, self).publish_hostname(hostname)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/osutil/default.py", line 891, in publish_hostname
    self.set_dhcp_hostname(hostname)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/osutil/redhat.py", line 90, in set_dhcp_hostname
    'DHCP_HOSTNAME={0}'.format(hostname))
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/utils/fileutil.py", line 170, in update_conf_file
    conf = read_file(path).split('\n')
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/utils/fileutil.py", line 61, in read_file
    with open(filepath, mode) as in_file:
IOError: [Errno 2] No such file or directory: '/etc/sysconfig/network-scripts/ifcfg-eth1', duration=0
```

I am only observing this error on older image versions of CentOS.  I **think** that this [was a bug that was fixed in August of 2017](https://lkml.org/lkml/2017/8/9/225).

I am not going to fix the issue in the agent because there are not that many deployments affected, the issue has been addressed in later versions, and the fix has been out for quite some time.  Even if you have an image that exhibits the issue, the chances of being affected is very small.  If you land here due to an Internet search, the solution is to upgrade to a newer image.

Here's the list of images that are known to have this issue.

|Offer|SKU|Version|
|---|---|---|
|CentOS-LVM|7-LVM|7.4.20180122|
|CentOS|7.3|7.3.20170925|
|CentOS|7.4|7.4.20170919|
|CentOS|7.4|7.4.20180118|

**Comment by szarkos** [comment]
This is not an agent issue, but due to accelerated networking.  CentOS 7.3 does not fully support AN, but RHEL/CentOS 7.4 does as of their November 2017 kernel update.

With the current images we have transparent SRIOV where the eth0 (synthetic interface) and eth1 (VF interface) are transparently bonded in the background.  In that case having DHCP enabled on just the synthetic interface works fine and you ignore the VF interface (this is similar to how Windows does this as well).
