### ISSUE TITLE
UnhandledError in Provision: IndexError

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#1049]
I am not sure what can be done about this because if this isn't working something is wrong upstream (most likely).  Still, it is worth a look.

```text
Traceback (most recent call last):   File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 77, in run     self.daemon(child_args)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 123, in daemon     self.provision_handler.run()
File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 66, in run     if self.is_provisioned():
File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 183, in is_provisioned     self.report_ready()
File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 282, in report_ready     protocol = self.protocol_util.get_protocol()
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/util.py", line 262, in get_protocol     self.protocol = self._detect_protocol(protocols)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/util.py", line 181, in _detect_protocol     return self._detect_wire_protocol()
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/util.py", line 155, in _detect_wire_protocol     protocol.detect()
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/wire.py", line 101, in detect     self.update_goal_state(forced=True)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/wire.py", line 104, in update_goal_state     self.client.update_goal_state(forced=forced, max_retry=max_retry)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/wire.py", line 729, in update_goal_state     self.update_certs(goal_state)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/wire.py", line 688, in update_certs     self.certs = Certificates(self, xml_text)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/wire.py", line 1250, in __init__     self.parse(xml_text)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/protocol/wire.py", line 1306, in parse     thumbprint = cryptutil.get_thumbprint_from_crt(tmp_file)
File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/utils/cryptutil.py", line 55, in get_thumbprint_from_crt     thumbprint = thumbprint.rstrip().split('=')[1].replace(':', '').upper() IndexError: list index out of range 
```

**Comment by boumenot** [comment]
Archiving this case for now.
