### ISSUE TITLE
Waagent getting stuck, blocking artifacts provisioning

### ISSUE THREAD

**Issue by ZiedMB** [Azure/WALinuxAgent#1175]
Hello everyone,

The issue is impacting NV series VM M60 GPU and NC K80 GPU, with Market Place Image Centos 7.4 and Centos 7.4 HPC .

The machine stays for long time on the 'Updating Azure agent status' and then, when applying the artifacts, the first one fails and the remaining are skipped.

```
AGENT STATUS
Not Ready
AGENT VERSION
Unknown
```

Error message from GuestOS: 

```
2018/05/14 12:14:58.086124 INFO RDMA: kvp daemon (hv_kvp_daemon) is running
2018/05/14 12:14:58.087471 INFO RDMA: kvp daemon running: True
2018/05/14 12:15:08.099663 ERROR RDMA: NdDriverVersion not found in "/var/lib/hyperv/.kvp_pool_0"
2018/05/14 12:15:08.197962 ERROR Event: name=WALinuxAgent, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 77, in run
    self.daemon(child_args)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 127, in daemon
    self.rdma_handler.install_driver()
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/rdma/centos.py", line 64, in install_driver
    raise Exception('Cannot determine RDMA firmware version')
Exception: Cannot determine RDMA firmware version
, duration=0
2018/05/14 12:15:08.201259 WARNING Daemon ended with exception -- Sleep 15 seconds and restart daemon
2018/05/14 12:15:23.216639 INFO Run daemon
```

The workaround was to manually disable RDMA, restart waagent, and work with a snapshot image of the healthy VM in order to not have an interruption on the continuous integration pipeline.

## The binary file is not showing a NdDriverVersion key :

```
Python 2.7.5 (default, Aug  4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>> driver_info_source = '/var/lib/hyperv/.kvp_pool_0'
>>> lines = open(driver_info_source).read()
>>> import re
>>> r = re.search("NdDriverVersion\0+(\d\d\d\.\d)", lines)
>>> print(r)
None
>>>
```
https://github.com/Azure/WALinuxAgent/blob/ccd52807ab2c43548a4ef13d86ababeb7e3f8c1f/azurelinuxagent/common/rdma.py#L104-L110

```
[root@nc6centos74hpc LISISO]# ./kvp_client
Pool is 0
Num records is 4
Key: NvidiaGridSplConfig; Value: <?xml version="1.0" encoding="utf-8"?><!DOCTYPE gridConfig SYSTEM "http://www.nvidia.com/dtd/gridSplConfig.dtd"><message><response seq="0$ time="2018-05-14T19:34:47"></response><status value="0"></status><feature>NV_GRID_LICENSE_FEATURE_CODE_QUADRO</feature><config>ENABLE_UI=1</config></message>
Key: NvidiaGridSplIdentification; Value: Microsoft Azure
Key: NvidiaGridSplLicense; Value: <license>AAABxgAA5eP/////AAAACwABAAAAAAEAAAAoAK0FAAAACwCuAAAAB98AAAALAK8AAAAAAwAAAAsAsAAAAAAAAAAACwDKAAAAAAYAAAERACkFAAAABwAzCgAAABsADgJ$
UklELVZpcnR1YWwtV1MtRXh0AAAAAA4ABwJudmlkaWEAAAAACwAPAjIuMAAAAAATADQCMzEtanVsLTIwMTYAAAAACwAQAAAAAAEAAAAmAEMFAAAACwBEAAAAAAgAAAAUAEUCNDcyNUE2RjNCMzkxAAAAACAAkQJiLXgyd2ZjTE$
Pc2ZHL0p1WU1QRCtyOEEAAAAAawBqBQAAAAsAbAAAAAAEAAAACwCSAAAAAAAAAAALAFMAAAAAAgAAAEMAawsIEwghdw0M0ICeT8nIWHPCrGF+BACTc5DBNbEsgCsdZO+AdVqCvL6aHa6nv8crtZZ9vK3bFvKHLTjak0QAAABrA$
oFAAAACwBsAAAAAAQAAAALAJIAAAAAAAAAAAsAUwAAAAACAAAAQwBrCxZ1JLtclLnjKu0/++k54QwMxC1VkRJ3jhV7bo3H7RVqRBmHvgLE76UYBu0DTMD/kC2RGjstFvhpxf7EJw==</license>
Key: NvidiaGridSplResponse; Value: <?xml version="1.0" encoding="utf-8"?><!DOCTYPE gridConfig SYSTEM "http://www.nvidia.com/dtd/gridSplConfig.dtd"><message><response seq=$
1877767660" time="2018-05-15T10:24:58"></response><status value="0"></status><signature>65728180c1d3825c0b62d443c60659c8aea92f732b9f7684178a4fe984245eb98455bee2a7f34ce181$
b1aa3a915c321e49c397b43253f591b9b184a3f62e237cda823c1e776c223a7601e75bd830dca75217e9568a158c90dc40780626e28ca4cd69cce5592645225a398308c27696dec32559f2c13990c09ff1b8452c26$
f5df9b6670f77599748247bbaaef8617fb1c20634b1a9dc8e2b0d0cf3b52fd48d8dae82060bd4e8911d63d6761b4253ec71d38e01cb9da2d6a2bc79927f283946580824686606d30e51692683d0025ea61451a6263$
15b2e31307149e152baa5269a4b5638f5860910ff899215abed2e23cee123bd0ebff432c2fad0d45c7ba0f9</signature></message>
Pool is 1
Num records is 1
Key: NvidiaGridSplRequest; Value: <?xml version="1.0" encoding="utf-8"?><!DOCTYPE vgpu SYSTEM "http://www.nvidia.com/dtd/vgpuConfig.dtd"><message><request seq="1877767660$
 time="2018-05-15T10:24:24">READ_LICENSE</request><challenge keyid="0x0">541D921CF1EF57163C4F7451C2448D3030A0931F89D89847B020BE5924E982795737F31DB10D3544FD6EAC57952BD66E3$
412E0B8A1B4500709EE4794C9FD645C9F2C715CACEEC14429848028A81E6296102CA4E6DB20C232E6FBC0A9CDEEC757B15220E80C7740E1A1AD011F0E9B57BA9143B7F563DCC50DC5FA26BFD31CD1B</challenge>$
/message>
Pool is 2
Num records is 0
Pool is 3
Num records is 11
Key: HostName; Value: AMS060101211110
Key: HostingSystemEditionId; Value: 168
Key: HostingSystemOsMajor; Value: 10
Key: HostingSystemOsMinor; Value: 0
```

The issue persists even with the Nvidia driver installed.

```
filename:       /lib/modules/3.10.0-693.21.1.el7.x86_64/extra/nvidia.ko.xz                                                                                         [4/3777]
alias:          char-major-195-*
version:        390.42
supported:      external
license:        NVIDIA
retpoline:      Y
rhelversion:    7.4
srcversion:     FA33B00C00A6F70EC9CF314
alias:          pci:v000010DEd00000E00sv*sd*bc04sc80i00*
alias:          pci:v000010DEd*sv*sd*bc03sc02i00*
alias:          pci:v000010DEd*sv*sd*bc03sc00i00*
depends:        ipmi_msghandler,i2c-core
vermagic:       3.10.0-693.21.1.el7.x86_64 SMP mod_unload modversions
parm:           NVreg_Mobile:int
parm:           NVreg_ResmanDebugLevel:int
parm:           NVreg_RmLogonRC:int
parm:           NVreg_ModifyDeviceFiles:int
parm:           NVreg_DeviceFileUID:int
parm:           NVreg_DeviceFileGID:int
parm:           NVreg_DeviceFileMode:int
parm:           NVreg_UpdateMemoryTypes:int
parm:           NVreg_InitializeSystemMemoryAllocations:int
parm:           NVreg_UsePageAttributeTable:int
parm:           NVreg_MapRegistersEarly:int
parm:           NVreg_RegisterForACPIEvents:int
parm:           NVreg_CheckPCIConfigSpace:int
parm:           NVreg_EnablePCIeGen3:int
parm:           NVreg_EnableMSI:int
parm:           NVreg_TCEBypassMode:int
parm:           NVreg_UseThreadedInterrupts:int
parm:           NVreg_EnableStreamMemOPs:int
parm:           NVreg_EnableBacklightHandler:int
parm:           NVreg_EnableUserNUMAManagement:int
parm:           NVreg_EnableIBMNPURelaxedOrderingMode:int
parm:           NVreg_MemoryPoolSize:int
parm:           NVreg_IgnoreMMIOCheck:int
parm:           NVreg_RegistryDwords:charp
```

hyperV driver :

```
[root@nc6centos74hpc LISISO]# modinfo hv_vmbus
filename:       /lib/modules/3.10.0-693.21.1.el7.x86_64/extra/microsoft-hyper-v/hv_vmbus.ko
version:        4.2.4.2
license:        GPL
retpoline:      Y
rhelversion:    7.4
srcversion:     E19FE454A158B963927C59C
alias:          acpi*:VMBus:*
alias:          acpi*:VMBUS:*
depends:
vermagic:       3.10.0-693.21.1.el7.x86_64 SMP mod_unload modversions
parm:           affinity_mode:vmbus channel cpu affinity mode: 0, 1 (int)
```

running kernel :

```
3.10.0-693.21.1.el7.x86_64
```

kvp running :

```
Redirecting to /bin/systemctl status hv_kvp_daemon.service
● hv_kvp_daemon.service - Hyper-V KVP daemon
   Loaded: loaded (/usr/lib/systemd/system/hv_kvp_daemon.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-05-15 10:27:02 UTC; 1h 58min ago
 Main PID: 579 (hv_kvp_daemon)
   CGroup: /system.slice/hv_kvp_daemon.service
           └─579 /usr/sbin/hv_kvp_daemon -n

May 15 10:27:02 nc6centos74hpc systemd[1]: Started Hyper-V KVP daemon.
May 15 10:27:02 nc6centos74hpc systemd[1]: Starting Hyper-V KVP daemon...
May 15 10:27:02 nc6centos74hpc KVP[579]: version 4.2.4.2 starting; pid is:579
May 15 10:27:02 nc6centos74hpc KVP[579]: KVP LIC Version: 4.2.4.2
```

waagent tested versions :

```
WALinuxAgent-2.2.18 running on centos 7.4.1708
Python: 2.7.5
Goal state agent: 2.2.18
[root@nc6hpccentos74 zied]#
```
```
[root@nc6hpccentos74 WALinuxAgent]# waagent version
WALinuxAgent-2.2.25 running on centos 7.4.1708
Python: 2.7.5
Goal state agent: 2.2.25
[root@nc6hpccentos74 WALinuxAgent]#
```

![error](https://user-images.githubusercontent.com/25243842/40063592-5e6f0336-5866-11e8-94e0-bac40b8f0a5a.JPG)

Is there a way to fast fail this process in order to have the waagent available to execute customscripts ?

Without RDMA, is the VM performance impacted ? 
as per :
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup#rdma-network-connectivity

CentOS-based 7.4 HPC should be RDMA capable with no additional installation steps.

Not sure if we can append the missing key to the pool to have everything working fine.

Please let me know if you need more details.
I will try to repro this using ubuntu.

Best regards, 
Zied

********

**Comment by ZiedMB** [comment]
ubuntu is having the same issue with rdma however it's by default commented, so the waagent is not stuck and showing working fine in the portal, letting all artifacts correctly provisioning.




Having both rdma enabled and updated :

```
OS.EnableRDMA=y
OS.UpdateRdmaDriver=y
```

did not afftect waagent since it's failing with :

```
2018/05/22 08:59:19.819790 ERROR RDMA: Source file "/var/lib/hyperv/.kvp_pool_0" is empty. Kernel does not provide the necessary information or the kvp daemon is not runni
ng.
2018/05/22 08:59:19.820844 ERROR RDMA: Could not determine firmware version. No driver will be installed
2018/05/22 08:59:19.821986 INFO RDMA capabilities are enabled in configuration
20
```

kvp running :

```
root@ubuntugpu:/home/zied# service hv-kvp-daemon status
● hv-kvp-daemon.service - Hyper-V KVP Protocol Daemon
   Loaded: loaded (/lib/systemd/system/hv-kvp-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-05-22 07:58:05 UTC; 32min ago
 Main PID: 1288 (hv_kvp_daemon)
   CGroup: /system.slice/hv-kvp-daemon.service
           └─1288 /usr/lib/linux-tools/4.13.0-1016-azure/hv_kvp_daemon -n

May 22 07:58:05 ubuntugpu KVP[1288]: KVP starting; pid is:1288
May 22 07:58:05 ubuntugpu KVP[1288]: KVP LIC Version: 3.1
May 22 07:58:05 ubuntugpu systemd[1]: Started Hyper-V KVP Protocol Daemon.
root@ubuntugpu:/home/zied#
```

kvp pools :

```
root@ubuntugpu:/home/zied# ./kvp_client
Pool is 0
Num records is 0
Pool is 1
Num records is 0
Pool is 2
Num records is 0
Pool is 3
Num records is 11
Key: HostName; Value: AMS060103111910
Key: HostingSystemEditionId; Value: 168
Key: HostingSystemOsMajor; Value: 10
Key: HostingSystemOsMinor; Value: 0
Key: HostingSystemProcessorArchitecture; Value: 9
Key: HostingSystemSpMajor; Value: 0
Key: HostingSystemSpMinor; Value: 0
Key: PhysicalHostName; Value: AMS060103111910
Key: PhysicalHostNameFullyQualified; Value: AMS060103111910
Key: VirtualMachineId; Value: 844FF8C7-4344-4FBF-9500-57CA18CF516E
Key: VirtualMachineName; Value: a6483d3e-20a4-4581-97bc-758a76f0e04b
Pool is 4
Num records is 0
```

waagent version 

```
WALinuxAgent-2.2.20 running on ubuntu 16.04
Python: 3.5.2
Goal state agent: 2.2.25
root@ubuntugpu:/home/zied#
```
```
VERSION="16.04.4 LTS (Xenial Xerus)"
4.13.0-1016-azure
```
