### ISSUE TITLE
Sometimes hostname not updated by waagent

### ISSUE THREAD

**Issue by mhmxs** [Azure/WALinuxAgent#119]
In some cases waagent doesn't update the hostname and stay localhost.localdomain. I started two machines in the same time. Here some information where hostname update failed:
- /var/lib/waagent/ovf-env.xml
```
<Environment xmlns="http://schemas.dmtf.org/ovf/environment/1" xmlns:oe="http://schemas.dmtf.org/ovf/environment/1" xmlns:wa="http://schemas.microsoft.com/windowsazure" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <wa:ProvisioningSection><wa:Version>1.0</wa:Version><LinuxProvisioningConfigurationSet xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ConfigurationSetType>LinuxProvisioningConfiguration</ConfigurationSetType><HostName>vmmaster1</HostName><UserName>asd</UserName><DisableSshPasswordAuthentication>true</DisableSshPasswordAuthentication><SSH><PublicKeys><PublicKey><Fingerprint>750...</Fingerprint><Path>/home/asd/.ssh/authorized_keys</Path></PublicKey></PublicKeys></SSH><CustomData>IyEvYmluL.....</CustomData></LinuxProvisioningConfigurationSet></wa:ProvisioningSection>
  <wa:PlatformSettingsSection><wa:Version>1.0</wa:Version><PlatformSettings xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><KmsServerHostname>kms.core.windows.net</KmsServerHostname><ProvisionGuestAgent>true</ProvisionGuestAgent><GuestAgentPackageName>VMAgentPackage.zip</GuestAgentPackageName></PlatformSettings></wa:PlatformSettingsSection>
</Environment>
```
- /var/log/waagent.log
```
2015/10/28 13:00:40 Windows Azure Linux Agent Version: WALinuxAgent-2.0.14
2015/10/28 13:00:41 Linux Distribution Detected      : centos
2015/10/28 13:00:41 Module /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
2015/10/28 13:00:41 mount: /dev/sr0 is write-protected, mounting read-only
2015/10/28 13:00:41 mount: /dev/sr0 mounted on /mnt/cdrom/secure.
2015/10/28 13:00:41 mount succeeded on attempt #1
2015/10/28 13:00:41 VMM Init script not found.  Provisioning for Azure
2015/10/28 13:00:41 Waiting for network.
2015/10/28 13:00:51 IPv4 address: 10.0.0.4
2015/10/28 13:00:51 MAC  address: 00:0D:3A:21:3D:EF
2015/10/28 13:00:51 Probing for Windows Azure environment.
2015/10/28 13:00:51 DoDhcpWork: Setting socket.timeout=10, entering recv
2015/10/28 13:00:52 Discovered Windows Azure endpoint: 168.63.129.16
2015/10/28 13:00:52 Fabric preferred wire protocol version: 2015-04-05
2015/10/28 13:00:52 Negotiated wire protocol version: 2012-11-30
2015/10/28 13:00:52 SetBlockDeviceTimeout: Update the device sda with timeout 300
2015/10/28 13:00:52 SetBlockDeviceTimeout: Update the device sdb with timeout 300
2015/10/28 13:00:52 SetBlockDeviceTimeout: Update the device sdc with timeout 300
2015/10/28 13:00:52 Retrieved GoalState from Windows Azure Fabric.
2015/10/28 13:00:52 ExpectedState: Started
2015/10/28 13:00:52 ContainerId: 97d26...
2015/10/28 13:00:52 RoleInstanceId: 0473...master1
2015/10/28 13:00:53 Public cert with thumbprint: 750A2... was retrieved.
2015/10/28 13:00:53 Provisioning image started.
2015/10/28 13:00:53 Detect GPT...
2015/10/28 13:00:53 mount: /dev/sr0 is write-protected, mounting read-only
2015/10/28 13:00:53 mount succeeded on attempt #1
2015/10/28 13:00:53 Provisioning image using OVF settings in the DVD.
2015/10/28 13:00:53 Wrote /var/lib/waagent/CustomData
2015/10/28 13:00:53 Disabled SSH password-based authentication methods.
2015/10/28 13:00:55 Created user account: asd
2015/10/28 13:00:55 Deploy public key:750A...
2015/10/28 13:00:55 Ovf XML process finished
2015/10/28 13:00:55 Posted Role Properties. CertificateThumbprint=70ee...
2015/10/28 13:00:55 Root password deleted.
2015/10/28 13:00:55 Provisioning image completed.
2015/10/28 13:00:55 Posted Role Properties. CertificateThumbprint=70ee...
2015/10/28 13:00:56 Resource disk (/dev/sdb1) is mounted at /mnt/resource with fstype ext4
2015/10/28 13:00:57 EnvMonitor: Detected dhcp client restart. Restoring routing table.
2015/10/28 13:01:00 Finished processing ExtensionsConfig.xml
2015/10/28 13:01:00 ERROR:Traceback (most recent call last):
2015/10/28 13:01:00 ERROR:  File "/usr/sbin/waagent", line 4806, in AddSystemInfo
2015/10/28 13:01:00 ERROR:    sharedConfig = xml.dom.minidom.parse("/var/lib/waagent/SharedConfig.xml").childNodes[0]
2015/10/28 13:01:00 ERROR:  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1921, in parse
2015/10/28 13:01:00 ERROR:    return expatbuilder.parse(file)
2015/10/28 13:01:00 ERROR:  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 922, in parse
2015/10/28 13:01:00 ERROR:    fp = open(file, 'rb')
2015/10/28 13:01:00 ERROR:IOError: [Errno 2] No such file or directory: '/var/lib/waagent/SharedConfig.xml'
2015/10/28 13:01:00 ERROR:
```
- /var/log/messages | grep hostname
```
Oct 28 13:00:12 localhost systemd[1]: Set hostname to <localhost.localdomain>.
Oct 28 13:00:32 localhost systemd: Set hostname to <localhost.localdomain>.
Oct 28 13:00:53 localhost NetworkManager[608]: <info>  Setting system hostname to 'localhost.localdomain' (no default device)
Oct 28 13:00:53 localhost nm-dispatcher: Dispatching action 'hostname'
```

The other machine, where the hostname is configured as well
- /var/lib/waagent/ovf-env.xml
```
<Environment xmlns="http://schemas.dmtf.org/ovf/environment/1" xmlns:oe="http://schemas.dmtf.org/ovf/environment/1" xmlns:wa="http://schemas.microsoft.com/windowsazure" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <wa:ProvisioningSection><wa:Version>1.0</wa:Version><LinuxProvisioningConfigurationSet xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ConfigurationSetType>LinuxProvisioningConfiguration</ConfigurationSetType><HostName>vmslave12</HostName><UserName>asd</UserName><DisableSshPasswordAuthentication>true</DisableSshPasswordAuthentication><SSH><PublicKeys><PublicKey><Fingerprint>750A...</Fingerprint><Path>/home/asd/.ssh/authorized_keys</Path></PublicKey></PublicKeys></SSH><CustomData>IyEvYmluL2Jhc2gK...</CustomData></LinuxProvisioningConfigurationSet></wa:ProvisioningSection>
  <wa:PlatformSettingsSection><wa:Version>1.0</wa:Version><PlatformSettings xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><KmsServerHostname>kms.core.windows.net</KmsServerHostname><ProvisionGuestAgent>true</ProvisionGuestAgent><GuestAgentPackageName>VMAgentPackage.zip</GuestAgentPackageName></PlatformSettings></wa:PlatformSettingsSection>
</Environment>
```
- /var/log/waagent.log
```
2015/10/28 13:01:13 Windows Azure Linux Agent Version: WALinuxAgent-2.0.14
  2015/10/28 13:01:13 Linux Distribution Detected      : centos
  2015/10/28 13:01:13 Module /lib/modules/3.10.0-229.7.2.el7.x86_64/kernel/drivers/ata/ata_piix.ko driver for ATAPI CD-ROM is already present.
  2015/10/28 13:01:14 mount: /dev/sr0 is write-protected, mounting read-only
  2015/10/28 13:01:14 mount: /dev/sr0 mounted on /mnt/cdrom/secure.
  2015/10/28 13:01:14 mount succeeded on attempt #1
  2015/10/28 13:01:14 VMM Init script not found.  Provisioning for Azure
  2015/10/28 13:01:14 IPv4 address: 10.0.0.5
  2015/10/28 13:01:14 MAC  address: 00:0D:3A:21:49:93
  2015/10/28 13:01:14 Probing for Windows Azure environment.
  2015/10/28 13:01:14 DoDhcpWork: Setting socket.timeout=10, entering recv
  2015/10/28 13:01:14 Discovered Windows Azure endpoint: 168.63.129.16
  2015/10/28 13:01:14 Fabric preferred wire protocol version: 2015-04-05
  2015/10/28 13:01:14 Negotiated wire protocol version: 2012-11-30
  2015/10/28 13:01:14 SetBlockDeviceTimeout: Update the device sda with timeout 300
  2015/10/28 13:01:14 SetBlockDeviceTimeout: Update the device sdb with timeout 300
  2015/10/28 13:01:14 SetBlockDeviceTimeout: Update the device sdc with timeout 300
  2015/10/28 13:01:15 Retrieved GoalState from Windows Azure Fabric.
  2015/10/28 13:01:15 ExpectedState: Started
  2015/10/28 13:01:15 ContainerId: 2867...
  2015/10/28 13:01:15 RoleInstanceId: 6da4...slave12
  2015/10/28 13:01:15 Public cert with thumbprint: 750A2E3DE4CA53757C1D7040C445E14951774241 was retrieved.
  2015/10/28 13:01:15 Provisioning image started.
  2015/10/28 13:01:15 Detect GPT...
  2015/10/28 13:01:16 mount: /dev/sr0 is write-protected, mounting read-only
  2015/10/28 13:01:16 mount succeeded on attempt #1
  2015/10/28 13:01:16 Provisioning image using OVF settings in the DVD.
  2015/10/28 13:01:16 Wrote /var/lib/waagent/CustomData
  2015/10/28 13:01:16 Disabled SSH password-based authentication methods.
  2015/10/28 13:01:18 Created user account: asd
  2015/10/28 13:01:18 Deploy public key:750A...
  2015/10/28 13:01:19 Resource disk (/dev/sdb1) is mounted at /mnt/resource with fstype ext4
  2015/10/28 13:01:20 EnvMonitor: Detected host name change: localhost.localdomain -> vmslave12
  2015/10/28 13:01:20 Setting host name: vmslave12
  2015/10/28 13:01:21 Ovf XML process finished
  2015/10/28 13:01:21 Posted Role Properties. CertificateThumbprint=2371...
  2015/10/28 13:01:21 Root password deleted.
  2015/10/28 13:01:21 Provisioning image completed.
  2015/10/28 13:01:21 Posted Role Properties. CertificateThumbprint=2371...
  2015/10/28 13:01:26 Finished processing ExtensionsConfig.xml
  2015/10/28 13:01:26 ERROR:Traceback (most recent call last):
  2015/10/28 13:01:26 ERROR:  File "/usr/sbin/waagent", line 4806, in AddSystemInfo
  2015/10/28 13:01:26 ERROR:    sharedConfig = xml.dom.minidom.parse("/var/lib/waagent/SharedConfig.xml").childNodes[0]
  2015/10/28 13:01:26 ERROR:  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1921, in parse
  2015/10/28 13:01:26 ERROR:    return expatbuilder.parse(file)
  2015/10/28 13:01:26 ERROR:  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 922, in parse
  2015/10/28 13:01:26 ERROR:    fp = open(file, 'rb')
  2015/10/28 13:01:26 ERROR:IOError: [Errno 2] No such file or directory: '/var/lib/waagent/SharedConfig.xml'
  2015/10/28 13:01:26 ERROR:
```
- /var/log/messages | grep hostname
```
Oct 28 13:00:50 localhost systemd[1]: Set hostname to <localhost.localdomain>.
Oct 28 13:01:05 localhost systemd: Set hostname to <localhost.localdomain>.
Oct 28 13:01:20 localhost NetworkManager[613]: <info>  Setting system hostname to 'localhost.localdomain' (no default device)
Oct 28 13:01:20 localhost nm-dispatcher: Dispatching action 'hostname'
Oct 28 13:01:21 localhost NetworkManager[613]: <info>  Setting system hostname to 'vmslave12' (from system configuration)
Oct 28 13:01:21 localhost nm-dispatcher: Dispatching action 'hostname'
```

This thing not happens always, for example in the previous couple of days it appears two times, and we started 18 instances. If you need any further information please feel free to ask me.

Best Regards,
Richard

**Comment by yuezh** [comment]
What is the cloud-init version the image is using? There was a bug with cloud-init that it will remove the file "SharedConfig.xml" which is essential for waagent.

**Comment by mhmxs** [comment]
We are using `cloud-init.x86_64 0:0.7.5-10.el7.centos.1`. Sorry maybe i was misunderstood, i pasted the full log of the waagent. Our problem is not around the SharedConfig.xml, but in the Ovf XML processing. On the rigth node i see:
```
2015/10/28 13:01:16 Provisioning image using OVF settings in the DVD.
...
2015/10/28 13:01:20 EnvMonitor: Detected host name change: localhost.localdomain -> vmslave12
2015/10/28 13:01:20 Setting host name: vmslave12
2015/10/28 13:01:21 Ovf XML process finished
```
but on the failed:
```
2015/10/28 13:00:53 Provisioning image using OVF settings in the DVD.
2015/10/28 13:00:53 Wrote /var/lib/waagent/CustomData
2015/10/28 13:00:53 Disabled SSH password-based authentication methods.
2015/10/28 13:00:55 Created user account: asd
2015/10/28 13:00:55 Deploy public key:750A...
2015/10/28 13:00:55 Ovf XML process finished
```

So there are missing `Detected host name change`and `Setting host name` lines.

**Comment by yuezh** [comment]
Sorry. I may mislead you in the preview post. Your problem is that Network Manager is conflict with waagent. I assume you are using a customized image. You need to uninstall the Network Manager first.

**Comment by mhmxs** [comment]
Thank you, we would try it, but really hard to catch the problem, because  for example yesterday i created almost 40 instances without any problem.

**Comment by mhmxs** [comment]
We are running on Centos7, and i found the text below in the official documentation:
```
Preparing a CentOS 7 virtual machine for Azure is very similar to CentOS 6, however there are several important differences worth noting:

The NetworkManager package no longer conflicts with the Azure Linux agent. This package is installed by default and we recommend that it is not removed.
```

**Comment by szarkos** [comment]
Right, NetworkManager is required in CentOS 7.  The issue here is probably with cloud-init.  Canonical wrote the cloud-init data provider for Azure, but it's really only been tested on Ubuntu.  If you just install cloud-init it will work partially and probably try to provision the VM at the same time as the Azure Linux agent, which will probably be very racy and lead to odd issues like this.  So in this case I would recommend removing cloud-init.

**Comment by mhmxs** [comment]
Thank you.

**Comment by TuxInvader** [comment]
I think this is still an issue, at least for custom images. I'm using an Ubuntu 18.04 image created and provisioned by packer. After installing my software waagent is called with `-deprovision+user`. 

The first machine deployed from this image in a new VNET will register with DHCP using `localhost`. The default config for provision.MonitorHostName in ubuntu is `no` so even if the hostname is changed in cloud-init or via some other mechanism the DHCP wont get updated (not unless the lease is renewed). 

Subsequent hosts will get the hostname they were given through the ARM template, presumably because DHCP rejects the attempt to register localhost, and gives them the name configured for them in the Azure.

I'm guessing the issue is caused by the `set_dhcp_hostname` function being called during the packer build

https://github.com/Azure/WALinuxAgent/blob/8087dbf377945dfc42516b557be4dfe8cde39301/azurelinuxagent/common/osutil/default.py#L1135

There should be an `unset_dhcp_hostname()` called during `-deprovision`

**Comment by TuxInvader** [comment]
Actually `send host-name gethostname();` is in the original dhclient.conf, so waagent isn't adding it, it would have hardcoded the hostname if it had anyway.

For me, removing the send_hostname line from dhclient in my packer script stops localhost getting added to DNS, and modifying setting `Provisioning.MonitorHostName=y` in waagent.conf adds the hostname I set in cloud-init.

**Comment by TuxInvader** [comment]
More digging has revealed that this happens to me when the hostname of the instance is the same as the hostname used in building the image. It's because the the waagent process doesn't reset the set-hostname file when deprovisioning. This results in setting the hostname being skipped in cc_set_hostname.py during cloud-init:

https://github.com/canonical/cloud-init/blob/695c4f8f46585dd7feac2fdc0729f410c539d3bc/cloudinit/config/cc_set_hostname.py#L80

I'm going to open a bug to request that waagent removes or updates /var/lib/cloud/data/set-hostname on deprovision. As a workaround I manually `rm` the file as the last step in my packer script.

```
 {
    "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
    "inline": [
      "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0",
      "rm /var/lib/cloud/data/set-hostname || echo 'no set-hostname file'",
      "sync; sync; sync"
    ],
    "inline_shebang": "/bin/sh -x",
    "type": "shell"
  }
```
