### ISSUE TITLE
ExtHandler Monitor thread died, restarting on FreeBSD 11.2

### ISSUE THREAD

**Issue by binary247** [Azure/WALinuxAgent#1243]
waagent is throwing a repeating warning for the ExtHandler Monitor on FreeBSD 11.2.  Can reproduce on 2.2.25 through 2.2.27.  With 2.2.27, additional errors are thrown on FreeBSD on the firewall monitor due to the lack of checks for ipfw or pf.

2018/07/07 22:54:33.967581 INFO Daemon Azure Linux Agent Version:2.2.27
2018/07/07 22:54:33.969257 INFO Daemon OS: freebsd 11.2
2018/07/07 22:54:33.969379 INFO Daemon Python: 2.7.15
2018/07/07 22:54:34.008872 INFO Daemon Run daemon
2018/07/07 22:54:34.010540 INFO Daemon No RDMA handler exists for distro='freebsd' version='11.2'
2018/07/07 22:54:34.011763 INFO Daemon Activate resource disk
2018/07/07 22:54:34.072227 INFO Daemon Resource disk device da1 found.
2018/07/07 22:54:34.086536 INFO Daemon Resource disk partition /dev/da1s1 found.
2018/07/07 22:54:34.092652 INFO Daemon Resource disk /dev/da1s1 is already mounted
2018/07/07 22:54:34.114598 INFO Daemon Clean protocol
2018/07/07 22:54:34.126599 INFO Daemon Provisioning already completed, skipping.
2018/07/07 22:54:34.128157 INFO Daemon RDMA capabilities are not enabled, skipping
2018/07/07 22:54:34.131255 INFO Daemon Installed Agent WALinuxAgent-2.2.27 is the most current agent
2018/07/07 22:54:34.239188 INFO ExtHandler Agent WALinuxAgent-2.2.27 is running as the goal state agent
2018/07/07 22:54:34.286983 INFO ExtHandler Detect protocol endpoints
2018/07/07 22:54:34.289325 INFO ExtHandler Clean protocol
2018/07/07 22:54:34.303892 INFO ExtHandler WireServer endpoint is not found. Rerun dhcp handler
2018/07/07 22:54:34.324115 INFO ExtHandler Test for route to 168.63.129.16
2018/07/07 22:54:34.326789 WARNING ExtHandler No route exists to 168.63.129.16
2018/07/07 22:54:34.337890 INFO ExtHandler Checking for dhcp lease cache
2018/07/07 22:54:34.355719 INFO ExtHandler Cache exists [False]
2018/07/07 22:54:34.368573 INFO ExtHandler Send dhcp request
2018/07/07 22:54:34.441926 INFO ExtHandler Configure routes
2018/07/07 22:54:34.444614 INFO ExtHandler Gateway:10.0.0.1
2018/07/07 22:54:34.463407 INFO ExtHandler Routes:None
2018/07/07 22:54:34.474620 INFO ExtHandler Wire server endpoint:168.63.129.16
2018/07/07 22:54:34.487730 INFO ExtHandler Fabric preferred wire protocol version:2015-04-05
2018/07/07 22:54:34.490634 INFO ExtHandler Wire protocol version:2012-11-30
2018/07/07 22:54:34.503687 INFO ExtHandler Server preferred version:2015-04-05
2018/07/07 22:54:34.735605 INFO ExtHandler Start env monitor service.
2018/07/07 22:54:34.747557 INFO ExtHandler Configure routes
2018/07/07 22:54:34.747760 ERROR ExtHandler Command: [iptables --version], return code: [127], result: [/bin/sh: iptables: not found
]
2018/07/07 22:54:34.758599 INFO ExtHandler Gateway:None
2018/07/07 22:54:34.760101 WARNING ExtHandler Unable to determine version of iptables
2018/07/07 22:54:34.760242 WARNING ExtHandler Unable to retrieve firewall packets droppedUnable to determine version of iptables
2018/07/07 22:54:34.814177 INFO ExtHandler Routes:None
2018/07/07 22:54:34.824695 INFO ExtHandler Wire server endpoint:168.63.129.16
2018/07/07 22:54:34.824839 INFO ExtHandler WALinuxAgent-2.2.27 running as process 16260
2018/07/07 22:54:34.861222 INFO ExtHandler Wire server endpoint:168.63.129.16
2018/07/07 22:55:06.274161 INFO ExtHandler Setting host plugin as default channel
2018/07/07 22:55:06.280045 INFO ExtHandler Wire server endpoint:168.63.129.16
2018/07/07 22:55:06.341486 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0] Target handler state: uninstall
2018/07/07 22:55:06.343245 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.6.42.0] [Uninstall] current handler state is: notinstalled
2018/07/07 22:55:06.384203 INFO ExtHandler Wire server endpoint:168.63.129.16
2018/07/07 22:55:06.386490 INFO ExtHandler ProcessGoalState completed [incarnation 2; 106 ms]
2018/07/07 22:55:09.420709 WARNING ExtHandler Monitor thread died, restarting

**Comment by binary247** [comment]
Thanks for the feedback.  Will try to work toward a fix and submit a PR.

As an FYI, the underlying issue seems to be resulting from the ExtHandler checks for /proc/net/route.  

2018/07/11 23:45:24.975066 WARNING ExtHandler Monitor thread died, restarting
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/ga/monitor.py", line 267, in daemon
    self.log_altered_network_configuration()
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/ga/monitor.py", line 427, in log_altered_network_configuration
    raw_route_list = self.osutil.read_route_table()
  File "/usr/local/lib/python2.7/site-packages/azurelinuxagent/common/osutil/default.py", line 810, in read_route_table
    with open('/proc/net/route') as routing_table:
IOError: [Errno 2] No such file or directory: '/proc/net/route'

Other projects have run into similar issues and resolved by using netstat on flavors that don't support procfs.

https://bugzilla.xamarin.com/show_bug.cgi?id=23209

**Comment by lyda** [comment]
I'm seeing this too, but it doesn't seem to be the routing thing.  The `azurelinuxagent/common/osutil/freebsd.py` bit abstracts out all the route code.

If you set `Logs.Verbose=y` in `/etc/waagent.conf` you'll get a clearer picture of the error. In my case an install script I ran made enough networking changes to somehow mess up dhcp requests.

**Comment by tengtengvn** [comment]
I'm going through each version all the way to 2.2.31 without any luck.

2018/09/20 23:03:50.126232 INFO Daemon Azure Linux Agent Version:2.2.31
2018/09/20 23:03:50.126696 INFO Daemon OS: freebsd 11.1
2018/09/20 23:03:50.126831 INFO Daemon Python: 2.7.14
2018/09/20 23:03:50.134215 INFO Daemon Run daemon
2018/09/20 23:03:50.134400 INFO Daemon No RDMA handler exists for distro='freebsd' version='11.1'
2018/09/20 23:03:50.134535 INFO Daemon Activate resource disk
2018/09/20 23:03:50.179688 INFO Daemon Resource disk device da1 found.
2018/09/20 23:03:50.187420 INFO Daemon Resource disk partition /dev/da1s1 found.
2018/09/20 23:03:50.197845 INFO Daemon Resource disk partition /dev/da1s1 is mounted at /mnt/resource with fstype ufs
2018/09/20 23:03:50.199298 INFO Daemon Clean protocol
2018/09/20 23:03:50.199584 INFO Daemon Running default provisioning handler
2018/09/20 23:03:50.199698 INFO Daemon Copying ovf-env.xml
2018/09/20 23:03:50.200588 INFO Daemon Detect protocol endpoints
2018/09/20 23:03:50.200712 INFO Daemon Clean protocol
2018/09/20 23:03:50.200860 INFO Daemon WireServer endpoint is not found. Rerun dhcp handler
2018/09/20 23:03:50.200950 INFO Daemon Test for route to 168.63.129.16
2018/09/20 23:03:50.201030 WARNING Daemon No route exists to 168.63.129.16
2018/09/20 23:03:50.201095 INFO Daemon Checking for dhcp lease cache
2018/09/20 23:03:50.201173 INFO Daemon Cache exists [False]
2018/09/20 23:03:50.201225 INFO Daemon Send dhcp request
2018/09/20 23:04:00.245037 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/20 23:04:10.344966 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/20 23:04:30.445020 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/20 23:05:10.645124 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/20 23:06:20.744947 WARNING Daemon Failed to send DHCP request: [DhcpError] timed out
2018/09/20 23:07:20.792065 INFO Daemon Protocol endpoint not found: WireProtocol, [ProtocolError] [DhcpError] Failed to receive dhcp response.

**Comment by mike-pt** [comment]
Seeing the same and this spams dmesg a lot, why was the GHI closed though? 

Shouldn't we keep the GHI open though? the problem was not addressed after all perhaps there's a label "waiting for someone to take it" 

Anyway I'd be happy to spend some time on it on the weekend, I found the 2 files  (at least) that need to be updated to check "netstat -rn" instead of /proc/net/route.
>`(common/dhcp.py and common/osutil/default.py) `

I am curious though .... should we just default to that? Is there  linux distro or even any unix system without `netstat -rn`?

Otherwise I can add some conditionals to only do it if `/proc/net/route` is not found... I just don't want to spend the time and open a PR to have it rejected :) so asking some pointers first

**Comment by fegu** [comment]
I am also having this problem on FreeBSD 11.2 using waagent v2.2.35. Logs say missing /proc/net/route. Enabling /procfs and/or installing linux compatibility does not fix it. This makes backup in azure fail for FreeBSD.

**Comment by fegu** [comment]
I just put a text file in the correct format in /proc/net/route. This made the waagent continue, but it now complains about missing the utility iptables. The backup job still fails. A quick grep shows some use of iptables in common/osutil/default.py. I am considering just making an iptables shell script to fake the necessary values.

**Comment by Tulkis** [comment]
> 
> 
> I just put a text file in the correct format in /proc/net/route. This made the waagent continue, but it now complains about missing the utility iptables. The backup job still fails. A quick grep shows some use of iptables in common/osutil/default.py. I am considering just making an iptables shell script to fake the necessary values.

Hi @fegu, could you resolve the issue with that workarround?

**Comment by fegu** [comment]
@Tulkis sorry, no. I didn't spend a lot of time on it, though.

**Comment by Tulkis** [comment]
> 
> 
> @Tulkis sorry, no. I didn't spend a lot of time on it, though.

You're welcome, thank you for the response.
