### ISSUE TITLE
CGroups error in Ubuntu 14.04

### ISSUE THREAD

**Issue by hglkrijger** [Azure/WALinuxAgent#1282]
```
2018/07/31 11:41:06.400633 ERROR ExtHandler monitor: Exception tracking wrapper and agent: 'Hierarchy memory is not mounted' [Traceback (most recent call last):
  File "bin/WALinuxAgent-2.2.30-py2.7.egg/azurelinuxagent/ga/monitor.py", line 397, in init_cgroups
    CGroupsTelemetry.track_cgroup(CGroups.for_extension(""))
  File "bin/WALinuxAgent-2.2.30-py2.7.egg/azurelinuxagent/common/cgroups.py", line 360, in for_extension
    return CGroups(name, CGroups._construct_custom_path_for_hierarchy)
  File "bin/WALinuxAgent-2.2.30-py2.7.egg/azurelinuxagent/common/cgroups.py", line 401, in __init__
    raise CGroupsException("Hierarchy {0} is not mounted".format(hierarchy))
azurelinuxagent.common.cgroups.CGroupsException: 'Hierarchy memory is not mounted'
]
```

**Comment by jasonzio** [comment]
Hmmm. The cgroups code init code tries to mount the two desired hierarchies; did the mount operation fail? Messages would have appeared earlier in the spew.

**Comment by hglkrijger** [comment]
This was an RDFE VM, logs looked normal otherwise.
