### ISSUE TITLE
FreeBSD 2.2.29 ExtHandler Monitor thread died

### ISSUE THREAD

**Issue by woodwardjavere** [Azure/WALinuxAgent#1286]
Seems since 2.2.26 there is a problem on FreeBSD:

```
2018/08/03 19:45:18.908369 INFO Daemon Azure Linux Agent Version:2.2.29
2018/08/03 19:45:18.920870 INFO Daemon OS: freebsd 11.1
2018/08/03 19:45:18.925967 INFO Daemon Python: 2.7.15
2018/08/03 19:45:18.989362 INFO Daemon Run daemon
2018/08/03 19:45:18.991157 INFO Daemon No RDMA handler exists for distro='freebsd' version='11.1'
2018/08/03 19:45:18.995100 INFO Daemon Clean protocol
2018/08/03 19:45:19.015702 INFO Daemon Provisioning already completed, skipping.
2018/08/03 19:45:19.016425 INFO Daemon RDMA capabilities are not enabled, skipping
2018/08/03 19:45:19.019318 INFO Daemon Installed Agent WALinuxAgent-2.2.29 is the most current agent
2018/08/03 19:45:19.119509 INFO ExtHandler Agent WALinuxAgent-2.2.29 is running as the goal state agent
2018/08/03 19:45:19.216079 INFO ExtHandler Detect protocol endpoints
2018/08/03 19:45:19.217170 INFO ExtHandler Clean protocol
2018/08/03 19:45:19.228981 INFO ExtHandler WireServer endpoint is not found. Rerun dhcp handler
2018/08/03 19:45:19.231411 INFO ExtHandler Test for route to 168.63.129.16
2018/08/03 19:45:19.231532 WARNING ExtHandler No route exists to 168.63.129.16
2018/08/03 19:45:19.233583 INFO ExtHandler Checking for dhcp lease cache
2018/08/03 19:45:19.234334 INFO ExtHandler Cache exists [False]
2018/08/03 19:45:19.235112 INFO ExtHandler Send dhcp request
...<skip>...
2018/08/03 19:48:49.620267 INFO ExtHandler Wire server endpoint:168.63.129.16
2018/08/03 19:48:49.627338 INFO ExtHandler Fabric preferred wire protocol version:2015-04-05
2018/08/03 19:48:49.628742 INFO ExtHandler Wire protocol version:2012-11-30
2018/08/03 19:48:49.640162 INFO ExtHandler Server preferred version:2015-04-05
2018/08/03 19:48:51.213170 INFO ExtHandler Start env monitor service.
2018/08/03 19:48:51.217683 INFO ExtHandler Configure routes
2018/08/03 19:48:51.221395 INFO ExtHandler Gateway:None
2018/08/03 19:48:51.222524 INFO ExtHandler Routes:None
2018/08/03 19:48:51.228915 ERROR ExtHandler Command: [iptables --version], return code: [127], result: [/bin/sh: iptables: not found
]
2018/08/03 19:48:51.231597 WARNING ExtHandler Unable to determine version of iptables
2018/08/03 19:48:51.234924 WARNING ExtHandler Unable to retrieve firewall packets droppedUnable to determine version of iptables
2018/08/03 19:48:51.252179 INFO ExtHandler Wire server endpoint:168.63.129.16
2018/08/03 19:48:51.276764 INFO ExtHandler WALinuxAgent-2.2.29 running as process 64927
2018/08/03 19:48:51.280890 WARNING ExtHandler Dhcp client is not running.
2018/08/03 19:48:51.314950 INFO ExtHandler Wire server endpoint:168.63.129.16
2018/08/03 19:48:51.437321 INFO ExtHandler Wire server endpoint:168.63.129.16
2018/08/03 19:48:51.600896 INFO ExtHandler Wire server endpoint:168.63.129.16
2018/08/03 19:48:51.602302 INFO ExtHandler ProcessGoalState completed [incarnation 3; 165 ms]
2018/08/03 19:48:54.657969 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:48:57.701983 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:00.735388 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:03.767535 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:06.837573 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:09.898257 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:12.937035 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:15.980779 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:19.023321 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:22.057883 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:25.092904 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:28.167120 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:31.222807 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:34.297657 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:37.362089 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:40.442405 WARNING ExtHandler Monitor thread died, restarting
2018/08/03 19:49:43.508203 WARNING ExtHandler Monitor thread died, restarting
```

It appears to be the send_cgroup_telemetry and log_altered_network_configuration calls in azurelinuxagent/ga/monitor.py:MonitorHandler.daemon assuming files in /proc and /sys.

Thanks and take care,
jason

**Comment by hglkrijger** [comment]
We should fail gracefully

**Comment by hglkrijger** [comment]
```
2018/08/22 22:02:32.370060 INFO ExtHandler WALinuxAgent-2.2.31 running as process 3055
2018/08/22 22:02:32.396103 INFO ExtHandler Wire server endpoint:168.63.129.16
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/azurelinuxagent/ga/monitor.py", line 267, in daemon
    self.log_altered_network_configuration()
  File "build/bdist.linux-x86_64/egg/azurelinuxagent/ga/monitor.py", line 427, in log_altered_network_configuration
    raw_route_list = self.osutil.read_route_table()
  File "build/bdist.linux-x86_64/egg/azurelinuxagent/common/osutil/default.py", line 810, in read_route_table
    with open('/proc/net/route') as routing_table:
IOError: [Errno 2] No such file or directory: '/proc/net/route'
```
