### ISSUE TITLE
InitializeHostPlugin should be called after incarnation resets

### ISSUE THREAD

**Issue by vrdmr** [Azure/WALinuxAgent#1294]
After a live migration, when the agent resets, it is not updating the host plugin information (on the GA). After the new incarnation comes in, there are no new `InitializeHostPlugin` events, which points to that the agent is continuing to use the container id/role name in the memory.

The [Waagent.log](https://gist.githubusercontent.com/vrdmr/b999902765c1405a37fe628bbf88b8c2/raw/a4d5d920db8c0e94507ff757b7e8e3a232258835/waagent.log) has a large gap during this live migration as well, and does not have any restart logs.

```
2018/08/03 10:54:34.454022 INFO ExtHandler Setting host plugin as default channel
2018/08/04 03:10:41.088150 WARNING ExtHandler Fetch failed from [http://168.63.129.16:32526/extensionArtifact]: [HTTP Failed] [400: Bad Request] b'{  "errorCode": "InvalidContainerConfiguration",  "message": "Invalid request.",  "details": "[0x8000100a] ValidateIpAddress"}'
```

Based on the investigation @hglkrijger did, the potential issue might be [here](https://github.com/Azure/WALinuxAgent/blob/master/azurelinuxagent/ga/update.py#L681), where the `ResourceGoneError` does not account for any 400s.

**Comment by hglkrijger** [comment]
```
2018/08/01 06:40:27.767168 ERROR ExtHandler Event: name=WALinuxAgent, op=ExtensionProcessing, message=Failed to report vm agent status: [ProtocolError] Failed to upload status blob via either channel, duration=0
2018/08/01 06:40:30.780706 ERROR ExtHandler HostGAPlugin: Failed Get API versions: [HTTP Failed] [400: Bad Request] b'{  "errorCode": "InvalidContainerConfiguration",  "message": "Invalid request.",  "details": "[0x8000100a] ValidateIpAddress"}'
2018/08/01 06:40:30.786391 ERROR ExtHandler Event: name=WALinuxAgent, op=InitializeHostPlugin, message=, duration=0
2018/08/01 06:40:30.788608 WARNING ExtHandler Exception retrieving agent manifests: Traceback (most recent call last):
  File "bin/WALinuxAgent-2.2.29-py2.7.egg/azurelinuxagent/ga/update.py", line 653, in _upgrade_available
    pkg_list = protocol.get_vmagent_pkgs(manifests[0])
  File "bin/WALinuxAgent-2.2.29-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 144, in get_vmagent_pkgs
    ga_manifest = self.client.get_gafamily_manifest(vmagent_manifest, goal_state)
  File "bin/WALinuxAgent-2.2.29-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 939, in get_gafamily_manifest
    vmagent_manifest.versionsManifestUris)
  File "bin/WALinuxAgent-2.2.29-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 626, in fetch_manifest
    uri, headers = host.get_artifact_request(version.uri)
  File "bin/WALinuxAgent-2.2.29-py2.7.egg/azurelinuxagent/common/protocol/hostplugin.py", line 133, in get_artifact_request
    raise ProtocolError("HostGAPlugin: Host plugin channel is not available")
azurelinuxagent.common.exception.ProtocolError: [ProtocolError] HostGAPlugin: Host plugin channel is not available
```

**Comment by hglkrijger** [comment]
We also must not report health store failures if the return code is 400.

**Comment by hglkrijger** [comment]
Fix merged
