### ISSUE TITLE
Agent exception during extension upgrade leaves extension inoperable

### ISSUE THREAD

**Issue by mthompson83** [Azure/WALinuxAgent#1320]
During the upgrade of an extension, with updatemode updatewithinstall, the Azure Agent threw an exception. Therefore, it did not complete the install operation for the new version. After restarting, the AzureAgent is logging that the extension current state is uninstalled, but appears to be bypassing invoking the extension's install operation and going directly to the enable operation. Because the install hasn't been completed, the enable is failing.
```
uname -a
Linux _redacted_ 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Extract from /var/log/waagent.log:
```
2018/08/03 10:37:49.021883 INFO Azure Linux Agent Version:2.1.3
...
2018/08/21 00:26:18.075717 INFO Handle new ext handler config
2018/08/21 00:26:18.107444 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Expected handler state: enabled
2018/08/21 00:26:18.129332 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Decide which version to use
2018/08/21 00:26:18.181045 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Use version: 9.6.2.1366
2018/08/21 00:26:18.203828 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Current handler state is: NotInstalled
2018/08/21 00:26:18.226845 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Download extension package
2018/08/21 00:26:30.086111 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Unpack extension package
2018/08/21 00:26:31.215719 INFO Event: name=Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux, op=Download, message=Download succeeded
2018/08/21 00:26:31.235425 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Initialize extension directory
2018/08/21 00:26:31.258133 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Extension has no settings, write empty 0.settings
2018/08/21 00:26:31.280826 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.0.1355] Disable extension.
2018/08/21 00:26:31.450667 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.0.1355] Launch command:scripts/service_stop.sh
2018/08/21 00:26:31.645018 INFO Event: name=Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux, op=Disable, message=Launch command succeeded: scripts/service_stop.sh
2018/08/21 00:26:31.683242 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Copy status files from old plugin to new
2018/08/21 00:26:31.849014 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Update extension.
2018/08/21 00:26:31.865702 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Launch command:scripts/nop.sh
2018/08/21 00:26:31.892280 INFO Event: name=Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux, op=Update, message=Launch command succeeded: scripts/nop.sh
2018/08/21 00:26:31.910206 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.0.1355] Uninstall extension.
2018/08/21 00:26:31.924704 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.0.1355] Launch command:scripts/uninstall.sh 2>&1 >/dev/null
2018/08/21 00:26:32.286310 INFO Event: name=Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux, op=UnInstall, message=Launch command succeeded: scripts/uninstall.sh 2>&1 >/dev/null
2018/08/21 00:26:32.306748 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.0.1355] Remove ext handler dir: /var/lib/waagent/handler_state/Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.0.1355
2018/08/21 00:26:33.881346 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.0.1355] Remove ext handler dir: /var/lib/waagent/Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.0.1355
**2018/08/21 00:26:33.969320 ERROR Event: name=WALA, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/lib/python3.5/dist-packages/azurelinuxagent/distro/default/daemon.py", line 53, in run
    self.daemon()
  File "/usr/lib/python3.5/dist-packages/azurelinuxagent/distro/default/daemon.py", line 101, in daemon
    self.distro.ext_handlers_handler.run()
  File "/usr/lib/python3.5/dist-packages/azurelinuxagent/distro/default/extension.py", line 128, in run
    self.handle_ext_handlers(ext_handlers)
  File "/usr/lib/python3.5/dist-packages/azurelinuxagent/distro/default/extension.py", line 141, in handle_ext_handlers
    self.handle_ext_handler(ext_handler)
  File "/usr/lib/python3.5/dist-packages/azurelinuxagent/distro/default/extension.py", line 149, in handle_ext_handler
    self.handle_enable(ext_handler_i)
  File "/usr/lib/python3.5/dist-packages/azurelinuxagent/distro/default/extension.py", line 187, in handle_enable
    ext_handler_i.update_with_install()
  File "/usr/lib/python3.5/dist-packages/azurelinuxagent/distro/default/extension.py", line 488, in update_with_install
    if man.is_update_with_install():
  File "/usr/lib/python3.5/dist-packages/azurelinuxagent/distro/default/extension.py", line 817, in is_update_with_install
    return update_mode.low() == "updatewithinstall"
AttributeError: 'str' object has no attribute 'low'**
2018/08/21 00:26:34.170916 INFO Sleep 15 seconds and restart daemon
2018/08/21 00:26:49.197684 INFO Run daemon
…
2018/08/21 00:26:53.401018 INFO Handle new ext handler config
2018/08/21 00:26:53.419917 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Expected handler state: enabled
2018/08/21 00:26:53.436514 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Decide which version to use
2018/08/21 00:26:53.487587 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Use version: 9.6.2.1366
2018/08/21 00:26:53.516911 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Current handler state is: NotInstalled
2018/08/21 00:26:53.537201 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Download extension package
2018/08/21 00:27:03.313846 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Unpack extension package
2018/08/21 00:27:04.454310 INFO Event: name=Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux, op=Download, message=Download succeeded
2018/08/21 00:27:04.484597 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Initialize extension directory
2018/08/21 00:27:04.518888 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Extension has no settings, write empty 0.settings
2018/08/21 00:27:04.541950 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Enable extension.
2018/08/21 00:27:04.562236 INFO [Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux-9.6.2.1366] Launch command:scripts/enableHandler.py 2>&1
2018/08/21 00:27:05.080718 ERROR Event: name=Microsoft.Azure.Monitoring.DependencyAgent.DependencyAgentLinux, op=Enable, message=(000003)Non-zero exit code: 66, scripts/enableHandler.py 2>&1
```

**Comment by hglkrijger** [comment]
This was fixed in #449, which should be present in any 2.2.x version of the agent. Please note that 2.1.3 is not a supported version: https://support.microsoft.com/en-us/help/4049215/extensions-and-virtual-machine-agent-minimum-version-support
