### ISSUE TITLE
Test failures: tests.utils.test_rest_util.TestHttpOperations

### ISSUE THREAD

**Issue by waldiTM** [Azure/WALinuxAgent#1405]
e9ab9a6c80d9f4e42829b63864e4aef96d0a8055 produces the following two test failures if `http_proxy` is set, as is in current Debian builds.

```
======================================================================
FAIL: test_get_http_proxy_configuration_requires_host (tests.utils.test_rest_util.TestHttpOperations)
----------------------------------------------------------------------
Traceback (most recent call last):                               
  File "/usr/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/tmp/WALinuxAgent/tests/utils/test_rest_util.py", line 207, in test_get_http_proxy_configuration_requires_host
    self.assertEqual(None, h)
AssertionError: None != 'wrong'         
        
======================================================================
FAIL: test_get_http_proxy_none_is_default (tests.utils.test_rest_util.TestHttpOperations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/tmp/WALinuxAgent/tests/utils/test_rest_util.py", line 187, in test_get_http_proxy_none_is_default
    self.assertEqual(None, h)
AssertionError: None != 'wrong'
```

**Comment by narrieta** [comment]
we were unable to reproduce this issue
