### ISSUE TITLE
Test failure: tests.protocol.test_wire.TestWireProtocol

### ISSUE THREAD

**Issue by waldiTM** [Azure/WALinuxAgent#1407]
e9ab9a6 shows the following test failure:

```
=====================================================================
ERROR: test_download_ext_handler_pkg_stream (tests.protocol.test_wire.TestWireProtocol)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/tmp/WALinuxAgent/.pybuild/cpython3_3.6/build/tests/protocol/test_wire.py", line 186, in test_download_ext_handler_pkg_stream
    success = WireProtocol(wireserver_url).download_ext_handler_pkg(ext_uri, destination)
  File "/tmp/WALinuxAgent/.pybuild/cpython3_3.6/build/azurelinuxagent/common/protocol/wire.py", line 172, in download_ext_handler_pkg
    host = self.client.get_host_plugin()
  File "/tmp/WALinuxAgent/.pybuild/cpython3_3.6/build/azurelinuxagent/common/protocol/wire.py", line 1185, in get_host_plugin
    goal_state = self.get_goal_state()
  File "/tmp/WALinuxAgent/.pybuild/cpython3_3.6/build/azurelinuxagent/common/protocol/wire.py", line 830, in get_goal_state
    incarnation = self.fetch_cache(incarnation_file)
  File "/tmp/WALinuxAgent/.pybuild/cpython3_3.6/build/azurelinuxagent/common/protocol/wire.py", line 578, in fetch_cache
    raise ProtocolError("{0} is missing.".format(local_file))
azurelinuxagent.common.exception.ProtocolError: [ProtocolError] /tmp/TestWireProtocol_6_ma7peb/Incarnation is missing.
```

**Comment by pgombar** [comment]
@waldiTM we can't repro this on our side.
