### ISSUE TITLE
'NoneType' object has no attribute 'UserName'

### ISSUE THREAD

**Issue by jakehoms** [Azure/WALinuxAgent#1446]
We are setting up a Jenkins build to create SLES 12 for SAP (SP3) images in Azure. When installing like this:
```
zypper --non-interactive install git-core python-setuptools cloud-netconfig-azure python-azurectl cloud-netconfig-azure azuremetadata
git clone https://github.com/Azure/WALinuxAgent.git /tmp/linuxagent
cd /tmp/linuxagent ; sudo python setup.py install --register-service || true
```
It builds fine through the deprovision portion:
```
waagent -force -deprovision+user
WARNING! The waagent service will be stopped.
WARNING! All SSH host key pairs will be deleted.
WARNING! Cached DHCP leases will be deleted.
WARNING! root password will be disabled. You will not be able to login as root.
WARNING! /etc/resolv.conf will be deleted.
WARNING! ovf-env.xml is not found.
WARNING! Skip delete user.
export HISTSIZE=0
HISTSIZE=0
sync
exit 0
Gracefully halting virtual machine...
```

But when installing via the scc.suse.com repo, it crashes:
```
waagent -force -deprovision+user
WARNING! The waagent service will be stopped.
WARNING! All SSH host key pairs will be deleted.
WARNING! Cached DHCP leases will be deleted.
WARNING! Nameserver configuration in /etc/resolv.conf will be deleted.
WARNING! root password will be disabled. You will not be able to login as root.
Traceback (most recent call last):
  File "/usr/sbin/waagent", line 6479, in <module>
    main()
  File "/usr/sbin/waagent", line 6446, in main
    sys.exit(Deprovision(force, True))
  File "/usr/sbin/waagent", line 6368, in Deprovision
    MyDistro.DeleteAccount(ovfobj.UserName)
AttributeError: 'NoneType' object has no attribute 'UserName'
export HISTSIZE=0
HISTSIZE=0
sync
exit 0
Gracefully halting virtual machine...
```

The github repo is trying to install version 2.2.34, while scc.suse.com has version 2.0.17. I'd be fine with the newer version, but the team consuming the image needs the older version which I do not see available in the releases here, and the older version won't allow the image to be created as shown above. 

Not sure, but I believe the reason the newer version isn't working correctly is that it's not conforming to Suse: 
v2.2.34:
```
waagent --version
WALinuxAgent-2.2.34 running on suse 12
Python: 2.7.13
Goal state agent: 2.2.34
```
v2.0.17:
```
waagent --version
WALinuxAgent-2.0.17 running on SuSE
```

Is there a way to build the older version and get Jenkins not to crash, or is there a better way to install/register the newer version of WALinuxAgent? Hope this makes sense, if not please ask and I'll try to clarify. Thanks for the help.

**Comment by pgombar** [comment]
Hi @jakehoms, this is what we do in our template when preparing a SUSE 12 custom image:
```
git clone https://github.com/Azure/WALinuxAgent
cd WALinuxAgent
wget https://bootstrap.pypa.io/ez_setup.py -O - | python3
python3 setup.py install --register-service --force
cat bin/waagent | sed 's_#!/usr/bin/env python_#!/usr/bin/env python3_' > /usr/sbin/waagent
initctl start walinuxagent
waagent --version
initctl stop walinuxagent
waagent -deprovision -force
rm -rf /var/lib/waagent
```
Hope this helps.
