### ISSUE TITLE
Unable to initiate Azure Backup on SLE 15

### ISSUE THREAD

**Issue by dops0** [Azure/WALinuxAgent#1477]
We are having problems initiating a backup of our VM running SLE 15. 

The error message we get on Azure portal is **ExtensionSnapshotFailedNoNetwork**
We've set NSG rules allowing outbound access to Azure storage but still end up with this error. Logs on the VM itself give some information, but don't know if that helps pinpoint the problem.

```
waagent --version
WALinuxAgent-2.2.36 running on sles 15
Python: 3.6.5
Goal state agent: 2.2.37
```

From 
/var/log/azure/Microsoft.Azure.RecoveryServices.VMSnapshotLinux/extension.log

```
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: Failed to get blob properties with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 207, in GetBlobProperties
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: retry times is 3
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: Failed to get blob properties with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 207, in GetBlobProperties
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: retry times is 2
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: Failed to get blob properties with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 207, in GetBlobProperties
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobProperties: retry times is 1
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]GetBlobType: Blob-Type :BlockBlob
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to committing the log with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 67, in WriteBlockBlob
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]retry times is 3
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to committing the log with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 67, in WriteBlockBlob
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]retry times is 2
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to construct ConfigurationProvider, which may due to the old wala code.
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]Failed to committing the log with error: __init__() takes exactly 2 arguments (1 given), stack trace: Traceback (most recent call last):
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/blobwriter.py", line 67, in WriteBlockBlob
2019/03/01 17:58:35     http_util = HttpUtil(self.hutil)
2019/03/01 17:58:35   File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9147.0/main/HttpUtil.py", line 43, in __init__
2019/03/01 17:58:35     Config = waagent.ConfigurationProvider()
2019/03/01 17:58:35 TypeError: __init__() takes exactly 2 arguments (1 given)
2019/03/01 17:58:35 
2019/03/01 17:58:35 [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0]retry times is 1

```

**Comment by vrdmr** [comment]
Hi @dops0 - Thanks for reporting the issue. I'll forward this to the extension owner. Thanks.
