### ISSUE TITLE
[BUG] WARNING ExtHandler Fetch failed from [http://168.63.129.16:32526/extensionArtifact]: [HTTP Failed] [400: Bad Request]

### ISSUE THREAD

**Issue by jim-minter** [Azure/WALinuxAgent#1505]
**Describe the bug**

Custom script extension failed to run on VMSS instance startup

Full journal at https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/1464/pull-ci-openshift-openshift-azure-master-e2e-azure/3567/artifacts/internal-e2e/infra-1555167065-000001-early-journal

I think this is the interesting snippet:
```
Apr 13 14:55:05 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:55:05.325941 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Target handler state: enabled
Apr 13 14:55:05 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:55:05.327848 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] [Enable] current handler state is: notinstalled
Apr 13 14:55:05 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:55:05.342185 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Downloading extension package: https://zrdfepirv2bl5prdstr04.blob.core.windows.net/708cdbbfb9ad4802ac80a012992930b1/Microsoft.Azure.Extensions__CustomScript__2.0.6
Apr 13 14:55:06 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:55:06.175582 INFO ExtHandler Route table: [{"Iface": "eth0", "Destination": "0.0.0.0", "Gateway": "10.0.0.1", "Mask": "0.0.0.0", "Flags": "0x0003", "Metric": "100"},{"Iface": "eth0", "Destination": "10.0.0.0", "Gateway": "0.0.0.0", "Mask": "255.255.255.0", "Flags": "0x0001", "Metric": "100"},{"Iface": "eth0", "Destination": "168.63.129.16", "Gateway": "10.0.0.1", "Mask": "255.255.255.255", "Flags": "0x0007", "Metric": "100"},{"Iface": "eth0", "Destination": "169.254.169.254", "Gateway": "10.0.0.1", "Mask": "255.255.255.255", "Flags": "0x0007", "Metric": "100"},{"Iface": "docker0", "Destination": "172.17.0.0", "Gateway": "0.0.0.0", "Mask": "255.255.0.0", "Flags": "0x0001", "Metric": "0"}]
Apr 13 14:55:06 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:55:06.208210 INFO ExtHandler Initial NIC state: [{ "name": "lo", "link": "<LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000\    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00" }, { "name": "docker0", "link": "<NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default \    link/ether 02:42:3d:56:33:42 brd ff:ff:ff:ff:ff:ff" }, { "name": "eth0", "link": "<BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000\    link/ether 00:0d:3a:1f:cf:c5 brd ff:ff:ff:ff:ff:ff" }]
Apr 13 14:55:41 infra-1555167065-000001 chronyd[3911]: Source 204.11.201.12 replaced with 206.55.191.142
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:56:36.533114 WARNING ExtHandler Fetch failed from [http://168.63.129.16:32526/extensionArtifact]: [HTTP Failed] [400: Bad Request]
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:56:36.540206 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Unzipping extension package: /var/lib/waagent/Microsoft.Azure.Extensions__CustomScript__2.0.6.zip
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:56:36.540690 INFO ExtHandler Error while unzipping extension package: File is not a zip file
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:56:36.543299 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Downloading extension package: https://zrdfepirv2bl5prdstr02.blob.core.windows.net/708cdbbfb9ad4802ac80a012992930b1/Microsoft.Azure.Extensions__CustomScript__2.0.6
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:56:36.652717 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Unzipping extension package: /var/lib/waagent/Microsoft.Azure.Extensions__CustomScript__2.0.6.zip
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:56:36.721195 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Initialize extension directory
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:56:36.724606 ERROR [Microsoft.Azure.Extensions.CustomScript-2.0.6] Failed to save handler status: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.6/config/HandlerStatus', Traceback (most recent call last):
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: File "build/bdist.linux-x86_64/egg/azurelinuxagent/ga/exthandlers.py", line 1295, in set_handler_status
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: fileutil.write_file(status_file, handler_status_json)
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: File "build/bdist.linux-x86_64/egg/azurelinuxagent/common/utils/fileutil.py", line 76, in write_file
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: with open(filepath, mode) as out_file:
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: IOError: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.6/config/HandlerStatus'
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:56:36.733838 ERROR ExtHandler Event: name=Microsoft.Azure.Extensions.CustomScript, op=Download, message=[Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.6/config', duration=0
Apr 13 14:56:36 infra-1555167065-000001 waagent[7155]: 2019/04/13 14:56:36.814312 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Remove extension handler directory: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.6
```

**Distro and WALinuxAgent details:**
 - RHEL 7.latest
 - WALinuxAgent 2.2.39

**Comment by jim-minter** [comment]
@amanohar fyi

^ above happened in subscription id 225e02bc-43d0-43d1-a01a-17e584a4ef69, resource group e2e-create-mjudeikis-1464-pmqtan, eastus region; timestamps in link above are in UTC.

**Comment by jim-minter** [comment]
In this case, the error happened to one node in the infra scaleset - the other nodes in the scaleset, and in the other scalesets booted fine

**Comment by larohra** [comment]
The fix for this issue has been merged with the develop branch. 
PR - [](https://github.com/Azure/WALinuxAgent/pull/1510)
Pending deployment.
