### ISSUE TITLE
Error during Waagent update due to lower methode not existing

### ISSUE THREAD

**Issue by plessisa** [Azure/WALinuxAgent#1597]
When trying to update to 2.2.41, we got the following error:

We got the following logs:
2019/08/01 14:02:22.247601 WARNING ExtHandler Agent WALinuxAgent-2.2.41 failed with exception: 'NoneType' object has no attribute 'lower'
]
2019/08/01 14:02:22.267883 WARNING ExtHandler Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/azurelinuxagent/ga/update.py", line 278, in run
    self._ensure_cgroups_initialized()
  File "build/bdist.linux-x86_64/egg/azurelinuxagent/ga/update.py", line 453, in _ensure_cgroups_initialized
    configurator = CGroupConfigurator.get_instance()
  File "build/bdist.linux-x86_64/egg/azurelinuxagent/common/cgroupconfigurator.py", line 179, in get_instance
    CGroupConfigurator._instance = CGroupConfigurator.__impl()
  File "build/bdist.linux-x86_64/egg/azurelinuxagent/common/cgroupconfigurator.py", line 43, in __init__
    self._cgroups_supported = osutil.is_cgroups_supported()
  File "build/bdist.linux-x86_64/egg/azurelinuxagent/common/osutil/default.py", line 309, in is_cgroups_supported
    if DISTRO_CODE_NAME.lower() is "trusty":
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by plessisa** [comment]
I will submit a review shortly

**Comment by pgombar** [comment]
Hi @plessisa, thanks for your contribution. That part of the code is actually unnecessary and we had planned to clean up the method `is_cgroups_supported`. This will be done in #1599.

**Comment by pgombar** [comment]
The fix is merged in #1599 and will be shipped in the next agent release. Closing the issue.
