### ISSUE TITLE
[BUG]AttributeError: 'tuple' object has no attribute 'read'  =  code=exited, status=1/FAILURE

### ISSUE THREAD

**Issue by v-jashed** [Azure/WALinuxAgent#1705]
description of what the bug is:

I'm Able to install the waagent and start it normally but when ever I want to restart it using systemctl restart waagent it crash with the error below. 

1. Section of the log where the error occurs.

```
2019-11-06T19:59:48.103085-03:00 devpo1a systemd[1]: Started Azure Linux Agent.
2019-11-06T19:59:48.221809-03:00 devpo1a python3[130705]: Traceback (most recent call last):
2019-11-06T19:59:48.222010-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/common/future.py", line 49, in get_linux_distribution
2019-11-06T19:59:48.222168-03:00 devpo1a python3[130705]:     return get_linux_distribution_from_distro(get_full_name)
2019-11-06T19:59:48.222352-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/common/future.py", line 65, in get_linux_distribution_from_distro
2019-11-06T19:59:48.222497-03:00 devpo1a python3[130705]:     full_distribution_name=get_full_name
2019-11-06T19:59:48.222668-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 120, in linux_distribution
2019-11-06T19:59:48.222802-03:00 devpo1a python3[130705]:     return _distro.linux_distribution(full_distribution_name)
2019-11-06T19:59:48.222917-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 634, in linux_distribution
2019-11-06T19:59:48.223039-03:00 devpo1a python3[130705]:     self.version(),
2019-11-06T19:59:48.223161-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 688, in version
2019-11-06T19:59:48.223350-03:00 devpo1a python3[130705]:     self.lsb_release_attr('release'),
2019-11-06T19:59:48.223494-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 836, in lsb_release_attr
2019-11-06T19:59:48.223663-03:00 devpo1a python3[130705]:     return self._lsb_release_info.get(attribute, '')
2019-11-06T19:59:48.223780-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 522, in __get__
2019-11-06T19:59:48.223899-03:00 devpo1a python3[130705]:     ret = obj.__dict__[self._fname] = self._f(obj)
2019-11-06T19:59:48.224033-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 933, in _lsb_release_info
2019-11-06T19:59:48.224149-03:00 devpo1a python3[130705]:     stdout = subprocess.check_output(cmd, stderr=devnull)
2019-11-06T19:59:48.224318-03:00 devpo1a python3[130705]:   File "/usr/lib64/python3.6/subprocess.py", line 336, in check_output
2019-11-06T19:59:48.224459-03:00 devpo1a python3[130705]:     **kwargs).stdout
2019-11-06T19:59:48.224643-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/run/__init__.py", line 145, in __new__
2019-11-06T19:59:48.224778-03:00 devpo1a python3[130705]:     process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
2019-11-06T19:59:48.225039-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/run/__init__.py", line 121, in create_process
2019-11-06T19:59:48.225196-03:00 devpo1a python3[130705]:     shlex.split(command),
2019-11-06T19:59:48.225406-03:00 devpo1a python3[130705]:   File "/usr/lib64/python3.6/shlex.py", line 305, in split
2019-11-06T19:59:48.225578-03:00 devpo1a python3[130705]:     return list(lex)
2019-11-06T19:59:48.225716-03:00 devpo1a python3[130705]:   File "/usr/lib64/python3.6/shlex.py", line 295, in __next__
2019-11-06T19:59:48.225830-03:00 devpo1a python3[130705]:     token = self.get_token()
2019-11-06T19:59:48.225944-03:00 devpo1a python3[130705]:   File "/usr/lib64/python3.6/shlex.py", line 105, in get_token
2019-11-06T19:59:48.226063-03:00 devpo1a python3[130705]:     raw = self.read_token()
2019-11-06T19:59:48.226179-03:00 devpo1a python3[130705]:   File "/usr/lib64/python3.6/shlex.py", line 136, in read_token
2019-11-06T19:59:48.226374-03:00 devpo1a python3[130705]:     nextchar = self.instream.read(1)
2019-11-06T19:59:48.226521-03:00 devpo1a python3[130705]: AttributeError: 'tuple' object has no attribute 'read'
2019-11-06T19:59:48.226683-03:00 devpo1a python3[130705]: During handling of the above exception, another exception occurred:
2019-11-06T19:59:48.226800-03:00 devpo1a python3[130705]: Traceback (most recent call last):
2019-11-06T19:59:48.226916-03:00 devpo1a python3[130705]:   File "/usr/sbin/waagent", line 31, in <module>
2019-11-06T19:59:48.227031-03:00 devpo1a python3[130705]:     import azurelinuxagent.agent as agent
2019-11-06T19:59:48.227146-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/agent.py", line 33, in <module>
2019-11-06T19:59:48.227326-03:00 devpo1a python3[130705]:     import azurelinuxagent.common.event as event
2019-11-06T19:59:48.227471-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/common/event.py", line 33, in <module>
2019-11-06T19:59:48.227643-03:00 devpo1a python3[130705]:     from azurelinuxagent.common.protocol.restapi import TelemetryEventParam, \
2019-11-06T19:59:48.227762-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/common/protocol/__init__.py", line 18, in <module>
2019-11-06T19:59:48.227879-03:00 devpo1a python3[130705]:     from azurelinuxagent.common.protocol.util import get_protocol_util, \
2019-11-06T19:59:48.227994-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/common/protocol/util.py", line 34, in <module>
2019-11-06T19:59:48.228108-03:00 devpo1a python3[130705]:     from azurelinuxagent.common.osutil import get_osutil
2019-11-06T19:59:48.228276-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/common/osutil/__init__.py", line 18, in <module>
2019-11-06T19:59:48.228422-03:00 devpo1a python3[130705]:     from azurelinuxagent.common.osutil.factory import get_osutil
2019-11-06T19:59:48.228563-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/common/osutil/factory.py", line 20, in <module>
2019-11-06T19:59:48.228726-03:00 devpo1a python3[130705]:     from azurelinuxagent.common.version import *
2019-11-06T19:59:48.228900-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/common/version.py", line 141, in <module>
2019-11-06T19:59:48.229019-03:00 devpo1a python3[130705]:     __distro__ = get_distro()
2019-11-06T19:59:48.229134-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/common/version.py", line 84, in get_distro
2019-11-06T19:59:48.229311-03:00 devpo1a python3[130705]:     osinfo = get_linux_distribution(0, 'alpine')
2019-11-06T19:59:48.229457-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/common/future.py", line 53, in get_linux_distribution
2019-11-06T19:59:48.229634-03:00 devpo1a python3[130705]:     return get_linux_distribution_from_distro(get_full_name)
2019-11-06T19:59:48.229765-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/azurelinuxagent/common/future.py", line 65, in get_linux_distribution_from_distro
2019-11-06T19:59:48.229880-03:00 devpo1a python3[130705]:     full_distribution_name=get_full_name
2019-11-06T19:59:48.229993-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 120, in linux_distribution
2019-11-06T19:59:48.230105-03:00 devpo1a python3[130705]:     return _distro.linux_distribution(full_distribution_name)
2019-11-06T19:59:48.230271-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 634, in linux_distribution
2019-11-06T19:59:48.230418-03:00 devpo1a python3[130705]:     self.version(),
2019-11-06T19:59:48.230562-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 688, in version
2019-11-06T19:59:48.230724-03:00 devpo1a python3[130705]:     self.lsb_release_attr('release'),
2019-11-06T19:59:48.230839-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 836, in lsb_release_attr
2019-11-06T19:59:48.230953-03:00 devpo1a python3[130705]:     return self._lsb_release_info.get(attribute, '')
2019-11-06T19:59:48.231069-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 522, in __get__
2019-11-06T19:59:48.231183-03:00 devpo1a python3[130705]:     ret = obj.__dict__[self._fname] = self._f(obj)
2019-11-06T19:59:48.231381-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/distro.py", line 933, in _lsb_release_info
2019-11-06T19:59:48.231525-03:00 devpo1a python3[130705]:     stdout = subprocess.check_output(cmd, stderr=devnull)
2019-11-06T19:59:48.231686-03:00 devpo1a python3[130705]:   File "/usr/lib64/python3.6/subprocess.py", line 336, in check_output
2019-11-06T19:59:48.231802-03:00 devpo1a python3[130705]:     **kwargs).stdout
2019-11-06T19:59:48.231917-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/run/__init__.py", line 145, in __new__
2019-11-06T19:59:48.232034-03:00 devpo1a python3[130705]:     process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
2019-11-06T19:59:48.232150-03:00 devpo1a python3[130705]:   File "/usr/lib/python3.6/site-packages/run/__init__.py", line 121, in create_process
2019-11-06T19:59:48.232329-03:00 devpo1a python3[130705]:     shlex.split(command),
2019-11-06T19:59:48.232473-03:00 devpo1a python3[130705]:   File "/usr/lib64/python3.6/shlex.py", line 305, in split
2019-11-06T19:59:48.232657-03:00 devpo1a python3[130705]:     return list(lex)
2019-11-06T19:59:48.232803-03:00 devpo1a python3[130705]:   File "/usr/lib64/python3.6/shlex.py", line 295, in __next__
2019-11-06T19:59:48.232953-03:00 devpo1a python3[130705]:     token = self.get_token()
2019-11-06T19:59:48.233067-03:00 devpo1a python3[130705]:   File "/usr/lib64/python3.6/shlex.py", line 105, in get_token
2019-11-06T19:59:48.233182-03:00 devpo1a python3[130705]:     raw = self.read_token()
2019-11-06T19:59:48.233375-03:00 devpo1a python3[130705]:   File "/usr/lib64/python3.6/shlex.py", line 136, in read_token
2019-11-06T19:59:48.233522-03:00 devpo1a python3[130705]:     nextchar = self.instream.read(1)
2019-11-06T19:59:48.233690-03:00 devpo1a python3[130705]: AttributeError: 'tuple' object has no attribute 'read'
2019-11-06T19:59:48.235273-03:00 devpo1a systemd[1]: waagent.service: Main process exited, code=exited, status=1/FAILURE
2019-11-06T19:59:48.235545-03:00 devpo1a systemd[1]: waagent.service: Unit entered failed state.
2019-11-06T19:59:48.235719-03:00 devpo1a systemd[1]: waagent.service: Failed with result 'exit-code'.
```

**Distro and WALinuxAgent details :**
 - Distro and Version: SLES15
 - WALinuxAgent version : 2.2.36-38.2.noarch

**Comment by vrdmr** [comment]
On the box  - can you run `distro.linux_distribution(full_distribution_name=0)` and paste the output? 
 Something like this should show up.
```
>>> import distro
>>> distro.linux_distribution(full_distribution_name=0)
(u'darwin', u'19.0.0', '')
```

Also - output of python --version
```
wus-dev:~$ python --version
Python 2.7.15+
```

**Comment by v-jashed** [comment]
![image](https://user-images.githubusercontent.com/57534388/68868633-79301000-06bd-11ea-9035-7451d53355ef.png)

Screenshots attached.

**Comment by vrdmr** [comment]
Environment issue - Looking at the distro modules source code - The customer is failing to do this call (example of the output)

```
distro.lsb_release_attr('release')
```
Which underneath relies on `lsb_release -a`

I would recommend opening a case against the distro module's [github page.](https://github.com/nir0s/distro/. Looking at the [`distro` (link)](https://pypi.org/project/distro/)'s page, 
it [points ](https://github.com/nir0s/distro/tree/master/tests/resources/distros)to the distros on which this module was tested and SLES 15 isn't on the test suite currently.

**Comment by vrdmr** [comment]
Any updates @v-jashed?

**Comment by v-jashed** [comment]
Having issues with python not even using pip we can uninstall the distro module so that we can try to uninstall it.
![image](https://user-images.githubusercontent.com/57534388/69385377-c5162280-0c84-11ea-8efb-bbd07100da5a.png)

**Comment by vrdmr** [comment]
It looks like an issue with the environment then. Nothing we can do to help you here. Closing the issue. If the python issues are resolved and the issue still persists, please reopen the issue or create a new one.

Thanks.
