### ISSUE TITLE
[BUG] WARNING Daemon cloud-init does not appear to be running

### ISSUE THREAD

**Issue by axelgMS** [Azure/WALinuxAgent#1933]
CRI 194661906 - Azure Linux VM failing to provision. waagent.log says:

_2020/06/30 17:35:11.106235 INFO Daemon Azure Linux Agent Version:2.2.38
2020/06/30 17:35:11.130331 INFO Daemon OS: redhat 7.8
2020/06/30 17:35:11.136431 INFO Daemon Python: 2.7.5_
...
_2020/06/30 17:35:11.572091 INFO Daemon Running CloudInit provisioning handler
2020/06/30 17:35:11.579520 INFO Daemon Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1800 retries remaining, sleeping 1s]
2020/06/30 17:35:12.617185 INFO Daemon Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1799 retries remaining, sleeping 1s]
2020/06/30 17:35:12.646217 WARNING **Daemon cloud-init does not appear to be running**
2020/06/30 17:35:13.653819 INFO Daemon Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1798 retries remaining, sleeping 1s]
2020/06/30 17:35:13.661455 WARNING **Daemon cloud-init does not appear to be running**
2020/06/30 17:35:14.662935 INFO Daemon Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1797 retries remaining, sleeping 1s]
2020/06/30 17:35:14.668357 WARNING **Daemon cloud-init does not appear to be running**_

and cloud-init.log says:

_2020-06-30 17:35:07,614 - handlers.py[DEBUG]: start: azure-ds/_get_metadata_from_imds: _get_metadata_from_imds
2020-06-30 17:35:07,615 - url_helper.py[DEBUG]: [0/4] open 'http://169.254.169.254/metadata/instance?api-version=2017-12-01' with {'url': 'http://169.254.169.254/metadata/instance?api-version=2017-12-01', 'headers': {'Metadata': 'true', 'User-Agent': 'Cloud-Init/18.5'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 2.0} configuration
2020-06-30 17:35:07,698 - url_helper.py[DEBUG]: Read from http://169.254.169.254/metadata/instance?api-version=2017-12-01 (200, 951b) after 1 attempts
2020-06-30 17:35:07,698 - handlers.py[DEBUG]: finish: azure-ds/_get_metadata_from_imds:_ **FAIL: _get_metadata_from_imds**_

followed by:

_2020-06-30 17:35:07,724 - util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceAzure.DataSourceAzure'> failed
2020-06-30 17:35:07,724 - util.py[DEBUG]: Getting data from <class 'cloudinit.sources.DataSourceAzure.DataSourceAzure'> failed
Traceback (most recent call last):_
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/__init__.py", line 733, in find_source
    if s.update_metadata([EventType.BOOT_NEW_INSTANCE]):
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/__init__.py", line 622, in update_metadata
    result = self.get_data()
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/__init__.py", line 256, in get_data
    return_value = self._get_data()
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/helpers/azure.py", line 40, in impl
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/DataSourceAzure.py", line 498, in _get_data
    func=self.crawl_metadata)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 2543, in log_time
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/helpers/azure.py", line 40, in impl
    return func(*args, **kwargs)
 File "/usr/lib/python2.7/site-packages/cloudinit/sources/DataSourceAzure.py", line 439, in crawl_metadata
    self.fallback_interface, retries=3)
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/helpers/azure.py", line 40, in impl
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/DataSourceAzure.py", line 1299, in get_metadata_from_imds
    return util.log_time(**kwargs)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 2543, in log_time
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/helpers/azure.py", line 40, in impl
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cloudinit/sources/DataSourceAzure.py", line 1316, in _get_metadata_from_imds
    except json.decoder.JSONDecodeError:
AttributeError: 'module' object has no attribute 'JSONDecodeError'_

This is caused by the IMDS service which is returning metadata about the VM and its Resource Group.

In this case, the RG has a tag containing a Unicode character - and this is causing Cloud-Init to fail decoding it. 
eg.
            "tags": {
                "key1": "Mise-à-jour",
or
                "key2": "Fiscalité",

One solution is to NOT use unicode characters in the RG Name, or in tags - but these are accepted by ARM convention (https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftresources).

ASKS:
- Get Cloud-Init to support Unicode characters
- Get WALinuxAgent to throw an actionable error message to the user - so we know how to avoid the error
- Get WALinuxAgent fail faster - so we don't have to retry 2000 times to copy the ovf-env.xml file

**Comment by trstringer** [comment]
I'm unable to repro this:

```
$ az group create -n rg1 -l eastus --tags notes=Mise-à-jour
$ az vm create -g rg1 ....
```

Then if I grep for `_get_metadata_from_imds` from the cloud-init logs after a successful provisioning I see:

```
2020-07-29 15:57:42,307 - handlers.py[DEBUG]: start: azure-ds/_get_metadata_from_imds: _get_metadata_from_imds
2020-07-29 15:57:42,394 - handlers.py[DEBUG]: finish: azure-ds/_get_metadata_from_imds: SUCCESS: _get_metadata_from_imds
```

Can you provide repro steps?

**Comment by axelgMS** [comment]
CRIs 194661906 & 196898588 

sorry I might have got confused with the tag in the RG instead of the VM.

**Comment by trstringer** [comment]
No problem! If this problem comes up, feel free to re-open this issue!

**Comment by dleborgne** [comment]
I came across this issue when creating a VM from the OpenLogic:CentOS:7_9:7.9.2023030700 image with a tag containing a non-ASCIII character :
```
az group create -l northeurope -n rg1
az vm create -n vm1 -g rg1 --image OpenLogic:CentOS:7_9:7.9.2023030700 -l northeurope --generate-ssh-keys --tags Customer="Compagnie Française"
``` 
VM provisioning does not succeed. Here are the boot diagnostics messages related to the failure of cloud-init. The link between cloud-init and the tag value is still puzzling me. 
```
util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceAzure.DataSourceAzure'> failed
systemd-fstab-generator[1073]: Checking was requested for "ephemeral0", but it is not a device.
Daemon Daemon Waiting for cloud-init to copy ovf-env.xml to /var/lib/waagent/ovf-env.xml [1800 retries remaining, sleeping 1s between retries]
cc_final_message.py[WARNING]: Used fallback datasource
```

Rocky Linux 9 (erockyenterprisesoftwarefoundationinc1653071250513:rockylinux-9:rockylinux-9:9.0.0) does not exhibit the same problem.
