### ISSUE TITLE
Temporary resource disk mounted as /mnt and no swap on rhel8 sku 8-lvm-gen2 latest

### ISSUE THREAD

**Issue by Klaas-** [Azure/WALinuxAgent#1971]
After installing the latest 8-lvm-gen2 RHEL8 on a B4ms I noticed that the /mnt/resource partition is not being mounted and that there is no swap being created. Instead it seems cloud-init has provisioned the disk like this:

```
# cat /etc/fstab |grep cloud
/dev/disk/cloud/azure_resource-part1    /mnt    auto    defaults,nofail,x-systemd.requires=cloud-init.service,comment=cloudconfig       0       2
```

Please advise if this behavior is wanted and recommended or if waagent should handle the resource disk and swap. Currently it seems this is explicitly set via waagent.conf in that image. RHEL 8.1 had different defaults.

**Distro and WALinuxAgent details (please complete the following information):**
 - RHEL 8.2 WALinuxAgent-2.2.46-1.el8.5.noarch
 - WALinuxAgent version
```
# waagent --version
WALinuxAgent-2.2.46 running on redhat 8.2
Python: 3.6.8
Goal state agent: 2.2.49.2
```

the image is with WALinuxAgent-2.2.38-1.el8, I did run yum update afterwards.

**Comment by trstringer** [comment]
This is the expected and desired behavior. It's by-design that cloud-init is handling the resource disk, and walinuxagent being aware of this. If you look in `/var/log/waagent.log` you should see something to the affect of "Resource disk ... is already mounted ..." assuming that `ResourceDisk.Format=y` is set in the config `/etc/waagent.conf`.

**Comment by Klaas-** [comment]
@trstringer so the default path for the Ressource disk changed to /mnt? And by default there is no longer swap?

**Comment by huahaiy** [comment]
It is not hard to create a swapfile on the mounted resource disk. However, if users are supposed to create their own swapfile on `/mnt`, the option for `ResoruceDiskEnableSwap` should be removed. Otherwise, it's confusing.

**Comment by trstringer** [comment]
Sorry for any confusion on this item. @Klaas-, `/mnt` is used for VMs that are provisioned with cloud-init (our modern approach to provisioning). `/mnt/resource` is used for VMs that are provisioned with walinuxagent. To enable swap, you can use cloud-init config to either enable a swap partition or continue to use a swap file.

**Comment by trstringer** [comment]
@huahaiy, users should not have to create their own swap file. For modern images that use cloud-init, the swap file will be created on `/mnt` and for VMs that don't have cloud-init and that are provisioned with walinuxagent the swap file will be created on `/mnt/resource`.

**Comment by ziesemer** [comment]
What was the motivation and/or standard for mounting the resource/temporary/ephemeral disk directly to `/mnt`?  Per my understanding of the Linux Filesystem Hierarchy Standard (FHS), `/mnt` is to be a location for temporarily-mounted filesystems, not a temporary file system itself.  This wrecks havoc with other standards and systems that depend on having existing mount point available under `/mnt` - which isn't possible when the entire disk may be re-created on a whim.

**Comment by Klaas-** [comment]
@trstringer the /mnt /mnt/resource thing feels like a breaking change that I would not expect within a major release of rhel :D Is that documented or is there a public changelog for these kind of changes to linuxes on azure?

the 2nd part, I am sure there was no swap created when I opened this issue, but I can retest that. But that would not be an issue with the walinuxagent if cloud-init is supposed to do that.

**Comment by trstringer** [comment]
> What was the motivation and/or standard for mounting the resource/temporary/ephemeral disk directly to `/mnt`? Per my understanding of the Linux Filesystem Hierarchy Standard (FHS), `/mnt` is to be a location for temporarily-mounted filesystems, not a temporary file system itself. This wrecks havoc with other standards and systems that depend on having existing mount point available under `/mnt` - which isn't possible when the entire disk may be re-created on a whim.

The choice of `/mnt` is a [cloud-init implementation detail](https://github.com/canonical/cloud-init/blob/master/cloudinit/config/cc_mounts.py#L371). The user can specify a non-default if that is undesired.

As for the documentation, I'll see if it exists with the change between paths. Thanks for bringing that to our attention!

**Comment by jpbuecken** [comment]
IMHO, the decision to use the default of cloud-init is not wise. I assume it is in the code because it is a generic decision for every cloud.

As user @Klaas- pointed out, it is a breaking change for Azure: E.g. we need to adapt our configuration management.
Second that, we have customer who mount further ephemeral storage or temporary mounts to /mnt. I do not like the idea to mount a temporary mount on top of a ephemeral mount.  I have the same understanding of the FHS as @ziesemer 

I like how OpenLogic solved it with their CentOS Image:
```
cat cloud.cfg.d/91-azure_datasource.cfg
# This configuration file is used to connect to the Azure DS sooner
datasource_list: [ Azure ]
# By default, the Azure ephemeral temporary resource disk will be mounted
# by cloud-init at /mnt/resource.
#
# If the mountpoint of the temporary resource disk is customized
# to be something else other than the /mnt/resource default mountpoint,
# the RequiresMountsFor and ConditionPathIsMountPoint options of the following
# systemd unit should be updated accordingly:
#   temp-disk-swapfile.service (/etc/systemd/system/temp-disk-swapfile.service)
#
# For additional details on the temporary resource disk please refer to the MSDN documentation at:
# https://docs.microsoft.com/en-us/azure/virtual-machines/linux/managed-disks-overview#temporary-disk
mounts:
  - [ ephemeral0, /mnt/resource ]
```

**Comment by picklesrein** [comment]
I also discovered this broken mechanism when rolling out RHEL8. Our script that looks for `/mnt/resource` fails because it no longer exists. @trstringer, did we ever locate the changelog for this? From what I found for the [Waagent](https://github.com/Azure/WALinuxAgent) it still references `/mnt/resource`.

I also agree with @ziesemer. This is contrary to how I've understood how the `/mnt` directory works. The examples provided in [The Linux Documentation Project](https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/mnt.html) also suggest that multiple mounts can live under this directory; but cannot in this case since the WAagent clobbers the whole thing from the top.

Is there a way to implement a cloud-init file to an image from the Marketplace, or would we need to move to managing custom images?

**Comment by Klaas-** [comment]
I have created a support request for this 121011824003656

Basically I think you need to make a decision about how consistent you want to be in Azure :)

The two main issues:
* Do you want to use /mnt or /mnt/resource for rhel? I would stronly suggest to keep this in sync with CentOS (at least CentOS, but ideally also with other linux distributions
* Do you want to automatically create swap or do you want a user to do this?

**Comment by Klaas-** [comment]
I would very much like to get a answer on the topic of use /mnt or /mnt/resource by default -- same for the swap created by default or not :) I know  that I can do all of this on my own via cloud-init custom data, but I'd rather not diverge from what I would consider "rhel defaults" and I would very much like centos/rhel to behave the same :)

highlighting @trstringer and @asinn826 for visibility again :)

**Comment by jpbuecken** [comment]
For your information, the choice for /mnt conflicts with some official AZURE / Micrsofot documentation.

For example, if you just follow the documentation [1] , the persistent mount of the Azure File is /mnt/$storageAccountName/$fileShareName

Since the resource disk is ephemeral, this will fail after reboot, at least after a deallocate, since the mount folder has vanished then

[1] https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-linux#create-a-persistent-mount-point-for-the-azure-file-share-with-etcfstab

**Comment by Klaas-** [comment]
@jpbuecken that would be the same argument @N3WWN made why the ephemeral disk is mounted to /mnt/resource for (OpenLogic) CentOS on Azure. In any case if /mnt is a fixed decision for rhel (which it seems like it is) the docs should be updated and you can open an issue against that page in the microsoft-docs repository.

**Comment by jpbuecken** [comment]
@Klaas-  yes, I was just pointing out real life example.

> In any case if /mnt is a fixed decision for rhel (which it seems like it is) 

Maybe you a right, we may need to open issues for the provider of the RHEL or Suse image (so, afaik this is Redhat and Suse themself?). They just depend on the cloud-init default, but the rougewave/openlogic approach makes more sence

**Comment by Klaas-** [comment]
> Maybe you a right, we may need to open issues for the provider of the RHEL or Suse image (so, afaik this is Redhat and Suse themself?). They just depend on the cloud-init default, but the rougewave/openlogic approach makes more sence

the rhel images are built by microsoft. all rhel images, even the byos.

**Comment by julienym** [comment]
Hi everyone,

Couldn't find anywhere else on the web except here the mention of temp-disk-swapfile.service
This service is WantedBy cloud-config, and therefore creates a swap file everytime you create a VM with custom-data (Azure word for cloud-init config)...

Is there a way to deactivate this ? 

Thanks

**Comment by ziesemer** [comment]
I'm now finding a need to fix this on an Azure VM that has already been provisioned, in-use, and not otherwise easily re-created - while ensuring the fix will remain even after a redeploy, etc., and receiving a new temporary disk from Azure.

https://docs.microsoft.com/en-us/azure/virtual-machines/custom-data#can-i-update-custom-data-after-the-vm-has-been-created mentions that "For single VMs, custom data in the VM model cannot be updated".  However, there has to be a way to get this to effectively re-run cloud-init - though I'm currently coming up short.  It seems that editing the Base64-encoded details within `/var/lib/waagent/ovf-env.xml` is where this needs to start.  However, attempts to then run `cloud-init clean` remove all other Azure-specifics and knowledge from the VM - such that `cloud-id` now returns `none` instead of `azure`, for example.  Looking for any help from anyone here that better understands how this process works from start to end here - especially as https://github.com/MicrosoftDocs/azure-docs/issues/68844 was since closed...

**Comment by picklesrein** [comment]
@saimsh-msft thanks for clarifying the suggested best practice. I think one reason this issue exists is that in my ~20 years of Linux administration it has been "not recommended" to clobber the entire /mnt directory with a single filesystem. 

going forward on the next build, would your team consider following established practices and mount the ephemeral disk at /mnt/resource like it used to be?

**Comment by jofrance** [comment]
This also breaks functionality with other Azure products, like ADE that still uses /mnt/azure_bek_disk and assumes that the resource drive needs to be mounted on /mnt/resource when it is encrypted, which overrides and sometimes duplicates the entries on /etc/fstab, which at the same time causes systemd to try to mount everything without having dependencies between those mount points. 

Quoting FSHS: 

"3.12. /mnt : Mount point for a temporarily
mounted filesystem
3.12.1. Purpose
This directory is provided so that the system administrator may temporarily mount a filesystem as needed.
The content of this directory is a local issue and should not affect the manner in which any program is run."

3.11. /media : Mount point for removable media
3.11.1. Purpose
This directory contains subdirectories which are used as mount points for removable media such as floppy
disks, cdroms and zip disks.
Rationale
Historically there have been a number of other different places used to mount removable media
such as /cdrom, /mnt or /mnt/cdrom. Placing the mount points for all removable media
directly in the root directory would potentially result in a large number of extra directories in
/. Although the use of subdirectories in /mnt as a mount point has recently been common, it
conflicts with a much older tradition of using /mnt directly as a temporary mount point.

**Comment by mike-estes-fl** [comment]
What is the workaround for this issue on already created VMs?

If we change `ResourceDisk.MountPoint=/mnt` to `ResourceDisk.MountPoint=/mnt/resource` in `/etc/waagent.conf` does that stay set per reboot of the VM or maintenance/move of VMs by Azure?  Or will something eventually undo that?

Or is there another way this should/could be done?  From what has been mentioned it appears that even after one changes fstab to either remove the mounting of this ephemeral disk or change the order then something undoes this when a reboot or move/maintenance is done.

We're not even using this Ephemeral disk, and had I known it would be an issue I would have tried to choose a sku that didn't have this option as it's currently a headache for us in how it's being handled.  Putting a volume mounted in `/mnt` is standard practice so far as I can tell, so putting this temporary ephemeral disk there seems like it should not have been done.

After looking more into an issue we're running into it seems this is the root cause for data we store in a volume mounted at `/mnt/data` is that the directory is getting blown away either on reboot or when the vm is moved or updated by Azure.  And happens to have some data files for our load balancer using haproxy.

And with further investigation looking at the cloud init logs it's also causing issues for the Azure Data Encryption volume.  Which was mentioned in the last message by jofrance.  Which I'm guessing gets set by Azure as I don't recall any configuration we've done that puts it in this location.

This is added to `/etc/fstab`:
`LABEL=BEK\040VOLUME /mnt/azure_bek_disk auto defaults,discard,nofail 0 0`

And this shows up in `/var/log/cloud-init.log`
```
2023-01-24 18:33:13,410 - subp.py[DEBUG]: Running command ['mount', '-a'] with allowed return codes [0] (shell=False, capture=True)
2023-01-24 18:33:13,429 - cc_mounts.py[WARNING]: Activate mounts: FAIL:mount -a
2023-01-24 18:33:13,430 - util.py[WARNING]: Activate mounts: FAIL:mount -a
2023-01-24 18:33:13,430 - util.py[DEBUG]: Activate mounts: FAIL:mount -a
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py", line 617, in handle
    subp.subp(cmd)
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 335, in subp
    raise ProcessExecutionError(
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['mount', '-a']
Exit code: 64
Reason: -
Stdout:
Stderr: mount: /mnt/azure_bek_disk: mount point does not exist.
        mount: /mnt/data: mount point does not exist.
```

**Comment by jofrance** [comment]
@mike-estes-fl changing this one /etc/waagent.conf will potentially not affect anything since the configuration for the resource drive when encrypted is handled by the ADE extension, it will re-create the entries on /etc/fstab as it encrypts the disk on each start after the vm its been deallocated. and on modern distros on Azure Cloud Init handles this disk, not waagent. 

/mnt/azure_bek_disk is setup by the ADE extension, the problem arises when Cloud Init mounts the resource drive on top of /mnt and it basically hides this folder. 

Ideally the resource disk should be mounted in a way that it doesn't conflict with the BEK volume that is used for ADE, which is one of the main problems here, we're working on eliminating the conflict by instructing cloud-init and ADE to mount the resource drive on the same please, let's say /mnt/resource and the BEK volume on a location that is not related to /mnt at all.

For already created VMs, 

You can instruct Cloud Init to mount the resource disk on /mnt/resource via a per-boot script, If ADE is also required to format it, it will then mount it on /mnt/azure_bek_disk, cloud init could be mounting it while the folder doesn't exists or is hidden below /mnt. 

For pinpointing your specific scenario, please open a support case with us so we can take a look and help you.

**Comment by mike-estes-fl** [comment]
> For already created VMs,
> You can instruct Cloud Init to mount the resource disk on /mnt/resource via a per-boot script,

@jofrance  For that do you mean this:

> [Cloud-init Final Stage](https://cloudinit.readthedocs.io/en/latest/topics/boot.html#final): At this final stage, the modules in cloud_final_modules, listed in /etc/cloud/cloud.cfg, runs. Here modules that need to be run late in the boot process run, such as package installations and run scripts etc.

> During this stage, you can run scripts by placing them in the directories under /var/lib/cloud/scripts:
> per-boot - scripts within this directory, run on every reboot

Found here?
https://learn.microsoft.com/en-us/azure/virtual-machines/linux/cloud-init-deep-dive#cloud-init-boot-stages-processing-configuration

If not, could you point me to the documentation that might help us figure this out?

I'm mostly a "windows" guy with enough "*nix" understanding to be dangerous.  LOL

**Comment by cherio** [comment]
This is indeed an issue. The standard Linux Documentation Project says `/mnt` "[is a generic mount point under which you mount your filesystems or devices](https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/mnt.html)".

This unorthodox MS design decision broke my company's installation and setup procedure.

**Comment by ryanc-me** [comment]
Just throwing my $0.02 in here - this is a really mind-boggling decision.

It's been established here (and other forums) that clobbering `/mnt` is _a really bad idea_ and that it has lead to _actual data-loss for some customers_. It also goes against the common understanding of the Linux filesystem.

I hope the Azure team will take this into consideration. The correct decision is to use `/mnt/resource`.

**Comment by fuxjezz** [comment]
We are stuck with loads of vm's running with a "scratch disk" (we don't need/want/can opt out of) and a non-persistant /mnt location as a result. 

We are baffled by these data-loss inducing mountpoint choices and the lack of support for parameters/mechanisms that allow customers to fix these design-errors (config parameters/running instances without "scratch-disks", whatever).

Having to apply a "non-supported" workaround/fix in order to have our VM's mount their datadisks properly on reboot is embarrasing, could have easily been avoided and the time needed to remedy this in a more or less stable way is tough to explain to our managers :/

**Comment by Klaas-** [comment]
> We are stuck with loads of vm's running with a "scratch disk" (we don't need/want/can opt out of) and a non-persistant /mnt location as a result.
> 
> We are baffled by these data-loss inducing mountpoint choices and the lack of support for parameters/mechanisms that allow customers to fix these design-errors (config parameters/running instances without "scratch-disks", whatever).
> 
> Having to apply a "non-supported" workaround/fix in order to have our VM's mount their datadisks properly on reboot is embarrasing, could have easily been avoided and the time needed to remedy this in a more or less stable way is tough to explain to our managers :/

I think you missed the point of this issue, but just so if the next person stumbles over this: you can opt out of the temporary resource disk. there are a lot of VM sizes that do not have one: https://learn.microsoft.com/en-us/azure/virtual-machines/dv5-dsv5-series#dv5-series generally speaking, usually the newer generations will have a size without a temp disk and one with a temp disk -- https://learn.microsoft.com/en-us/azure/virtual-machines/vm-naming-conventions#naming-convention-explanation (the *d* in the name).

**Comment by ryanc-me** [comment]
@Klaas- I don't think that's a good solution, because most of us are only discovering this issue _after_ the server has been provisioned (and, in my case, after it went to production).

This is such a ridiculous waste of time for everyone involved.

**Comment by N3WWN** [comment]
@ryanc-me One option for already provisioned systems is to adjust the size of the instance.  It will require the instance to be shut down and started back up after resizing, but it doesn't require building an entirely new instance.

**Comment by thecmdradama** [comment]
Hi all,

I would like to revive this issue as this is still fairly frustrating to deal with... 

We have several vm use-cases that are configured to use `/mnt/resource` for the ephemeral disk as location to store swap along with other applications that want a temp directory. Then using `/mnt` as expected for shared volumes i.e. SMB, NFS, etc. 

Say the VM uses the Azure Monitor Agent to mount the temporary ephemeral disk initially under `/mnt/resouce`, if cloud-init takes over at a later stage, say after implementing Azure Disk Encryption, this now causes issues with applications and potential dataloss because of mounting the ephemeral disk to `/mnt` instead of `/mnt/resource`...

**Comment by apjanke** [comment]
> One option for already provisioned systems is to adjust the size of the instance. It will require the instance to be shut down and started back up after resizing, but it doesn't require building an entirely new instance.

@N3WWN - Is that actually an option? In my experience, you can't use a VM resize to change whether a provisioned VM has a temporary disk or not. This ["Resize a VM" page](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/resize-vm?tabs=portal#limitations) in the Azure doco seems to agree. 

> Limitations
>
> You can't resize a VM size that has a local temp disk to a VM size with no local temp disk and vice versa.

Looks like you need to go through a [workaround](https://learn.microsoft.com/en-us/azure/virtual-machines/azure-vms-no-temp-disk#how-do-i-migrate-from-a-vm-size-with-local-temp-disk-to-a-vm-size-with-no-local-temp-disk---) where you provision a new VM and then use disk snapshots to move the contents of the OS disk from the old VM over to the new one.

**Comment by apjanke** [comment]
Do you know what, if anything, WALinuxAgent is going to do to handle the new Azure [D/E/Fads v6 series VMs](https://techcommunity.microsoft.com/blog/azurecompute/new-daeafav6-vms-with-increased-performance-and-azure-boost-are-now-generally-av/4309381), which have temp disks, but they're NVMe and handled somewhat differently.

For me, new Dads v6 VMs, with either RHEL 9.5 or Unbuntu 22.04/24.04, are coming with the temp disk not automatically set up and mounted, like it was on previous generations of D/Eds VMs. I think that's by design, per this ["temp NVMe disks in D/E_v6 VMs different from remote NVMe disks"](https://learn.microsoft.com/en-us/azure/virtual-machines/enable-nvme-temp-faqs#how-are-temp-nvme-disks-in-my-dl-d-e-v6-vms-different-from-remote-nvme-disks-) FAQ, which says:

> Unlike the previous D/E series VMs, the new v6 VMs come with raw, unformatted NVMe disks. Customers should initialize and format the disks into a file system of their preference after the VM starts up.

Does that mean that WALinuxAgent is a mechanism to use for this initialization and formatting, with cloud-init no longer taking over that part? Or is this more of a "some assembly required" thing, and customers now have to roll their own disk initialization scripts?

Sorry if I'm asking in the wrong place. I'm not clear on where the boundaries of responsibility are between cloud-init, WALinuxAgent, and Microsoft's own Azure-specific setup are.

**Comment by Klaas-** [comment]
> Do you know what, if anything, WALinuxAgent is going to do to handle the new Azure [D/E/Fads v6 series VMs](https://techcommunity.microsoft.com/blog/azurecompute/new-daeafav6-vms-with-increased-performance-and-azure-boost-are-now-generally-av/4309381), which have temp disks, but they're NVMe and handled somewhat differently.
> 
> For me, new Dads v6 VMs, with either RHEL 9.5 or Unbuntu 22.04/24.04, are coming with the temp disk not automatically set up and mounted, like it was on previous generations of D/Eds VMs. I think that's by design, per this ["temp NVMe disks in D/E_v6 VMs different from remote NVMe disks"](https://learn.microsoft.com/en-us/azure/virtual-machines/enable-nvme-temp-faqs#how-are-temp-nvme-disks-in-my-dl-d-e-v6-vms-different-from-remote-nvme-disks-) FAQ, which says:
> 
> > Unlike the previous D/E series VMs, the new v6 VMs come with raw, unformatted NVMe disks. Customers should initialize and format the disks into a file system of their preference after the VM starts up.
> 
> Does that mean that WALinuxAgent is a mechanism to use for this initialization and formatting, with cloud-init no longer taking over that part? Or is this more of a "some assembly required" thing, and customers now have to roll their own disk initialization scripts?
> 
> Sorry if I'm asking in the wrong place. I'm not clear on where the boundaries of responsibility are between cloud-init, WALinuxAgent, and Microsoft's own Azure-specific setup are.

I do think you're asking at the wrong place, but the answer I got a couple years back is basically: nothing we deal with, customer responsibility. https://github.com/MicrosoftDocs/azure-docs/issues/72921 -- I do not think it has changed from the msft side, but I would gladly learn that they have reevaluated their point of view and now support initializing them via cloud-init for example. That issue also includes a link to a service that the azure hpc people used for their nvme usage

**Comment by cherio** [comment]
It gets worse.

While running Ubuntu 22.04 I made a change in `/etc/waagent.conf` replacing line

`ResourceDisk.MountPoint=/mnt`
with
`ResourceDisk.MountPoint=/mnt/azure`

Recently I had to do the inplace OS upgrade to 24.04 with `do-release-upgrade`. After the upgrade finished I discovered that my configuration changes in `/etc/waagent.conf` were reverted back without prompting me the way the update process normally does when it is about to update config files in `etc`.

It was pure luck I noticed this and fortunately avoided data loss

**Comment by apjanke** [comment]
Thanks @Klaas-. That other ticket looks like exactly my question here, and it sounds like I've got a new little scripting project to do before we really adopt these new NVMe-using VM series.

**Comment by N3WWN** [comment]
> [@N3WWN](https://github.com/N3WWN) - Is that actually an option? In my experience, you can't use a VM resize to change whether a provisioned VM has a temporary disk or not. This ["Resize a VM" page](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/resize-vm?tabs=portal#limitations) in the Azure doco seems to agree.


Sorry, @apjanke , it appears that resize is no longer offered between local disk types (with vs without).  

While I don't have anything handy showing that this previously *WAS* an option, I am pretty sure it did work ... at one time.
