### ISSUE TITLE
[BUG] wala agent tried to install LIS driver in CentOS 7.8

### ISSUE THREAD

**Issue by juhlee-microsoft** [Azure/WALinuxAgent#1984]
**Describe the bug: A clear and concise description of what the bug is.**
LIS installation is only available less than RHEL/CentOS 7.7. There is no need it in 7.8 or higher version.

Note: Please add some context which would help us understand the problem better
1. Provision CentOS 7.8
2. Serial console output
3. Steps to reproduce the behavior.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: [e.g. Ubuntu 16.04]
 - WALinuxAgent version [e.g. 2.2.40, you can copy the output of `waagent --version`, more info [here](https://github.com/Azure/WALinuxAgent/wiki/FAQ#what-does-goal-state-agent-mean-in-waagent---version-output) ]

**Additional context**
This is the waagent log.

2020/08/18 18:08:23.039358 INFO Daemon Run daemon
2020/08/18 18:08:23.048474 INFO Daemon cloud-init is enabled: True
2020/08/18 18:08:23.051340 INFO Daemon Using cloud-init for provisioning
2020/08/18 18:08:23.054655 INFO Daemon Clean protocol
2020/08/18 18:08:23.058514 INFO Daemon Provisioning already completed, skipping.
2020/08/18 18:08:33.097048 INFO Daemon RDMA: kvp daemon (hypervkvpd) is running
2020/08/18 18:08:33.098664 INFO Daemon RDMA: kvp daemon running: True
2020/08/18 18:08:43.110361 INFO Daemon RDMA: found firmware version: 144.0
2020/08/18 18:08:43.143359 INFO Daemon RDMA: driver package is NOT installed
2020/08/18 18:08:43.144394 INFO Daemon RDMA: updating RDMA packages
2020/08/18 18:08:43.145273 INFO Daemon RDMA: refreshing yum repos
2020/08/18 18:08:45.316039 INFO Daemon RDMA: repositories refreshed
2020/08/18 18:08:45.317615 INFO Daemon RDMA: Force installing package: msft-rdma-drivers
2020/08/18 18:08:50.347330 INFO Daemon RDMA: installation completed: msft-rdma-drivers
2020/08/18 18:08:50.348594 INFO Daemon RDMA: **pkgs dir: /opt/microsoft/rdma/rhel78**
2020/08/18 18:08:50.352623 ERROR Daemon Event: name=WALinuxAgent, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 81, in run
    self.daemon(child_args)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 144, in daemon
    self.rdma_handler.install_driver_if_needed()
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/rdma.py", line 157, in install_driver_if_needed
    self.install_driver()
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/rdma/centos.py", line 79, in install_driver
    self.update_rdma_package(fw_version)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/rdma/centos.py", line 109, in update_rdma_package
    self.install_rdma_drivers(fw_version)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/rdma/centos.py", line 148, in install_rdma_drivers
    raise Exception('RDMA packages directory %s is missing' % pkg_dir)
Exception: RDMA packages directory /opt/microsoft/rdma/rhel78 is missing
, duration=0
2020/08/18 18:08:50.354927 WARNING Daemon Daemon ended with exception -- Sleep 15 seconds and restart daemon

There is no rhel78 directory

[root@controller-vm infiniband]# cd /opt/microsoft/rdma/rhel
rhel610/ rhel65/  rhel68/  rhel69/  rhel71/  rhel72/  rhel73/  rhel74/  rhel75/
[root@controller-vm infiniband]# 

**Log file attached**
If possible, please provide the full /var/log/waagent.log file to help us understand the problem better and get the context of the issue.

I have a full log. Please reach out to me.

**Comment by narrieta** [comment]
@longlimsft - could you take a look at this one? thanks!

**Comment by andschwa** [comment]
@juhlee-microsoft Can you confirm that you mean the LIS Drivers? As far as I can tell based on this log and the code, it's trying to install the `msft-rdma-drivers` package. I'm trying to confirm where this package comes from, and how it's different from the general "LIS Drivers" RPM provided for RedHat and CentOS (which also have the RDMA driver backported, as far as I can tell).

**Comment by longlimsft** [comment]
We don't have RDMA ND drivers for CentOS 7.8. 

When deploying to a ND HPC VM, need to comment out OS.EnableRDMA in /etc/waagent.conf.

**Comment by andschwa** [comment]
@longlimsft Okay, that's what I thought was meant, but the issue said "LIS Drivers" and "LIS installation." Thanks for the clarification!
