### ISSUE TITLE
WALA provisioning failed: AttributeError: 'array.array' object has no attribute 'tostring'

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#2080]
Description of problem:
WALA provisioning failed because of "AttributeError: 'array.array' object has no attribute 'tostring'"
The root cause is in python3.9 array.array doesn't have tostring(), should use tobytes() instead.
(In azurelinuxagent/common/osutil/default.py _get_all_interfaces function)

Version-Release number of selected components (if applicable):
WALinuxAgent-2.2.48.1-2.el9.noarch

How reproducible:
100%

Steps to Reproduce:
1. Create a RHEL VM on Azure with python 3.9 installed and use WALA as provisioning agent.

Actual results:
Provisioning failed.

# cat /var/log/waagent.log
2020-11-16T13:30:09.916260Z ERROR Daemon Daemon Event: name=WALinuxAgent, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/daemon/main.py", line 84, in run
    self.daemon(child_args)
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/daemon/main.py", line 146, in daemon
    self.provision_handler.run()
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/pa/provision/default.py", line 84, in run
    self.provision(ovf_env)
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/pa/provision/default.py", line 226, in provision
    self.osutil.publish_hostname(ovfenv.hostname)
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/common/osutil/default.py", line 1153, in publish_hostname
    ifname = self.get_if_name()
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/common/osutil/default.py", line 1049, in get_if_name
    if_name = self.get_first_if()[0]
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/common/osutil/default.py", line 816, in get_first_if
    ifaces = self._get_all_interfaces()
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/common/osutil/default.py", line 799, in _get_all_interfaces
    ifconf_buff = buff.tostring()
AttributeError: 'array.array' object has no attribute 'tostring'
, duration=0

Expected results:
Provisioning success

**Comment by pgombar** [comment]
Thanks for reporting this @yuxisun1217. We will address this as part of our task to make the Agent compatible with Python 3.9.

Is the image you are using with preinstalled Python 3.9 a RHEL image from Azure Marketplace?

**Comment by yuxisun1217** [comment]
Hi @pgombar ,
No it's not an image from Azure Marketplace, but a RHEL version that will be released in the future. The python 3.9 is the default python of it. So that we may need to make WALA adapt to python 3.9. Thanks!

**Comment by pgombar** [comment]
Will be fixed in #2082

**Comment by AkechiShiro** [comment]
I still ran into this issue with Python 3.9.2 on Debian 11, what's going on ??

**Comment by AkechiShiro** [comment]
What would be necessary for reporting this issue again ?
> 2023-08-20T15:30:56.222250Z INFO Daemon Daemon Azure Linux Agent Version:2.2.47

**Comment by rohan-97** [comment]
Hi @AkechiShiro ,  

looks like this fix is added in waagent `v2.2.54.2` whereas debian bullseye ships `v2.2.47`  
so this code fix is not present in waagent shipped by debian.  

I guess you need to compile waagent from the source
