### ISSUE TITLE
WALinuxAgent bring down NIC with error: azurelinuxagent.common.exception.HttpError: [HttpError] [HTTP Failed] POST http://168.63.129.16/machine?comp=telemetrydata -- IOError timed out -- 6 attempts made

### ISSUE THREAD

**Issue by lyan-git** [Azure/WALinuxAgent#2129]
WALinuxAgent bring down NIC with error: azurelinuxagent.common.exception.HttpError: [HttpError] [HTTP Failed] POST http://168.63.129.16/machine?comp=telemetrydata -- IOError timed out -- 6 attempts made

We have an Azure VM with the following config:
1. distribution:  Ubuntu18.04 
2. Accelerated Network: enabled
3. waagent version: 
WALinuxAgent-2.2.45 running on ubuntu 18.04
Python: 3.6.9
Goal state agent: 2.2.53
4. Number of NICs: 3
5. Possible trigger:
    We are not sure, it happened to two of our VMs where some linux route updates( learned from Virtual Network Gateway) might in ongoing. But we are not sure if that is the cause.
6. Question we have:
    Seems it's getting some telemtrydata, why the error would trigger WALinuxAgent to turn down the interface?
6. Error syslog capture:
2021-01-07T22:24:26.146283+00:00 av-gw-lune-transit2-insane-hagw racoon: INFO: IPsec-SA expired: ESP/Tunnel 10.103.0.202[500]->10.102.1.10[500] spi=192630447(0xb7b4eaf)
2021-01-07T22:24:26.804016+00:00 av-gw-lune-transit2-insane-hagw racoon: INFO: IPsec-SA expired: ESP/Tunnel 10.103.0.202[500]->10.102.1.10[500] spi=202590005(0xc134735)
2021-01-07T22:24:26.960454+00:00 av-gw-lune-transit2-insane-hagw racoon: INFO: IPsec-SA expired: ESP/Tunnel 10.103.0.196[500]->10.102.1.4[500] spi=204118401(0xc2a9981)
2021-01-07T22:24:41.675829+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: 2021-01-07T22:24:41.675441Z WARNING ExtHandler ExtHandler An error occurred while retrieving the goal state: Traceback (most recent call last):
2021-01-07T22:24:41.675992+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 554, in call_wireserver
2021-01-07T22:24:41.676043+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     resp = http_req(*args, **kwargs)
2021-01-07T22:24:41.676078+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 476, in http_get
2021-01-07T22:24:41.676130+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     retry_delay=retry_delay)
2021-01-07T22:24:41.676169+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 461, in http_request
2021-01-07T22:24:41.676223+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     raise HttpError("{0} -- {1} attempts made".format(msg, attempt))
2021-01-07T22:24:41.676275+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: azurelinuxagent.common.exception.HttpError: [HttpError] [HTTP Failed] GET http://168.63.129.16/machine/?comp=goalstate -- IOError timed out -- 6 attempts made
2021-01-07T22:24:41.676311+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: During handling of the above exception, another exception occurred:
2021-01-07T22:24:41.676343+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: Traceback (most recent call last):
2021-01-07T22:24:41.676368+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/protocol/goal_state.py", line 65, in __init__
2021-01-07T22:24:41.676397+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     self.xml_text = wire_client.fetch_config(uri, wire_client.get_header())
2021-01-07T22:24:41.676425+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 582, in fetch_config
2021-01-07T22:24:41.676458+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     headers=headers)
2021-01-07T22:24:41.676490+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 568, in call_wireserver
2021-01-07T22:24:41.676525+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     ustr(e)))
2021-01-07T22:24:41.676562+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: azurelinuxagent.common.exception.ProtocolError: [ProtocolError] [Wireserver Exception] [HttpError] [HTTP Failed] GET http://168.63.129.16/machine/?comp=goalstate -- IOError timed out -- 6 attempts made
2021-01-07T22:24:41.676591+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: During handling of the above exception, another exception occurred:
2021-01-07T22:24:41.676624+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: Traceback (most recent call last):
2021-01-07T22:24:41.676647+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 719, in update_goal_state
2021-01-07T22:24:41.676683+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     new_goal_state = GoalState.fetch_full_goal_state_if_incarnation_different_than(self, self._goal_state.incarnation)
2021-01-07T22:24:41.676711+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/protocol/goal_state.py", line 156, in fetch_full_goal_state_if_incarnation_different_than
2021-01-07T22:24:41.676765+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     goal_state = GoalState(wire_client, base_incarnation=incarnation)
2021-01-07T22:24:41.676807+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/protocol/goal_state.py", line 98, in __init__
2021-01-07T22:24:41.676844+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     raise ProtocolError(msg="Error fetching goal state", inner=exception)
2021-01-07T22:24:41.676885+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: azurelinuxagent.common.exception.ProtocolError: [ProtocolError] Error fetching goal state
2021-01-07T22:24:41.676914+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: Inner error: [ProtocolError] [Wireserver Exception] [HttpError] [HTTP Failed] GET http://168.63.129.16/machine/?comp=goalstate -- IOError timed out -- 6 attempts made

……..
2021-01-08T01:00:43.075736+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: 2021-01-08T01:00:43.075343Z ERROR SendTelemetryHandler ExtHandler Event: name=WALinuxAgent, op=ReportEventErrors, message=DroppedEventsCount: 1
2021-01-08T01:00:43.075969+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: Reasons (first 5 errors): [ProtocolError] [Wireserver Exception] [HttpError] [HTTP Failed] POST http://168.63.129.16/machine?comp=telemetrydata -- IOError timed out -- 6 attempts made: Traceback (most recent call last):
2021-01-08T01:00:43.076021+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 554, in call_wireserver
2021-01-08T01:00:43.076062+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     resp = http_req(*args, **kwargs)
2021-01-08T01:00:43.076106+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 507, in http_post
2021-01-08T01:00:43.076140+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     retry_delay=retry_delay)
2021-01-08T01:00:43.076172+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 461, in http_request
2021-01-08T01:00:43.076207+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     raise HttpError("{0} -- {1} attempts made".format(msg, attempt))
2021-01-08T01:00:43.076241+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: azurelinuxagent.common.exception.HttpError: [HttpError] [HTTP Failed] POST http://168.63.129.16/machine?comp=telemetrydata -- IOError timed out -- 6 attempts made
2021-01-08T01:00:43.076277+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: During handling of the above exception, another exception occurred:
2021-01-08T01:00:43.076310+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: Traceback (most recent call last):
2021-01-08T01:00:43.076345+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 1087, in _send_event
2021-01-08T01:00:43.076381+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     self.send_event(provider_id, buf[provider_id])
2021-01-08T01:00:43.076415+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 1071, in send_event
2021-01-08T01:00:43.076446+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     resp = self.call_wireserver(restutil.http_post, uri, data, header)
2021-01-08T01:00:43.076474+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:   File "bin/WALinuxAgent-2.2.53-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 568, in call_wireserver
2021-01-08T01:00:43.076508+00:00 av-gw-lune-transit2-insane-hagw python3[1605]:     ustr(e)))
2021-01-08T01:00:43.076541+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: azurelinuxagent.common.exception.ProtocolError: [ProtocolError] [Wireserver Exception] [HttpError] [HTTP Failed] POST http://168.63.129.16/machine?comp=telemetrydata -- IOError timed out -- 6 attempts made
2021-01-08T01:00:43.076573+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: , duration=0
2021-01-08T01:01:22.127052+00:00 av-gw-lune-transit2-insane-hagw perfmon.py: AviatrixGwNetStats: timestamp=2021-01-08T01:01:21.973072 name=lune-transit2-insane-hagw alias=lune-transit2-insane-hagw public_ip=137.116.67.253 private_ip=10.102.1.4 interface=eth0 total_rx_rate=18.32Kb total_tx_rate=8.98Kb total_rx_tx_rate=27.3Kb total_rx_cum=35.11MB total_tx_cum=12.6MB total_rx_tx_cum=47.71MB conntrack_count=70
2021-01-08T01:01:22.127283+00:00 av-gw-lune-transit2-insane-hagw perfmon.py: AviatrixGwSysStats: timestamp=2021-01-08T01:01:21.973072 name=lune-transit2-insane-hagw alias=lune-transit2-insane-hagw cpu_idle=100 memory_free=12876152 memory_available=13035304 memory_total=14109948 disk_total=30308240 disk_free=26323732
2021-01-08T01:01:39.010173+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: 2021-01-08T01:01:39.009770Z ERROR MonitorHandler ExtHandler An error occurred in the monitor thread main loop; will skip the current iteration.
2021-01-08T01:01:39.010312+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: [ProtocolError] Error fetching goal state
2021-01-08T01:01:39.010356+00:00 av-gw-lune-transit2-insane-hagw python3[1605]: Inner error: [ProtocolError] [Wireserver Exception] [HttpError] [HTTP Failed] GET http://168.63.129.16/machine/?comp=goalstate -- IOError timed out -- 6 attempts made
2021-01-08T01:02:18.270827+00:00 av-gw-lune-transit2-insane-hagw kernel: [ 9596.346944] mlx4_en: eth3: Close port called
2021-01-08T01:02:18.296867+00:00 av-gw-lune-transit2-insane-hagw systemd-networkd[892]: eth3: Link DOWN
2021-01-08T01:02:18.297071+00:00 av-gw-lune-transit2-insane-hagw systemd-networkd[892]: eth3: Lost carrier
2021-01-08T01:02:18.298825+00:00 av-gw-lune-transit2-insane-hagw kernel: [ 9596.374972] hv_netvsc 00224802-beea-0022-4802-beea00224802 eth0: Data path switched from VF: eth3
2021-01-08T01:02:18.309128+00:00 av-gw-lune-transit2-insane-hagw kernel: [ 9596.387332] hv_netvsc 00224802-beea-0022-4802-beea00224802 eth0: VF unregistering: eth3
2021-01-08T01:02:18.313221+00:00 av-gw-lune-transit2-insane-hagw systemd[1]: Starting resolvconf-pull-resolved.service...
2021-01-08T01:02:18.340115+00:00 av-gw-lune-transit2-insane-hagw systemd[1]: Started resolvconf-pull-resolved.service.
2021-01-08T01:02:18.342860+00:00 av-gw-lune-transit2-insane-hagw kernel: [ 9596.420430] hv_netvsc 00224802-beea-0022-4802-beea00224802 eth0: VF slot 1 removed
2021-01-08T01:02:19.078827+00:00 av-gw-lune-transit2-insane-hagw kernel: [ 9597.155923] mlx4_en: rename6: Close port called
2021-01-08T01:02:19.103684+00:00 av-gw-lune-transit2-insane-hagw systemd-networkd[892]: rename6: Link DOWN
2021-01-08T01:02:19.103802+00:00 av-gw-lune-transit2-insane-hagw systemd-networkd[892]: rename6: Lost carrier
2021-01-08T01:02:19.106811+00:00 av-gw-lune-transit2-insane-hagw kernel: [ 9597.182333] hv_netvsc 00224804-122d-0022-4804-122d00224804 eth1: Data path switched from VF: rename6
2021-01-08T01:02:19.106824+00:00 av-gw-lune-transit2-insane-hagw kernel: [ 9597.185684] hv_netvsc 00224804-122d-0022-4804-122d00224804 eth1: VF unregistering: rename6
2021-01-08T01:02:19.107247+00:00 av-gw-lune-transit2-insane-hagw systemd[1]: Starting resolvconf-pull-resolved.service...
2021-01-08T01:02:19.124815+00:00 av-gw-lune-transit2-insane-hagw systemd[1]: Started resolvconf-pull-resolved.service.
2021-01-08T01:02:19.126054+00:00 av-gw-lune-transit2-insane-hagw systemd[1]: Stopping ifup for eth1...
2021-01-08T01:02:19.134993+00:00 av-gw-lune-transit2-insane-hagw kernel: [ 9597.213005] hv_netvsc 00224804-122d-0022-4804-122d00224804 eth1: VF slot 2 removed

**Comment by kevinclark19a** [comment]
@lyan-git, Hi, I'm working on this issue, and was wondering if you could give me some more information. Firstly, why do you believe that it was the agent that brought the NIC down? I see some driver logs in proximity to the agent exception, but was wondering if you had more information.
Secondly, do you have full logs showing this issue? The part of the code emitting the error logs might not be the part of the code causing the NIC to go down, so it would be useful to have more info. Thanks in advance.

**Comment by lyan-git** [comment]
Hi Kevin,

We debug with Azure further and found that it was not the agent bring down the NIC, it was Azure had problem with the NIC. You can close the ticket for the agent.

Thanks.
Li

**Comment by kevinclark19a** [comment]
thanks, doing so now.
