### ISSUE TITLE
[BUG] Ubuntu 20.04 - waagent does not install extensions - hitting 'latin-1' codec error

### ISSUE THREAD

**Issue by maburlik** [Azure/WALinuxAgent#2300]
**Describe the bug: A clear and concise description of what the bug is.**

For the Ubuntu 20.04 (focal) image:
```
    "vmImageOffer": {
      "value": "0001-com-ubuntu-server-focal"
    },
    "vmImageSku": {
      "value": "20_04-lts"
    },
    "vmImagePublisher": {
      "value": "Canonical"
    },
    "vmImageVersion": {
      "value": "latest"
    }
```
WALinuxAgent is hitting unexpected exceptions in **call_wireserver**.

Errors:
```
2021-07-08T22:36:21.057145Z ERROR SendTelemetryHandler ExtHandler Event: name=WALinuxAgent, op=ReportEventErrors, messag
e=DroppedEventsCount: 1
Reasons (first 5 errors): [ProtocolError] [Wireserver Exception] 'latin-1' codec can't encode character '\u2018' in posi
tion 546: Body ('\u2018') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.: Trace
back (most recent call last):
  File "bin/WALinuxAgent-2.3.1.1-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 598, in call_wireserver
    resp = http_req(*args, **kwargs)
  File "bin/WALinuxAgent-2.3.1.1-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 533, in http_post
    return http_request("POST",
  File "bin/WALinuxAgent-2.3.1.1-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 430, in http_request
    resp = _http_request(method,
  File "bin/WALinuxAgent-2.3.1.1-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 347, in _http_request
    conn.request(method=method, url=url, body=data, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1300, in _send_request
    body = _encode(body, 'body')
  File "/usr/lib/python3.8/http/client.py", line 164, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 546: Body ('\u2018') is not valid Latin-
1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/WALinuxAgent-2.3.1.1-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 1182, in _send_event
    self.send_event(provider_id, buf[provider_id])
  File "bin/WALinuxAgent-2.3.1.1-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 1166, in send_event
   resp = self.call_wireserver(restutil.http_post, uri, data, header)
  File "bin/WALinuxAgent-2.3.1.1-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 611, in call_wireserver
    raise ProtocolError("[Wireserver Exception] {0}".format(
azurelinuxagent.common.exception.ProtocolError: [ProtocolError] [Wireserver Exception] 'latin-1' codec can't encode char
acter '\u2018' in position 546: Body ('\u2018') is not valid Latin-1. Use body.encode('utf-8') if you want to send it en
coded in UTF-8.
, duration=0
2021-07-08T22:37:21.116130Z ERROR SendTelemetryHandler ExtHandler Event: name=WALinuxAgent, op=ReportEventErrors, messag
e=DroppedEventsCount: 1
Reasons (first 5 errors): [ProtocolError] [Wireserver Exception] 'latin-1' codec can't encode character '\u2018' in posi
tion 546: Body ('\u2018') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.: Trace
back (most recent call last):
  File "bin/WALinuxAgent-2.3.1.1-py2.7.egg/azurelinuxagent/common/protocol/wire.py", line 598, in call_wireserver
    resp = http_req(*args, **kwargs)
  File "bin/WALinuxAgent-2.3.1.1-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 533, in http_post
    return http_request("POST",
  File "bin/WALinuxAgent-2.3.1.1-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 430, in http_request
    resp = _http_request(method,
  File "bin/WALinuxAgent-2.3.1.1-py2.7.egg/azurelinuxagent/common/utils/restutil.py", line 347, in _http_request
    conn.request(method=method, url=url, body=data, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1300, in _send_request
    body = _encode(body, 'body')
  File "/usr/lib/python3.8/http/client.py", line 164, in _encode
    raise UnicodeEncodeError(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2018' in position 546: Body ('\u2018') is not valid Latin-
1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

ARM template that was used for the deployment:
https://gist.github.com/maburlik/55120692c0c544d9f4bde65a8a0ee543

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: Ubuntu 20.04: Canonical - 0001-com-ubuntu-server-focal - 20_04-lts - latest
 - WALinuxAgent version [e.g. 2.2.40, you can copy the output of `waagent --version`, more info [here](https://github.com/Azure/WALinuxAgent/wiki/FAQ#what-does-goal-state-agent-mean-in-waagent---version-output) ]
 ```
root@SFRole0000000:/var/lib/waagent/WALinuxAgent-2.3.1.1# waagent --version
/usr/sbin/waagent:27: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
WALinuxAgent-2.2.46 running on ubuntu 20.04
Python: 3.8.10
Goal state agent: 2.3.1.1
```

**Additional context**
We are currently prototyping Service Fabric on Ubuntu 20.04 and found this flooding the logs of waagent.log.

**Log file attached**
[waagent.log](https://github.com/Azure/WALinuxAgent/files/6793996/waagent.log)

**Comment by narrieta** [comment]
@maburlik we will have a few changes to alleviate this issue in 1 or 2 releases. Most of the times this is caused by extensions producing telemetry data that includes characters outside the latin-1 range. The agent should delete those data once it fails to process them so if the error keeps popping up likely an extension is continuously producing more data like this. You could trying getting a verbose log to help identify the producer of that data.

Duplicate of #1523

**Comment by pholding** [comment]
@maburlik I'm also seeing this issue on a VM running Ubuntu 20.04. Could you explain how to get a verbose log from waagent to see what is producing the data with invalid characters?

**Comment by pholding** [comment]
@narrieta I'm also seeing this issue on a VM running Ubuntu 20.04. Could you explain how to get a verbose log from waagent to see what is producing the data with invalid characters?

**Comment by narrieta** [comment]
@pholding - to enable verbose logging, set Logs.Verbose to y in /etc/waagent.conf and restart the agent. Once you have the issue captured in the log (/var/log/waagent.log) revert the Verbose flag to n, since the verbose log can grow very fast.

**Comment by pholding** [comment]
@narrieta I've enabled verbose logging and have captured a few instances of the error but I can't see which extension is producing the bad data. The entry immediately before the error begins with `SendTelemetryHandler ExtHandler HTTP connection [POST] [/machine?comp=telemetrydata]` followed by a XML payload.

I don't know whether there is there is any sensitive information in the file encoded as base64 strings. I can see several places where the hostname and Azure resource group name is referenced.

Is there a way I can share the contents of the file with Microsoft (rather than anyone reading this issue) or alternatively could you let me know which bits of the log are relevant?

**Comment by narrieta** [comment]
The XML payload consists of a list of Event elements. Each event will have a name similar to

`<Param Name="Name" Value="Microsoft.Azure.GuestConfiguration.DSCAgent" T="mt:wstr"
`
and a message similar to

`<Param Name="Message" Value="&lt;GCLOG&gt;[2021-07-15 05:49:29.535] [PID 30318] [TID 30320] [DSCEngine] [WARNING] [00000000-0000-0000-0000-000000000000] [/home/dscbuilder/DesiredStateConfiguration/src/dsc/engine/EngineHelper/EngineHelper.c:2435] Job e5524e9a-5b52-4175-843c-44d7494388bb : WarningMessage The GET operation will be carried against a pending configuration since the latest configuration has not converged yet.&lt;/GCLOG&gt;&#10;" T="mt:wstr" />
`

Maybe you can spot  the character(s) in the Message that are causing the error? The Name is the extension's

**Comment by pholding** [comment]
@narrieta I can't see any characters in the message that might be causing the error. The unicode character referenced in the error message is \u2192 and there doesn't appear to be any occurrences of a rightwards arrow in the log.

There is an event created by the WALinuxAgent extension which contains the error message but I'm assuming this is simply reporting to Azure the error occurred rather than the root cause.

I've created a [gist](https://gist.github.com/pholding/1a0d55c86e55d225226071456ac81dab) with the XML payload for one of the occurrences of the error with the VM's hostname and resource group redacted. Would you be able to take a look and see if you can spot anything? Link to the gist is https://gist.github.com/pholding/1a0d55c86e55d225226071456ac81dab

I can share the other XML payloads as well if that helps.

**Comment by narrieta** [comment]
@pholding Thanks for the gist. I can see that in this case it is an Event produced by the agent itself that is causing those errors. At some point an extension produced an invalid Event and the agent is trying to report it and it is including the incorrect character in its Message, which causes another error.

How is this impacting your VM? We are currently deploying version 2.4.0.1, which fixes the error reporting on the agent side (we would still need to identify the extension that produced the original event).

Our release is currently only in a few regions in Azure, and will take approximately another 3-4 weeks to reach all regions. In the meanwhile, you could try to mitigate by deleting all files under /var/lib/waagent/events, but if an extension produces another invalid event, the issue would repeat.

**Comment by pholding** [comment]
@narrieta The only real impact on the VM is that /var/log/syslog is updated every minute with the error from waagent. Following your suggestion to delete the files in /var/lib/waagent/events the error has stopped (at least for the time being). Thanks for the workaround. I'll report back if it happens again and hopefully we can figured out which extension is causing the error in the first place.

The VM is in the Azure UK South region - Is this one of the regions that will receive version 2.4.0.1 initially?

If it helps, I think this error has occurred since the VM was created approximately 8 weeks ago. Perhaps there is something that happens during the VM creation process or the installation of one the extensions that produces an event with the incorrect characters. The extensions installed on the VM are AADSSHLoginForLinux, LinuxAgent.AzureSecurityCenter and OmsAgentForLinux.

**Comment by narrieta** [comment]
@pholding I'm sorry, UK South is one of the regions that will get 2.4.0.1 last. We use a mix of regions across different geographies and deploy the agent in "slices". UK South happens to be in the last slice... this is not something we can change easily.

I am not aware of any issue in those 3 extensions. If you have the old logs from the waagent from vm creation you could try to see if you can spot the first time the error appears in the logs. Or you could wait to see if this happens again and we can try to identify the extension emitting the event from there.

**Comment by pholding** [comment]
@narrieta I've still got the waagent log from when the VM was created, so I've uploaded a redacted version to remove hostnames and IP addresses to gist. The link is https://gist.github.com/pholding/fa394fdae96760f64a1d3678fe2863b4

There doesn't appear to be any errors logged in waagent.log from the extensions prior to the incorrect character error. Is there anything else you can spot from the log?

I've got another VM which is also experiencing the same error with invalid characters, so I'll have a look at the logs on that VM to see if there is anything else of note.

**Comment by narrieta** [comment]
@pholding Thanks for the log. Unfortunately, it did not provide additional information. This one is hard to debug with the current agent since the agent deletes the events that it fails to process so the only way to catch those event would be with a verbose log from the very beginning. That would require creating a custom image with verbose log enabled or installing the extensions after enabling verbose log manually.
