### ISSUE TITLE
[BUG] waagent fails after hostname change

### ISSUE THREAD

**Issue by spauka** [Azure/WALinuxAgent#2455]
After changing the hostname on a VM using the hostname command, waagent encounters a repeated error every 3 seconds leading to unbounded log file growth.

**Steps to reproduce**
1. Change hostname using the `hostname` command, like `hostname host.example.com`
2. `waagent` logs a consistent failure to the systemd journal every 3 seconds. This is visible by running `journalctl -f`

**Temporary Fix**
Restarting waagent resolves the issue, however the underlying problem should be addressed since I generated 1.1 GBs of log files in 3 days before I noticed.

**Version**
 - Debian 11.2 (Bullseye)
 - WALinuxAgent-2.2.47 running on debian 11
 - Python: 3.9.2
 - Goal state agent: 2.2.47

**Additional context**
Example output for 6 seconds of journalctl below. This message is repeated every 3 seconds. Note: hostname is changed for privacy.
```
Jan 04 00:31:50 newhostname.example.com waagent[916]: 2022-01-03T13:31:50.396932Z INFO EnvHandler ExtHandler EnvMonitor: Detected hostname change: oldhostname -> newhostname.example.com
Jan 04 00:31:50 newhostname.example.com waagent[916]: 2022-01-03T13:31:50.412551Z INFO EnvHandler ExtHandler Examine /proc/net/route for primary interface
Jan 04 00:31:50 newhostname.example.com waagent[916]: 2022-01-03T13:31:50.422976Z INFO EnvHandler ExtHandler Primary interface is [eth0]
Jan 04 00:31:50 newhostname.example.com waagent[916]: Exception in thread EnvHandler:
Jan 04 00:31:50 newhostname.example.com waagent[916]: Traceback (most recent call last):
Jan 04 00:31:50 newhostname.example.com waagent[916]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Jan 04 00:31:50 newhostname.example.com waagent[916]:     self.run()
Jan 04 00:31:50 newhostname.example.com waagent[916]:   File "/usr/lib/python3.9/threading.py", line 892, in run
Jan 04 00:31:50 newhostname.example.com waagent[916]:     self._target(*self._args, **self._kwargs)
Jan 04 00:31:50 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/env.py", line 136, in monitor
Jan 04 00:31:50 newhostname.example.com waagent[916]:     self.handle_hostname_update()
Jan 04 00:31:50 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/env.py", line 151, in handle_hostname_update
Jan 04 00:31:50 newhostname.example.com waagent[916]:     self.osutil.publish_hostname(curr_hostname)
Jan 04 00:31:50 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/osutil/default.py", line 1158, in publish_hostname
Jan 04 00:31:50 newhostname.example.com waagent[916]:     ifname = self.get_if_name()
Jan 04 00:31:50 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/osutil/default.py", line 1054, in get_if_name
Jan 04 00:31:50 newhostname.example.com waagent[916]:     if_name = self.get_first_if()[0]
Jan 04 00:31:50 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/osutil/default.py", line 821, in get_first_if
Jan 04 00:31:50 newhostname.example.com waagent[916]:     ifaces = self._get_all_interfaces()
Jan 04 00:31:50 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/osutil/default.py", line 804, in _get_all_interfaces
Jan 04 00:31:50 newhostname.example.com waagent[916]:     ifconf_buff = buff.tostring()
Jan 04 00:31:50 newhostname.example.com waagent[916]: AttributeError: 'array.array' object has no attribute 'tostring'
Jan 04 00:31:53 newhostname.example.com waagent[916]: 2022-01-03T13:31:53.441622Z WARNING ExtHandler ExtHandler Environment thread died, restarting
Jan 04 00:31:53 newhostname.example.com waagent[916]: 2022-01-03T13:31:53.454309Z INFO EnvHandler ExtHandler EnvMonitor: Detected hostname change: oldhostname -> newhostname.example.com
Jan 04 00:31:53 newhostname.example.com waagent[916]: 2022-01-03T13:31:53.470904Z INFO EnvHandler ExtHandler Examine /proc/net/route for primary interface
Jan 04 00:31:53 newhostname.example.com waagent[916]: 2022-01-03T13:31:53.478043Z INFO EnvHandler ExtHandler Primary interface is [eth0]
Jan 04 00:31:53 newhostname.example.com waagent[916]: Exception in thread EnvHandler:
Jan 04 00:31:53 newhostname.example.com waagent[916]: Traceback (most recent call last):
Jan 04 00:31:53 newhostname.example.com waagent[916]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Jan 04 00:31:53 newhostname.example.com waagent[916]:     self.run()
Jan 04 00:31:53 newhostname.example.com waagent[916]:   File "/usr/lib/python3.9/threading.py", line 892, in run
Jan 04 00:31:53 newhostname.example.com waagent[916]:     self._target(*self._args, **self._kwargs)
Jan 04 00:31:53 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/env.py", line 136, in monitor
Jan 04 00:31:53 newhostname.example.com waagent[916]:     self.handle_hostname_update()
Jan 04 00:31:53 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/env.py", line 151, in handle_hostname_update
Jan 04 00:31:53 newhostname.example.com waagent[916]:     self.osutil.publish_hostname(curr_hostname)
Jan 04 00:31:53 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/osutil/default.py", line 1158, in publish_hostname
Jan 04 00:31:53 newhostname.example.com waagent[916]:     ifname = self.get_if_name()
Jan 04 00:31:53 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/osutil/default.py", line 1054, in get_if_name
Jan 04 00:31:53 newhostname.example.com waagent[916]:     if_name = self.get_first_if()[0]
Jan 04 00:31:53 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/osutil/default.py", line 821, in get_first_if
Jan 04 00:31:53 newhostname.example.com waagent[916]:     ifaces = self._get_all_interfaces()
Jan 04 00:31:53 newhostname.example.com waagent[916]:   File "/usr/lib/python3/dist-packages/azurelinuxagent/common/osutil/default.py", line 804, in _get_all_interfaces
Jan 04 00:31:53 newhostname.example.com waagent[916]:     ifconf_buff = buff.tostring()
Jan 04 00:31:53 newhostname.example.com waagent[916]: AttributeError: 'array.array' object has no attribute 'tostring'
```

**Log file attached**
waagent.log shows the same error, without the stack trace:
```
2022-01-03T13:50:44.673809Z WARNING ExtHandler ExtHandler Environment thread died, restarting
2022-01-03T13:50:44.682371Z INFO EnvHandler ExtHandler EnvMonitor: Detected hostname change: oldhostname -> newhostname.example.com
2022-01-03T13:50:44.701678Z INFO EnvHandler ExtHandler Examine /proc/net/route for primary interface
2022-01-03T13:50:44.709122Z INFO EnvHandler ExtHandler Primary interface is [eth0]
2022-01-03T13:50:47.736480Z WARNING ExtHandler ExtHandler Environment thread died, restarting
2022-01-03T13:50:47.746434Z INFO EnvHandler ExtHandler EnvMonitor: Detected hostname change: oldhostname -> newhostname.example.com
2022-01-03T13:50:47.763607Z INFO EnvHandler ExtHandler Examine /proc/net/route for primary interface
2022-01-03T13:50:47.770413Z INFO EnvHandler ExtHandler Primary interface is [eth0]
```

**Comment by kevinclark19a** [comment]
Looks like this is a fixed bug in later goal state agent versions. Could you try turning on agent auto-update on this VM and let me know if that doesn't fix the issue?

**Comment by spauka** [comment]
@kevinclark19a Thanks, I can confirm that this bug no longer occurs after update.
