### ISSUE TITLE
[BUG] System crash may cause waagent exception

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#2460]
**Describe the bug: A clear and concise description of what the bug is.**
After system crash and reboot, sometimes there are exceptions in waagent.log:
```
2022-01-06T14:07:06.202463Z ERROR TelemetryEventsCollector ExtHandler Event: name=WALinuxAgent, op=CollectEventErrors, message=DroppedEventsCount: 6
Reasons (first 5 errors): [EventError] Error parsing event: no element found: line 1, column 0: Traceback (most recent call last):
  File "bin/WALinuxAgent-2.6.0.2-py2.7.egg/azurelinuxagent/common/event.py", line 206, in parse_event
    return parse_json_event(data_str)
  File "bin/WALinuxAgent-2.6.0.2-py2.7.egg/azurelinuxagent/common/event.py", line 196, in parse_json_event
    data = json.loads(data_str)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/WALinuxAgent-2.6.0.2-py2.7.egg/azurelinuxagent/common/event.py", line 229, in parse_xml_event
    xml_doc = parse_doc(data_str)
  File "bin/WALinuxAgent-2.6.0.2-py2.7.egg/azurelinuxagent/common/utils/textutil.py", line 41, in parse_doc
    return minidom.parseString(xml_text)
  File "/usr/lib64/python3.6/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python3.6/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python3.6/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/WALinuxAgent-2.6.0.2-py2.7.egg/azurelinuxagent/common/event.py", line 208, in parse_event
    return parse_xml_event(data_str)
  File "bin/WALinuxAgent-2.6.0.2-py2.7.egg/azurelinuxagent/common/event.py", line 239, in parse_xml_event
    raise ValueError(ustr(e))
ValueError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/WALinuxAgent-2.6.0.2-py2.7.egg/azurelinuxagent/ga/collect_telemetry_events.py", line 430, in process_events
    event = parse_event(event_data)
  File "bin/WALinuxAgent-2.6.0.2-py2.7.egg/azurelinuxagent/common/event.py", line 210, in parse_event
    raise EventError("Error parsing event: {0}".format(ustr(e)))
azurelinuxagent.common.exception.EventError: [EventError] Error parsing event: no element found: line 1, column 0
, duration=0
```

**Steps:**
1. Create a RHEL-8 VM on Azure. Enable kdump.
2. Trigger crash:
`echo c > /proc/sysrq-trigger`
3. Wait for the VM reboot, check /var/log/waagent.log
Usually trigger crash 2-3 times can see these exceptions.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: RHEL-8.6
 - WALinuxAgent version:
 WALinuxAgent-2.3.0.2 running on redhat 8.6
Python: 3.6.8
Goal state agent: 2.6.0.2
* If disable auto update, it also happens in WALinuxAgent-2.3.0.2 guest agent

**Comment by nagworld9** [comment]
@yuxisun1217 Thanks for reporting. This is by design of not waiting for threads to join when system crash and thus reporting if any exceptions raise in the thread. Looks like events stopped flushing and have an empty file while processing it in telemetry thread. Besides, I'm unable to repro this, could you share `waagent.log` to confirm few other details. Thanks!
