### ISSUE TITLE
[BUG] WALA provisions VM failed because of no "ifdown/ifup" commands in RHEL-9.0/8.6

### ISSUE THREAD

**Issue by yuxisun1217** [Azure/WALinuxAgent#2582]
**Describe the bug: A clear and concise description of what the bug is.**
* If use WALA as provisioning agent(without cloud-init), it provisions VM failed because of no "ifdown/ifup" commands in RHEL-9.0/8.6.

* Another impact is if use cloud-init as provision agent and waagent.service is running, when change hostname, waagent.service prints some error logs in waagent.log, but the hostname can be published successfully:
2022-05-05T04:17:21.540989Z ERROR EnvHandler ExtHandler Command: [ifdown eth0 && ifup eth0], return code: [127], result: [/bin/sh: line 1: ifdown: command not found
]
2022-05-05T04:17:21.544397Z WARNING EnvHandler ExtHandler failed to restart eth0: return code 127
2022-05-05T04:17:21.544524Z INFO EnvHandler ExtHandler retrying in 5 seconds

**Steps:**
1. Prepare a RHEL-9.0 image on Azure with WALA as provision agent and NO cloud-init installed.
2. Create a VM on Azure with this image.

**Distro and WALinuxAgent details (please complete the following information):**
 - Distro and Version: RHEL-9.0
WALinuxAgent-2.3.0.2 running on rhel 9.0
Python: 3.9.10
Goal state agent: 2.3.0.2

**Additional context**
```
2022-05-05T03:47:47.051371Z INFO Daemon Daemon Primary interface is [eth0]
2022-05-05T03:47:47.249204Z ERROR Daemon Daemon Event: name=WALinuxAgent, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/daemon/main.py", line 83, in run
    self.daemon(child_args)
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/daemon/main.py", line 145, in daemon
    self.provision_handler.run()
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/pa/provision/default.py", line 85, in run
    self.provision(ovf_env)
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/pa/provision/default.py", line 213, in provision
    self.osutil.publish_hostname(ovfenv.hostname)
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/common/osutil/redhat.py", line 125, in publish_hostname
    super(RedhatOSUtil, self).publish_hostname(hostname)
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/common/osutil/default.py", line 1190, in publish_hostname
    self.restart_if(ifname)
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/common/osutil/default.py", line 1167, in restart_if
    shellutil.run_command(["ifdown", ifname])
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/common/utils/shellutil.py", line 255, in run_command
    return __run_command(command_action=command_action, command=command, log_error=log_error, encode_output=encode_output)
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/common/utils/shellutil.py", line 182, in __run_command
    return_code, stdout, stderr = command_action()
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/common/utils/shellutil.py", line 245, in command_action
    process = _popen(command, stdin=popen_stdin, stdout=stdout, stderr=stderr, shell=False)
  File "/usr/lib/python3.9/site-packages/azurelinuxagent/common/utils/shellutil.py", line 352, in _popen
    process = subprocess.Popen(*args, **kwargs)
  File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ifdown'
, duration=0
2022-05-05T03:47:47.460449Z WARNING Daemon Daemon Daemon ended with exception -- Sleep 15 seconds and restart daemon
```

**Comment by nagworld9** [comment]
@yuxisun1217 thanks for reporting this. We fixed it now. The fix would go in v2.9
