### ISSUE TITLE
[BUG] Journal as 'Python3' and not as WALinuxAgent

### ISSUE THREAD

**Issue by MaxMelcher** [Azure/WALinuxAgent#2791]
1. Section of the log where the error occurs.

The log identifier is not set to WALinuxAgent which can make troubleshooting issues more difficult:

Mar 22 10:02:23 sltestrhel9-2023-0217 **python3**[948]: 2023-03-22T09:02:23.944179Z ERROR Daemon Daemon Event: name=WALinuxAgent, op=UnhandledError, message=Traceback (most recent call last):
Mar 22 10:02:23 sltestrhel9-2023-0217  **python3**[948]:   File "/usr/lib/python3.9/site-packages/azurelinuxagent/daemon/main.py", line 83, in run
Mar 22 10:02:23 sltestrhel9-2023-0217  **python3**[948]:     self.daemon(child_args)
Mar 22 10:02:23 sltestrhel9-2023-0217  **python3**[948]:   File "/usr/lib/python3.9/site-packages/azurelinuxagent/daemon/main.py", line 145, in daemon

**Distro and WALinuxAgent details:**
 - Distro and Version: RHEL9
 - WALinuxAgent version: WALinuxAgent-2.3.0.2-3.el9.noarch

**Additional context**
log forwarding based on the identifier is easier and more reliable, also will help identifier issues faster.

Can this be improved?

**Comment by Klaas-** [comment]
I think you can fix this with https://github.com/Azure/WALinuxAgent/pull/2729 but you should maybe not group based on that you could use _SYSTEMD_UNIT or something like that
