### ISSUE TITLE
[BUG] Installation fails on unendorsed distribution

### ISSUE THREAD

**Issue by arackhaen** [Azure/WALinuxAgent#2911]
**Describe the bug: Installation of WALinuxAgent fails on unendorsed distribution.**

Installing WALinuxAgent on Gentoo failed:
"Traceback (most recent call last):
  File "/usr/local/src/WALinuxAgent/azurelinuxagent/common/future.py", line 77, in get_linux_distribution
    supported = platform._supported_dists + (supported_dists,)
AttributeError: module 'platform' has no attribute '_supported_dists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/src/WALinuxAgent/setup.py", line 28, in <module>
    from azurelinuxagent.common.osutil import get_osutil
  File "/usr/local/src/WALinuxAgent/azurelinuxagent/common/osutil/__init__.py", line 18, in <module>
    from azurelinuxagent.common.osutil.factory import get_osutil
  File "/usr/local/src/WALinuxAgent/azurelinuxagent/common/osutil/factory.py", line 22, in <module>
    from azurelinuxagent.common.version import DISTRO_NAME, DISTRO_CODE_NAME, DISTRO_VERSION, DISTRO_FULL_NAME
  File "/usr/local/src/WALinuxAgent/azurelinuxagent/common/version.py", line 234, in <module>
    __distro__ = get_distro()
  File "/usr/local/src/WALinuxAgent/azurelinuxagent/common/version.py", line 114, in get_distro
    osinfo = get_linux_distribution(0, 'alpine')
  File "/usr/local/src/WALinuxAgent/azurelinuxagent/common/future.py", line 95, in get_linux_distribution
    return get_linux_distribution_from_distro(get_full_name)
  File "/usr/local/src/WALinuxAgent/azurelinuxagent/common/future.py", line 106, in get_linux_distribution_from_distro
    distro.linux_distribution(
NameError: name 'distro' is not defined"

Is WALinuxAgent ment to support other distibutions too (thaan just endorsed ones)?

**Comment by maddieford** [comment]
@arackhaen for python >= 3.8 you'll need the distro module. You can see our requirements here: https://github.com/Azure/WALinuxAgent/blob/master/requirements.txt

**Comment by AkechiShiro** [comment]
@maddieford this module needs to be installed as a system-wide package?

**Comment by maddieford** [comment]
Yes, system-wide and that is the correct package
