### ISSUE TITLE
[BUG] Backup not possible from Azure Portal with waagent + Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by pthoelken** [Azure/WALinuxAgent#3132]
**Describe the bug:**

Since the update from Ubuntu 20.04 LTS to 24.04 LTS ( 20.04 LTS -> 22.04 LTS -> 23.04 -> 24.04 LTS, normal procedure) I've got daily the message from the Azure monitoring portal, that the backup was unsucessful. After checking the log files, I've got the error message from below while the agent try to create the snapshot.

**Distro and WALinuxAgent details:**
 - Distro and Version: Ubuntu 24.04 LTS (upgraded from 20.04 LTS, see above)
 - WALinuxAgent version Informations
```
WALinuxAgent-2.9.1.1 running on ubuntu 24.04
Python: 3.12.3
Goal state agent: 2.10.0.8
```

**Log file attached**
```
2024-05-29T05:45:42.987587Z INFO ExtHandler [Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0] Executing command: /var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/handle.sh enable with environment variables: {"AZURE_GUEST_AGENT_UNINSTALL_CMD_EXIT_CODE": "NOT_RUN", "AZURE_GUEST_AGENT_EXTENSION_PATH": "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0", "AZURE_GUEST_AGENT_EXTENSION_VERSION": "1.0.9217.0", "AZURE_GUEST_AGENT_WIRE_PROTOCOL_ADDRESS": "XXX.XXX.XXX.XXX", "ConfigSequenceNumber": "637", "AZURE_GUEST_AGENT_EXTENSION_SUPPORTED_FEATURES": "[{\"Key\": \"ExtensionTelemetryPipeline\", \"Value\": \"1.0\"}]"}
2024-05-29T05:45:44.992799Z ERROR ExtHandler ExtHandler Event: name=Microsoft.Azure.RecoveryServices.VMSnapshotLinux, op=Enable, message=[ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/handle.sh enable
[stdout]


[stderr]
Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/Utils/WAAgentUtil.py", line 57, in <module>
    waagent = imp.load_source('waagent', agentPath)
              ^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'load_source'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/handle.py", line 40, in <module>
    from mounts import Mounts
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/mounts.py", line 25, in <module>
    from Utils.DiskUtil import DiskUtil
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/Utils/DiskUtil.py", line 29, in <module>
    import Utils.HandlerUtil
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/Utils/HandlerUtil.py", line 69, in <module>
    import Utils.WAAgentUtil
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/Utils/WAAgentUtil.py", line 64, in <module>
    waagent = imp.load_source('waagent', agentPath)
              ^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'load_source'
Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/Utils/WAAgentUtil.py", line 57, in <module>
    waagent = imp.load_source('waagent', agentPath)
              ^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'load_source'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/handle.py", line 40, in <module>
    from mounts import Mounts
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/mounts.py", line 25, in <module>
    from Utils.DiskUtil import DiskUtil
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/Utils/DiskUtil.py", line 29, in <module>
    import Utils.HandlerUtil
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/Utils/HandlerUtil.py", line 69, in <module>
    import Utils.WAAgentUtil
  File "/var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/main/Utils/WAAgentUtil.py", line 64, in <module>
    waagent = imp.load_source('waagent', agentPath)
              ^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'load_source'
, duration=0
2024-05-29T05:45:44.994899Z INFO ExtHandler ExtHandler ProcessExtensionsGoalState completed [etag_8166643226849683953 4186 ms]

2024-05-29T05:45:52.997921Z WARNING ExtHandler ExtHandler [PERIODIC] This status is being reported by the Guest Agent since no status file was reported by extension Microsoft.Azure.RecoveryServices.VMSnapshotLinux: [ExtensionStatusError] Status file /var/lib/waagent/Microsoft.Azure.RecoveryServices.VMSnapshotLinux-1.0.9217.0/status/637.status does not exist
2024-05-29T05:45:53.017470Z INFO ExtHandler ExtHandler Extension status: [('Microsoft.Azure.RecoveryServices.VMSnapshotLinux', 'transitioning'), ('Microsoft.CPlat.Core.RunCommandLinux', 'success')]

```

**Comment by narrieta** [comment]
@pthoelken This is an issue on the backup extension, rather than on WALinuxAgent. Could you open this issue on https://github.com/Azure/azure-linux-extensions?

**Comment by pthoelken** [comment]
@narrieta - Thanks for your response. I've paste it here: https://github.com/Azure/azure-linux-extensions/issues/1922
