### ISSUE TITLE
"[Errno 26] Text file busy: " Intermittent Errors with WALinuxAgent Installing LinuxDiagnostics Agent

### ISSUE THREAD

**Issue by tamcclur** [Azure/WALinuxAgent#428]
We have been seeing very intermittent and spaced out occurrences where LinuxDiagnostics `mdsd` binary is busy and cannot be used. The frequency will be about 5-10 days.

This issue subsequently crashes WALinuxAgent in its entirety prompting a manual reboot of the service. Here is the stack trace in waagent.log:

```
2016/09/08 01:06:06 Found Plugin: Microsoft.OSTCExtensions.LinuxDiagnostic version: 2.3.9007
2016/09/08 01:06:06 Downloading plugin manifest: Microsoft.OSTCExtensions.LinuxDiagnostic from https://rdfepirv2bl2prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions_LinuxDiagnostic_useast_manifest.xml
2016/09/08 01:06:06 Plugin server is: rdfepirv2bl2prdstr01.blob.core.windows.net
2016/09/08 01:06:06 Bundle URI = https://rdfepirv2bl2prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions__LinuxDiagnostic__2.3.9007
2016/09/08 01:06:08 Plugin bundlehttps://rdfepirv2bl2prdstr01.blob.core.windows.net/b01058962be54ceca550a390fa5ff064/Microsoft.OSTCExtensions__LinuxDiagnostic__2.3.9007downloaded successfully length = 38562489
2016/09/08 01:06:08 ERROR:Traceback (most recent call last):
2016/09/08 01:06:08 ERROR:  File "/usr/sbin/waagent", line 6123, in main
2016/09/08 01:06:08 ERROR:    WaAgent.Run()
2016/09/08 01:06:08 ERROR:  File "/usr/sbin/waagent", line 5717, in Run
2016/09/08 01:06:08 ERROR:    goalState.ExtensionsConfig = ExtensionsConfig().Parse(goalState.ExtensionsConfigXml)
2016/09/08 01:06:08 ERROR:  File "/usr/sbin/waagent", line 3666, in Parse
2016/09/08 01:06:08 ERROR:    z.extractall(zip_dir)
2016/09/08 01:06:08 ERROR:  File "/usr/lib64/python2.7/zipfile.py", line 1036, in extractall
2016/09/08 01:06:08 ERROR:    self.extract(zipinfo, path, pwd)
2016/09/08 01:06:08 ERROR:  File "/usr/lib64/python2.7/zipfile.py", line 1024, in extract
2016/09/08 01:06:08 ERROR:    return self._extract_member(member, path, pwd)
2016/09/08 01:06:08 ERROR:  File "/usr/lib64/python2.7/zipfile.py", line 1079, in _extract_member
2016/09/08 01:06:08 ERROR:    file(targetpath, "wb") as target:
2016/09/08 01:06:08 ERROR:IOError: [Errno 26] Text file busy: u'/var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007/bin/mdsd'
2016/09/08 01:06:08 ERROR:
2016/09/08 01:06:08 ERROR:Exception: [Errno 26] Text file busy: u'/var/lib/waagent/Microsoft.OSTCExtensions.LinuxDiagnostic-2.3.9007/bin/mdsd'
```

Distro information:

Oracle Linux
Kernel: 3.8.13-55.1.1.el7uek.x86_64
WALinuxAgent Version: WALinuxAgent-2.0.15 (latest in main repo)

**Comment by brendandixon** [comment]
Fixed in v2.1.5+ versions.

**Comment by tamcclur** [comment]
Thanks!

@brendandixon do we have any say as to Oracle updating their repos with the latest version of WALinuxAgent?

**Comment by brendandixon** [comment]
@tamcclur We let them know when new versions exist. They choose their own delivery schedule.
