### ISSUE TITLE
Agent doesn't handle "Connection reset by peer" exception while downloading extension manifest

### ISSUE THREAD

**Issue by jasonzio** [Azure/WALinuxAgent#465]
walinuxagent needs to catch and handle exceptions in Util.HttpGetWithoutHeaders(). Ideally this proper handling would include backoff-and-retry code.

```
2016/10/14 00:05:25 Retrieved GoalState from Windows Azure Fabric.
2016/10/14 00:05:25 ExpectedState: Started
2016/10/14 00:05:25 ContainerId: 9c026a1b-fe4b-4bb5-99d2-xxxxxxxxxxxx
2016/10/14 00:05:25 RoleInstanceId: 725365b8-5def-4a15-a5df-xxxxxxxxxxxx._CrpRunnerBlahBlah
2016/10/14 00:05:25 Posted Role Properties. CertificateThumbprint=63fd69fe97b664b2xxxxxxxxxxxxxxxx
2016/10/14 00:05:28 Found Plugin: Microsoft.OSTCExtensions.CustomScriptForLinux version: 1.5.2.0
2016/10/14 00:05:28 Downloading plugin manifest: Microsoft.OSTCExtensions.CustomScriptForLinux from https://ardfepirv2bn
1azfstr01.blob.core.usgovcloudapi.net/e1b1cc6bf774433e87b91950a3745448/Microsoft.OSTCExtensions_CustomScriptForLinux_usg
oveast_manifest.xml
2016/10/14 00:05:28 Plugin server is: ardfepirv2bn1azfstr01.blob.core.usgovcloudapi.net
2016/10/14 00:05:28 Bundle URI = https://ardfepirv2bn1azfstr01.blob.core.usgovcloudapi.net/e1b1cc6bf774433e87b91950a3745
448/Microsoft.OSTCExtensions__CustomScriptForLinux__1.5.2.0
2016/10/14 00:06:11 ERROR:Traceback (most recent call last):
2016/10/14 00:06:11 ERROR:  File "/usr/sbin/waagent", line 6047, in main
2016/10/14 00:06:11 ERROR:    WaAgent.Run()
2016/10/14 00:06:11 ERROR:  File "/usr/sbin/waagent", line 5636, in Run
2016/10/14 00:06:11 ERROR:    goalState.ExtensionsConfig = ExtensionsConfig().Parse(goalState.ExtensionsConfigXml)
2016/10/14 00:06:11 ERROR:  File "/usr/sbin/waagent", line 3578, in Parse
2016/10/14 00:06:11 ERROR:    bundle=self.Util.HttpGetWithoutHeaders(bundle_uri, chkProxy=True)
2016/10/14 00:06:11 ERROR:  File "/usr/sbin/waagent", line 2805, in HttpGetWithoutHeaders
2016/10/14 00:06:11 ERROR:    return resp.read() if resp is not None else None
2016/10/14 00:06:11 ERROR:  File "/usr/lib/python2.7/httplib.py", line 557, in read
2016/10/14 00:06:11 ERROR:    s = self._safe_read(self.length)
2016/10/14 00:06:11 ERROR:  File "/usr/lib/python2.7/httplib.py", line 664, in _safe_read
2016/10/14 00:06:11 ERROR:    chunk = self.fp.read(min(amt, MAXAMOUNT))
2016/10/14 00:06:11 ERROR:  File "/usr/lib/python2.7/socket.py", line 380, in read
2016/10/14 00:06:11 ERROR:    data = self._sock.recv(left)
2016/10/14 00:06:11 ERROR:  File "/usr/lib/python2.7/ssl.py", line 341, in recv
2016/10/14 00:06:11 ERROR:    return self.read(buflen)
2016/10/14 00:06:11 ERROR:  File "/usr/lib/python2.7/ssl.py", line 260, in read
2016/10/14 00:06:11 ERROR:    return self._sslobj.read(len)
2016/10/14 00:06:11 ERROR:error: [Errno 104] Connection reset by peer
2016/10/14 00:06:11 ERROR:
2016/10/14 00:06:11 ERROR:Exception: [Errno 104] Connection reset by peer
```

**Comment by brendandixon** [comment]
@jasonzio What version of the agent? I believe we handle this in v2.1+.

**Comment by jasonzio** [comment]
2.0.14. If you can confirm 2.1+ handles this, please feel free to close this.

**Comment by jinhyunr** [comment]
the latest version of WALA uses retry logic and handles HttpError. 
Closing the issue.
