### ISSUE TITLE
Password encoding issues causing provisioning failures

### ISSUE THREAD

**Issue by mabicca** [Azure/WALinuxAgent#516]
Hi there,

While deploying a VM with the following password:
Mèé2016%a12345

The waagent spits out the following error, causing issues with provisioning:

```
2016/12/12 21:57:49.500344 ERROR Event: name=WALA, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/daemon/main.py", line 68, in run
    self.daemon()
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/daemon/main.py", line 115, in daemon
    self.provision_handler.run()
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/pa/provision/ubuntu.py", line 44, in run
    super(UbuntuProvisionHandler, self).run()
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/pa/provision/default.py", line 62, in run
    self.provision(ovf_env)
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/pa/provision/default.py", line 109, in provision
    self.config_user_account(ovfenv)
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/pa/provision/default.py", line 128, in config_user_account
    crypt_id=crypt_id, salt_len=salt_len)
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/common/osutil/default.py", line 113, in chpasswd
    passwd_hash = textutil.gen_password_hash(password, crypt_id, salt_len)
  File "/usr/lib/python2.7/dist-packages/azurelinuxagent/common/utils/textutil.py", line 264, in gen_password_hash
    return crypt.crypt(password, salt)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 13: ordinal not in range(128)
```

Version of the waagent is 2.2.0 included with the latest Debian 8 image.

Please, let me know if you guys need any other details.

Thank you,

**Comment by hglkrijger** [comment]
Fix merged
