### ISSUE TITLE
character  £  can't be encoded in password for RHEL 7.2

### ISSUE THREAD

**Issue by axelgMS** [Azure/WALinuxAgent#596]
Do we have the requirements for password complexity for Linux IaaS VMs somewhere? I know we recommend using SSH keys, but some customers might still prefer passwords…
Just had issue deploying a RHEL 7.2 VM from Ibiza portal and got OSProvisioningInternalError after few minutes.

After investigation, that’s because I used character “ £ “ (British pound symbol) in my password – which WALA fails to encrypt. See below my repro:
	Can this be documented?
	Can we add a validation in Ibiza portal – to prevent other customers from using it and get to a point where they'll just see OSProvisioningInternalError which has no sense if we don't look at logs
	Can we try to catch that exception and improve the error returned ?

My serial logs:
2017/02/27 13:57:24.546353 WARNING Server prefered version:2015-04-05
2017/02/27 13:57:29.517648 INFO Starting provisioning
2017/02/27 13:57:29.525260 INFO Handle ovf-env.xml.
2017/02/27 13:57:29.536971 INFO Set host name.
2017/02/27 13:57:29.622911 INFO Publish host name.
2017/02/27 13:57:30.223263 INFO examine /proc/net/route for primary interface
2017/02/27 13:57:30.247981 INFO primary interface is [eth0]
2017/02/27 13:57:30.256110 INFO interface [lo] has flags [73], is loopback [True]
2017/02/27 13:57:30.341347 INFO interface [lo] skipped
2017/02/27 13:57:30.353317 INFO interface [eth0] has flags [4163], is loopback [False]
2017/02/27 13:57:30.406628 INFO interface [eth0] selected
2017/02/27 13:57:30.509502 INFO examine /proc/net/route for primary interface
2017/02/27 13:57:30.533619 INFO primary interface is [eth0]
2017/02/27 13:57:30.541368 INFO interface [lo] has flags [73], is loopback [True]
2017/02/27 13:57:30.594778 INFO interface [lo] skipped
2017/02/27 13:57:30.600887 INFO interface [eth0] has flags [4163], is loopback [False]
2017/02/27 13:57:30.639314 INFO interface [eth0] selected
2017/02/27 13:57:32.389193 INFO Create user account if not exists
2017/02/27 13:57:33.365743 INFO Set user password.
2017/02/27 13:57:33.435093 ERROR Event: name=WALA, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 68, in run
    self.daemon()
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/daemon/main.py", line 115, in daemon
    self.provision_handler.run()
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 62, in run
    self.provision(ovf_env)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 109, in provision
    self.config_user_account(ovfenv)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/pa/provision/default.py", line 128, in config_user_account
    crypt_id=crypt_id, salt_len=salt_len)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/osutil/default.py", line 113, in chpasswd
    passwd_hash = textutil.gen_password_hash(password, crypt_id, salt_len)
  File "/usr/lib/python2.7/site-packages/azurelinuxagent/common/utils/textutil.py", line 264, in gen_password_hash
    return crypt.crypt(password, salt)
  File "/usr/lib64/python2.7/crypt.py", line 55, in crypt
    return _crypt.crypt(word, salt)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 18: ordinal not in range(128)

2017/02/27 13:57:33.726086 INFO Sleep 15 seconds and restart daemon
2017/02/27 13:57:48.775429 INFO Run daemon
2017/02/27 13:57:48.780886 INFO No RDMA handler exists for distro='Red Hat Enterprise Linux Server' version='7.2'
2017/02/27 13:57:48.803913 INFO Activate resource disk
2017/02/27 13:57:48.825434 INFO Resource disk [/dev/sdb1] is already mounted [/mnt/resource]
2017/02/27 13:57:48.845480 INFO Enable swap
2017/02/27 13:57:48.866438 INFO Swap already enabled
2017/02/27 13:57:48.872436 INFO Clean protocol
2017/02/27 13:57:48.880978 INFO Running provisioning handler
2017/02/27 13:57:48.888434 INFO Copying ovf-env.xml
2017/02/27 13:57:49.094970 ERROR run cmd 'mount -o ro -t udf,iso9660 /dev/sr0 /mnt/cdrom/secure' failed
2017/02/27 13:57:49.107845 ERROR Error Code:32
2017/02/27 13:57:49.114998 ERROR Result:mount: no medium found on /dev/sr0

2017/02/27 13:57:49.134547 WARNING Mount dvd failed: retry=0, ret=32
2017/02/27 13:57:54.274208 ERROR run cmd 'mount -o ro -t udf,iso9660 /dev/sr0 /mnt/cdrom/secure' failed
2017/02/27 13:57:54.289595 ERROR Error Code:32
2017/02/27 13:57:54.305079 ERROR Result:mount: no medium found on /dev/sr0

2017/02/27 13:57:54.323265 WARNING Mount dvd failed: retry=1, ret=32
2017/02/27 13:57:59.506068 ERROR run cmd 'mount -o ro -t udf,iso9660 /dev/sr0 /mnt/cdrom/secure' failed
2017/02/27 13:57:59.548629 ERROR Error Code:32
2017/02/27 13:57:59.554878 ERROR Result:mount: no medium found on /dev/sr0

2017/02/27 13:57:59.588169 WARNING Mount dvd failed: retry=2, ret=32
2017/02/27 13:58:04.790477 ERROR run cmd 'mount -o ro -t udf,iso9660 /dev/sr0 /mnt/cdrom/secure' failed
2017/02/27 13:58:04.817291 ERROR Error Code:32
2017/02/27 13:58:04.825715 ERROR Result:mount: no medium found on /dev/sr0

2017/02/27 13:58:04.853579 WARNING Mount dvd failed: retry=3, ret=32
2017/02/27 13:58:10.043904 ERROR run cmd 'mount -o ro -t udf,iso9660 /dev/sr0 /mnt/cdrom/secure' failed
2017/02/27 13:58:10.074810 ERROR Error Code:32
2017/02/27 13:58:10.081061 ERROR Result:mount: no medium found on /dev/sr0

2017/02/27 13:58:10.103250 WARNING Mount dvd failed: retry=4, ret=32
2017/02/27 13:58:15.301218 ERROR run cmd 'mount -o ro -t udf,iso9660 /dev/sr0 /mnt/cdrom/secure' failed
2017/02/27 13:58:15.325484 ERROR Error Code:32
2017/02/27 13:58:15.331161 ERROR Result:mount: no medium found on /dev/sr0

2017/02/27 13:58:15.352276 ERROR [ProtocolError] Provisioning failed: (000008)(000007)Failed to mount dvd.
2017/02/27 13:58:15.376245 INFO Detect protocol endpoints
2017/02/27 13:58:15.382764 INFO Clean protocol
2017/02/27 13:58:15.400163 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/02/27 13:58:15.421504 INFO test for route to 168.63.129.16
2017/02/27 13:58:15.429526 INFO route to 168.63.129.16 exists
2017/02/27 13:58:15.448251 INFO Wire server endpoint:168.63.129.16
2017/02/27 13:58:15.479282 INFO Fabric preferred wire protocol version:2015-04-05
2017/02/27 13:58:15.488511 INFO Wire protocol version:2012-11-30
2017/02/27 13:58:15.507417 WARNING Server prefered version:2015-04-05
2017/02/27 13:58:20.801603 ERROR Event: name=WALA, op=Provision, message=Failed to copy ovf-env.xml: (000008)(000007)Failed to mount dvd.
2017/02/27 13:58:20.827564 INFO RDMA capabilities are not enabled, skipping
2017/02/27 13:58:20.835795 INFO Installed Agent WALinuxAgent-2.2.0 is the most current agent
2017/02/27 13:58:20.895530 INFO Agent WALinuxAgent-2.2.0 launched with command 'python -u /usr/sbin/waagent -run-exthandlers'
2017/02/27 13:58:21.331286 INFO Agent WALinuxAgent-2.2.0 is running as the goal state agent
2017/02/27 13:58:21.380946 INFO Wire server endpoint:168.63.129.16
2017/02/27 13:58:21.421557 INFO Event: name=WALinuxAgent-2.2.0, op=HeartBeat, message=
2017/02/27 13:58:21.448668 INFO Start env monitor service.
2017/02/27 13:58:21.465289 INFO Configure routes
2017/02/27 13:58:21.482328 INFO Gateway:None
2017/02/27 13:58:21.487656 INFO Routes:None
2017/02/27 13:58:21.594822 INFO Set block dev timeout: sda with timeout: 300
2017/02/27 13:58:21.621335 INFO Set block dev timeout: sdb with timeout: 300
2017/02/27 13:58:21.609292 INFO WALinuxAgent-2.2.0 running as process 8007
2017/02/27 13:58:21.682599 INFO Wire server endpoint:168.63.129.16

thanks

**Comment by axelgMS** [comment]
Looks like it's already resolved in https://github.com/Azure/WALinuxAgent/issues/516
