### ISSUE TITLE
Exception: WriteToFolder:Too many file under /var/lib/waagent/events exit

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#605]
The agent threw the following exception.

GAVersion: 2.0.18
Distro: CentOS

```text
ERROR:Error Traceback (most recent call last):
ERROR:  File "/usr/sbin/waagent", line 5659, in AddExtensionEvent
ERROR:    event.Save()
ERROR:  File "/usr/sbin/waagent", line 5630, in Save
ERROR:    raise Exception("WriteToFolder:Too many file under "+eventfolder+" exit")
ERROR:Exception: WriteToFolder:Too many file under /var/lib/waagent/events exit
ERROR:
ERROR:Exception: No JSON object could be decoded
```

The agent would then restart, and go through a short startup and immediately die due the same error.

**Comment by brendandixon** [comment]
@boumenot v2.0.18 is known to have issues like this. Please use a more recent agent version.
