### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by boumenot** [Azure/WALinuxAgent#606]
This may be related to #605 because it was discovered on the same VM.

The agent emitted this error.

```text
ERROR:Unable to fetch Bundle URI from manifest for Microsoft.OSTCExtensions.LinuxDiagnostic v 2.3.9011
```

and then emitted this error.

```text
Finished processing ExtensionsConfig.xml
ERROR:Traceback (most recent call last):
ERROR:  File "/usr/sbin/waagent", line 7162, in main
ERROR:    WaAgent.Run()
ERROR:  File "/usr/sbin/waagent", line 6744, in Run
ERROR:    ret = goalState.ExtensionsConfig.ReportHandlerStatus()
ERROR:  File "/usr/sbin/waagent", line 4885, in ReportHandlerStatus
ERROR:    reportHeartbeat = json.loads(p.getAttribute("manifestdata"))[0]['handlerManifest']['report

ERROR:  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
ERROR:    return _default_decoder.decode(s)
ERROR:  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
ERROR:    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
ERROR:  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
ERROR:    raise ValueError("No JSON object could be decoded")
ERROR:ValueError: No JSON object could be decoded
ERROR:
ERROR:Exception: No JSON object could be decoded
```

The agent then restarted, went through a short startup sequence and died the same way again.

**Comment by brendandixon** [comment]
@boumenot v2.0.18 is known to have issues like this. Please use a more recent agent version.
