### ISSUE TITLE
MetadataProtocol has no client object

### ISSUE THREAD

**Issue by hglkrijger** [Azure/WALinuxAgent#761]
```
2017/06/14 22:46:43.331214 WARNING Agent WALinuxAgent-2.2.12 launched with command 'python3 -u /usr/sbin/waagent -run-exthandlers' failed with return code: 1
2017/06/14 22:46:43.339738 ERROR Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.12 launched with command 'python3 -u /usr/sbin/waagent -run-exthandlers' failed with return code: 1
2017/06/14 22:46:43.348803 WARNING Agent WALinuxAgent-2.2.12 launched with command 'python3 -u /usr/sbin/waagent -run-exthandlers' returned code: 1
2017/06/14 22:46:43.356455 INFO Installed Agent WALinuxAgent-2.2.12 is the most current agent
2017/06/14 22:46:43.773154 INFO Agent WALinuxAgent-2.2.12 is running as the goal state agent
2017/06/14 22:46:43.856962 INFO Event: name=WALinuxAgent-2.2.12, op=HeartBeat, message=
2017/06/14 22:46:43.859580 INFO Start env monitor service.
2017/06/14 22:46:43.937592 INFO Configure routes
2017/06/14 22:46:43.965398 INFO Gateway:None
2017/06/14 22:46:43.976631 INFO Routes:None
2017/06/14 22:46:44.025814 INFO WALinuxAgent-2.2.12 running as process 5704
2017/06/14 22:46:44.033808 INFO WALinuxAgent-2.2.12 did not terminate cleanly
2017/06/14 22:46:44.040433 ERROR Event: name=WALinuxAgent, op=Restart, message=WALinuxAgent-2.2.12 did not terminate cleanly
2017/06/14 22:46:44.154968 ERROR [000008] 404 - POST: http://169.254.169.254/Microsoft.Compute/status/telemetry?api-version=2015-05-01-preview
2017/06/14 22:46:44.432870 WARNING Agent WALinuxAgent-2.2.12 failed with exception: 'MetadataProtocol' object has no attribute 'client'
2017/06/14 22:46:44.443499 WARNING Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/update.py", line 256, in run
    if self._upgrade_available():
  File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/update.py", line 427, in _upgrade_available
    if protocol and protocol.client:
AttributeError: 'MetadataProtocol' object has no attribute 'client'
```

**Comment by brendandixon** [comment]
Addressed by #776
