### ISSUE TITLE
walinuxagent Failed to run 'run-exthandlers':

### ISSUE THREAD

**Issue by tungripe** [Azure/WALinuxAgent#763]
Hi,
We have dozen servers running Ubuntu 14.04.5 LTS on Azure. We recently upgrade waagent to the latest versions. Our azure vm backup fails since upgrading waagent to version 2.2.12. The strange thing is azure VM backup  works on all of them except for 3 different VMs

Here is the waagent version:
```
# waagent -version
WALinuxAgent-2.2.12 running on ubuntu 14.04
Python: 3.4.3
Goal state agent: 2.2.12
```

In the waagent log file, this error appears every 3 seconds: 
```
# less /var/log/waagent.log
2017/06/16 04:02:34.893131 ERROR Command: 'None                     # If "None", the system default version is used. cms -decrypt -in /var/lib/waagent/Certificates.p7m -inkey /var/lib/waagent/TransportPrivate.pem -recip /var/lib/waagent/TransportCert.pem | None                     # If "None", the system default version is used. pkcs12 -nodes -password pass: -out /var/lib/waagent/Certificates.pem'
2017/06/16 04:02:34.905336 ERROR Return code: 127
2017/06/16 04:02:34.907113 ERROR Result: /bin/sh: 1: None: not found

2017/06/16 04:02:34.912356 ERROR Command: 'None                     # If "None", the system default version is used. rsa -in /var/lib/waagent/0.prv -pubout 2>/dev/null'
2017/06/16 04:02:34.919377 ERROR Return code: 127
2017/06/16 04:02:34.922083 ERROR Result: /bin/sh: 1: None: not found

2017/06/16 04:02:34.926843 ERROR Command: 'None                     # If "None", the system default version is used. x509 -in /var/lib/waagent/1.crt -pubkey -noout'
2017/06/16 04:02:34.932286 ERROR Return code: 127
2017/06/16 04:02:34.934056 ERROR Result: /bin/sh: 1: None: not found

2017/06/16 04:02:34.938140 ERROR Command: 'None                     # If "None", the system default version is used. x509 -in /var/lib/waagent/1.crt -fingerprint -noout'
2017/06/16 04:02:34.944696 ERROR Return code: 127
2017/06/16 04:02:34.946497 ERROR Result: /bin/sh: 1: None: not found

2017/06/16 04:02:34.950498 ERROR Failed to run 'run-exthandlers': Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/azurelinuxagent/agent.py", line 147, in main
    agent.run_exthandlers()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/agent.py", line 117, in run_exthandlers
    update_handler.run()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/update.py", line 236, in run
    get_monitor_handler().run()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/monitor.py", line 96, in run
    self.init_sysinfo()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/ga/monitor.py", line 121, in init_sysinfo
    protocol = self.protocol_util.get_protocol()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/util.py", line 261, in get_protocol
    self.protocol = self._detect_protocol(protocols)
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/util.py", line 183, in _detect_protocol
    return self._detect_wire_protocol()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/util.py", line 152, in _detect_wire_protocol
    protocol.detect()
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 99, in detect
    self.client.update_goal_state(forced=True)
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 729, in update_goal_state
    self.update_certs(goal_state)
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 688, in update_certs
    self.certs = Certificates(self, xml_text)
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 1147, in __init__
    self.parse(xml_text)
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/protocol/wire.py", line 1203, in parse
    thumbprint = cryptutil.get_thumbprint_from_crt(tmp_file)
  File "/usr/lib/python3/dist-packages/azurelinuxagent/common/utils/cryptutil.py", line 55, in get_thumbprint_from_crt
    thumbprint = thumbprint.rstrip().split('=')[1].replace(':', '').upper()
IndexError: list index out of range

2017/06/16 04:02:35.662751 INFO Agent WALinuxAgent-2.2.12 launched with command 'python3 -u /usr/sbin/waagent -run-exthandlers' is successfully running
2017/06/16 04:02:35.665392 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.12 launched with command 'python3 -u /usr/sbin/waagent -run-exthandlers' is successfully running
2017/06/16 04:02:35.668840 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2017/06/16 04:02:35.670446 INFO Installed Agent WALinuxAgent-2.2.12 is the most current agent
2017/06/16 04:02:35.829161 INFO Agent WALinuxAgent-2.2.12 is running as the goal state agent
2017/06/16 04:02:35.831243 INFO Detect protocol endpoints
2017/06/16 04:02:35.832317 INFO Clean protocol
2017/06/16 04:02:35.833313 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/06/16 04:02:35.834788 INFO Test for route to 168.63.129.16
2017/06/16 04:02:35.837044 INFO Route to 168.63.129.16 exists
2017/06/16 04:02:35.837840 INFO Wire server endpoint:168.63.129.16
2017/06/16 04:02:35.846969 INFO Fabric preferred wire protocol version:2015-04-05
2017/06/16 04:02:35.848083 INFO Wire protocol version:2012-11-30
2017/06/16 04:02:35.849052 WARNING Server preferred version:2015-04-05
2017/06/16 04:02:35.856200 ERROR Command: 'None                     # If "None", the system default version is used. req -x509 -nodes -subj /CN=LinuxTransport -days 730 -newkey rsa:2048 -keyout /var/lib/waagent/TransportPrivate.pem -out /var/lib/waagent/TransportCert.pem'
2017/06/16 04:02:35.857008 ERROR Return code: 127
2017/06/16 04:02:35.857873 ERROR Result: /bin/sh: 1: None: not found
```

I restarted waagent services few times, and it did not help. I reinstalled waagent but it did not help either, the errors are still there and backups still failed.

I also notice that there are waagent and walinuxagent  services on the machine. If I start one service, the other one stops automatically. Can you please clarify this for me?
```
# service waagent status
waagent stop/waiting
# service walinuxagent status
walinuxagent start/running, process 11680
```

Our main issue is the VM backups are failing on our production server. So we would like to find out the root cause and bring it back to normal.

Let us know if you need further details. Appreciate your helps.

**Edit:** 
The error that we got in azure console is: VM agent is unable to communicate with the Azure Backup Service.

I also followed the instruction to troubleshoot here but did not work:
https://docs.microsoft.com/en-us/azure/backup/backup-azure-troubleshoot-vm-backup-fails-snapshot-timeout

Cheers,
Tung

**Comment by lovepreetkaul** [comment]
I am also facing the same issue. These are two different errors. 

The first being:
```
2017/06/16 04:02:34.893131 ERROR Command: 'None                     # If "None", the system default version is used. cms -decrypt -in /var/lib/waagent/Certificates.p7m -inkey /var/lib/waagent/TransportPrivate.pem -recip /var/lib/waagent/TransportCert.pem | None                     # If "None", the system default version is used. pkcs12 -nodes -password pass: -out /var/lib/waagent/Certificates.pem'
2017/06/16 04:02:34.905336 ERROR Return code: 127
2017/06/16 04:02:34.907113 ERROR Result: /bin/sh: 1: None: not found
```

Here, Waagent is not able to get the default Openssl path from the system and is using the value `None`, and then trying to execute it on Shell. `None` isn't a shell command and therefore it fails.

 You can workaround this issue by specifying the Openssl path in `waagent.conf` as
```
OS.OpensslPath=/usr/bin/openssl
```
Although this will not solve the backup failing issue.

**Comment by lovepreetkaul** [comment]
Hi,

Found a solution.  The config parameters are being read wrong due to the comments in the waagent.conf file.

Instead of
`OS.OpensslPath=None`
 
It is read
```
OS.OpensslPath=None                       # If "None", the system default version is used.
```

Hence, the value that is passed is this complete string, causing the waagent to go wonky.

**FIX**
Getting all the comments in the config file into another line instead of the same line for all the parameters fixed it for me. 
```
OS.OpensslPath=None
# If "None", the system default version is used.
```
Restart the waagent service after making the changes. And try back up again.

Hope that helps!

**Comment by brendandixon** [comment]
@tungripe @lovepreetkaul The agent uses an exceedingly simple parse for its configuration file: It only accepts <key>=<value> pairs without additional material on the line (e.g., no comments). Comments must live on their own lines.

The version of /etc/waagent.conf we ship with the agent (e.g., https://github.com/Azure/WALinuxAgent/blob/master/config/waagent.conf) honors this restriction.

**Comment by tungripe** [comment]
@lovepreetkaul @brendandixon Thanks a lot. It is working after moving the comments to different lines.

FYI: When I upgraded waagent, I selected the option to keep old configuration files which why it did not update waagent.conf. A bit curious why it still works on some machines even though the config files are the same.
