### ISSUE TITLE
Error with sshd_config no such file

### ISSUE THREAD

**Issue by ChrisJergens** [Azure/WALinuxAgent#790]
I'm baffled and can't figure out what's going wrong.
WALinuxAgent-2.2.13 running on centos 6.7
Python: 2.6.6
Goal state agent: 2.2.13
uname 2.6.32-696.3.1.el6.x86_64

ERROR Event: name=WALinuxAgent, op=UnhandledError, message=Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/daemon/main.py", line 77, in run
    self.daemon(child_args)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/daemon/main.py", line 123, in daemon
    self.provision_handler.run()
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/pa/provision/default.py", line 83, in run
    self.provision(ovf_env)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/pa/provision/default.py", line 193, in provision
    self.config_user_account(ovfenv)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/pa/provision/default.py", line 219, in config_user_account
    self.osutil.conf_sshd(ovfenv.disable_ssh_password_auth)
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/osutil/default.py", line 291, in conf_sshd
    conf_file = fileutil.read_file(conf_file_path).split("\n")
  File "/usr/lib/python2.6/site-packages/azurelinuxagent/common/utils/fileutil.py", line 45, in read_file
    with open(filepath, mode) as in_file:
IOError: [Errno 2] No such file or directory: u'/etc/ssh\r/sshd_config'

# ll /etc/ssh/
total 164
-rw-------. 1 root root 125811 Mar 22 08:33 moduli
-rw-r--r--. 1 root root   2047 Mar 22 08:33 ssh_config
-rw-------. 1 root root    668 Jun 29 13:05 ssh_host_dsa_key
-rw-r--r--. 1 root root    590 Jun 29 13:05 ssh_host_dsa_key.pub
-rw-------. 1 root root    963 Jun 29 13:05 ssh_host_key
-rw-r--r--. 1 root root    627 Jun 29 13:05 ssh_host_key.pub
-rw-------. 1 root root   1675 Jun 29 13:05 ssh_host_rsa_key
-rw-r--r--. 1 root root    382 Jun 29 13:05 ssh_host_rsa_key.pub
-rw-------. 1 root root   4213 Jul  3 10:16 sshd_config

**Comment by ChrisJergens** [comment]
And the Issue was....  CRLF in waagent.conf, self-induced shame.  This had a weird effect on a number of errors I've been having.  Basically during edits, different lines were getting CRLF, not the whole file, so depending on that, different errors were produced.  Causing much head bashing.
