### ISSUE TITLE
Installation issue:  AttributeError: 'module' object has no attribute 'EREMOTEIO'

### ISSUE THREAD

**Issue by schur** [Azure/WALinuxAgent#901]
~/WALinuxAgent # python setup.py install                                        
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    from azurelinuxagent.common.version import AGENT_NAME, AGENT_VERSION, \
  File "/home/reiny/WALinuxAgent/azurelinuxagent/common/version.py", line 23, in <module>
    import azurelinuxagent.common.conf as conf
  File "/home/reiny/WALinuxAgent/azurelinuxagent/common/conf.py", line 26, in <module>
    import azurelinuxagent.common.utils.fileutil as fileutil
  File "/home/reiny/WALinuxAgent/azurelinuxagent/common/utils/fileutil.py", line 45, in <module>
    errno.EREMOTEIO     # Remote I/O error
AttributeError: 'module' object has no attribute 'EREMOTEIO'

Python Version is 2.7
OpenBSD 6.1
EREMOTEIO is missing when running help('eremoteio') in python.

**Comment by brendandixon** [comment]
@schur `errno.EREMOTEIO` is in the standard Python 2.7 (see https://docs.python.org/2/library/errno.html#errno.EREMOTEIO). OpenBSD may have modified their modules.
