### ISSUE TITLE
waagent dies when rate limited

### ISSUE THREAD

**Issue by bueti** [Azure/WALinuxAgent#95]
The waagent process dies when storing the status to the blob storage fails due to rate limit:

```
2015/07/17 18:36:54 ERROR:Retry=0
2015/07/17 18:36:54 ERROR:HTTP Req: HEAD https://xxxxxx.blob.core.windows.net/vhds/xxxxxx
2015/07/17 18:36:54 ERROR:HTTP Req: Data=None
2015/07/17 18:36:54 ERROR:HTTP Req: Header={'x-ms-version': '2014-02-14', 'x-ms-date': '2015-07-17T18:36:54Z'}
2015/07/17 18:36:54 ERROR:HTTP Err: Status=503
2015/07/17 18:36:54 ERROR:HTTP Err: Reason=The server is busy.
2015/07/17 18:36:54 ERROR:HTTP Err: Header=[('transfer-encoding', 'chunked'), ('date', 'Fri, 17 Jul 2015 18:36:53 GMT'), ('x-ms-request-id', 'd263f174-0001-0070-77bf-c0b52e000000'), ('x-ms-version', '2012-02-12'), ('server', 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0')]
2015/07/17 18:36:54 ERROR:HTTP Err: Body=
2015/07/17 18:37:04 ERROR:Traceback (most recent call last):
2015/07/17 18:37:04 ERROR:  File "/usr/sbin/waagent", line 5938, in main
2015/07/17 18:37:04 ERROR:    WaAgent.Run()
2015/07/17 18:37:04 ERROR:  File "/usr/sbin/waagent", line 5540, in Run
2015/07/17 18:37:04 ERROR:    goalState.ExtensionsConfig.ReportHandlerStatus()
2015/07/17 18:37:04 ERROR:  File "/usr/sbin/waagent", line 3831, in ReportHandlerStatus
2015/07/17 18:37:04 ERROR:    UploadStatusBlob(uri, status.encode("utf-8"))
2015/07/17 18:37:04 ERROR:  File "/usr/sbin/waagent", line 2890, in UploadStatusBlob
2015/07/17 18:37:04 ERROR:    blobType = GetBlobType(url)
2015/07/17 18:37:04 ERROR:  File "/usr/sbin/waagent", line 2819, in GetBlobType
```

imho the waagent should back-off or retry instead of crash :)

**Comment by yuezh** [comment]
Sure, we should improve the error handling :)
Thanks

**Comment by kuni-nakaji** [comment]
We have got same error in  the `WALinuxAgent-2.0.14 running on centos` 

```
2015/11/04 19:26:19 ERROR:Retry=0
2015/11/04 19:26:19 ERROR:HTTP Req: POST /machine?comp=health
2015/11/04 19:26:19 ERROR:HTTP Req: Data=<?xml version="1.0" encoding="utf-8"?><Health xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GoalStateIncarnation>4</GoalStateIncarnation><Container><ContainerId>e998d239-8567-46e9-af55-821608514ecd</ContainerId><RoleInstanceList><Role><InstanceId>3303c71d5e694f03919aeb664c746add.vmud-az-logstore12</InstanceId><Health><State>Ready</State></Health></Role></RoleInstanceList></Container></Health>
2015/11/04 19:26:19 ERROR:HTTP Req: Header={'Content-Type': 'text/xml; charset=utf-8', 'x-ms-version': '2012-11-30', 'x-ms-agent-name': 'WALinuxAgent'}
2015/11/04 19:26:19 ERROR:HTTP Err: Status=503
2015/11/04 19:26:19 ERROR:HTTP Err: Reason=Service Unavailable
2015/11/04 19:26:19 ERROR:HTTP Err: Header=[('date', 'Wed, 04 Nov 2015 19:26:18 GMT'), ('connection', 'close'), ('content-type', 'text/html; charset=us-ascii'), ('content-length', '326'), ('server', 'Microsoft-HTTPAPI/2.0')]
2015/11/04 19:26:19 ERROR:HTTP Err: Body=<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
2015/11/04 19:26:19 ERROR:<HTML><HEAD><TITLE>Service Unavailable</TITLE>
2015/11/04 19:26:19 ERROR:<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
2015/11/04 19:26:19 ERROR:<BODY><h2>Service Unavailable</h2>
2015/11/04 19:26:19 ERROR:<hr><p>HTTP Error 503. The service is unavailable.</p>
2015/11/04 19:26:19 ERROR:</BODY></HTML>
2015/11/04 19:26:19 ERROR:
2015/11/04 19:26:29 ERROR:Retry=1
2015/11/04 19:26:29 ERROR:HTTP Req: POST /machine?comp=health
2015/11/04 19:26:29 ERROR:HTTP Req: Data=<?xml version="1.0" encoding="utf-8"?><Health xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GoalStateIncarnation>4</GoalStateIncarnation><Container><ContainerId>e998d239-8567-46e9-af55-821608514ecd</ContainerId><RoleInstanceList><Role><InstanceId>3303c71d5e694f03919aeb664c746add.vmud-az-logstore12</InstanceId><Health><State>Ready</State></Health></Role></RoleInstanceList></Container></Health>
2015/11/04 19:26:29 ERROR:HTTP Req: Header={'Content-Type': 'text/xml; charset=utf-8', 'x-ms-version': '2012-11-30', 'x-ms-agent-name': 'WALinuxAgent'}
2015/11/04 19:26:29 ERROR:HTTP Err: Status=503
2015/11/04 19:26:29 ERROR:HTTP Err: Reason=Service Unavailable
2015/11/04 19:26:29 ERROR:HTTP Err: Header=[('date', 'Wed, 04 Nov 2015 19:26:29 GMT'), ('connection', 'close'), ('content-type', 'text/html; charset=us-ascii'), ('content-length', '326'), ('server', 'Microsoft-HTTPAPI/2.0')]
2015/11/04 19:26:29 ERROR:HTTP Err: Body=<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
2015/11/04 19:26:29 ERROR:<HTML><HEAD><TITLE>Service Unavailable</TITLE>
2015/11/04 19:26:29 ERROR:<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
2015/11/04 19:26:29 ERROR:<BODY><h2>Service Unavailable</h2>
2015/11/04 19:26:29 ERROR:<hr><p>HTTP Error 503. The service is unavailable.</p>
2015/11/04 19:26:29 ERROR:</BODY></HTML>
2015/11/04 19:26:29 ERROR:
2015/11/04 19:26:39 ERROR:Traceback (most recent call last):
2015/11/04 19:26:39 ERROR:  File "/usr/sbin/waagent", line 6048, in main
2015/11/04 19:26:39 ERROR:    WaAgent.Run()
2015/11/04 19:26:39 ERROR:  File "/usr/sbin/waagent", line 5634, in Run
2015/11/04 19:26:39 ERROR:    incarnation = self.ReportReady()
2015/11/04 19:26:39 ERROR:  File "/usr/sbin/waagent", line 5221, in ReportReady
2015/11/04 19:26:39 ERROR:    a = self.HttpPostWithHeaders("/machine?comp=health", healthReport)
2015/11/04 19:26:39 ERROR:  File "/usr/sbin/waagent", line 2840, in HttpPostWithHeaders
2015/11/04 19:26:39 ERROR:    maxRetry=maxRetry, chkProxy=chkProxy)
2015/11/04 19:26:39 ERROR:  File "/usr/sbin/waagent", line 2790, in HttpPost
2015/11/04 19:26:39 ERROR:    maxRetry=maxRetry, chkProxy=chkProxy)
2015/11/04 19:26:39 ERROR:  File "/usr/sbin/waagent", line 2759, in HttpRequest
2015/11/04 19:26:39 ERROR:    raise HttpResourceGoneError("Http resource gone.")
2015/11/04 19:26:39 ERROR:HttpResourceGoneError: Http resource gone.
2015/11/04 19:26:39 ERROR:
2015/11/04 19:26:39 ERROR:Exception: Http resource gone.
```

**Comment by yuezh** [comment]
Hi, @kuni-nakaji. We will fix this in 2.1.2 release.

**Comment by kuni-nakaji** [comment]
Thx, @yuezh !!

**Comment by alager** [comment]
@yuezh, is there an ETA on when the 2.1.2 will be pushed to the repositories(ubuntu 14.04)?
What is the work around, besides just logging in every day to see if the agent is still running?
Thanks!

**Comment by alager** [comment]
FYI, I modified the startup script, /etc/init/walinuxagent.conf to add respawing, with a time delay:
```
description "Windows Azure Linux agent"
author "Ben Howard <ben.howard@canonical.com>"
#modified by Aaron Lager <aaron.lager@gmail.com> to add respawning with time delay

start on runlevel [2345]
stop on runlevel [!2345]

#respawn if died of unnatrual cuases
#try 10 times within 100 seconds, then give up
respawn
respawn limit 10 100

#this little bit, slows down the respawinging process
env SLEEP_TIME=1
post-stop script
    goal=`initctl status $UPSTART_JOB | awk '{print $2}' | cut -d '/' -f 1`
    if [ $goal != "stop" ]; then
        sleep $SLEEP_TIME
        NEW_SLEEP_TIME=`expr 2 * $SLEEP_TIME`
        if [ $NEW_SLEEP_TIME -ge 60 ]; then
            NEW_SLEEP_TIME=60
        fi
        initctl set-env SLEEP_TIME=$NEW_SLEEP_TIME
    fi
end script


pre-start script

    [ -r /etc/default/walinuxagent ] && . /etc/default/walinuxagent

    if [ "$WALINUXAGENT_ENABLED" != "1" ]; then
        stop ; exit 0
    fi

    if [ ! -x /usr/sbin/waagent ]; then
        stop ; exit 0
    fi

    #Load the udf module
    modprobe -b udf

end script

exec /usr/sbin/waagent -daemon
```

Hope this can help someone.
Aaron

**Comment by ahmetalpbalkan** [comment]
@alager thanks for providing a workaround. 

The init scripts for the recent versions of waagent incorporated the patch adding `respawn` directive to the init script.

Please pick up one of the recent images from Azure if you are still seeing this issue.
