### ISSUE TITLE
"ImportError: cannot import name LoggerInit" error makes thousands of line of logs

### ISSUE THREAD

**Issue by AlexDaciuk** [Azure/WALinuxAgent#957]
System : Debian 9.2 (upgraded from 8)
Plan : Standard D1 v2 (1 vcpu, 3.5 GB memory)
Location : South Central US
waagent version : waagent/stable,now 2.2.14-1~deb9u1

After investigating why I'm getting gigs of logs after just weeks, one thing that keeps appearing in `daemon.log` is this

```
waagent[741]: 2017/12/01 01:29:13.041526 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Target handler state: enabled
waagent[741]: 2017/12/01 01:29:13.053827 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] [Enable] current handler state is: notinstalled
waagent[741]: 2017/12/01 01:29:13.099400 INFO Event: name=Microsoft.OSTCExtensions.VMAccessForLinux, op=Download, message=Download succeeded, duration=0
waagent[741]: 2017/12/01 01:29:13.113239 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Initialize extension directory
waagent[741]: 2017/12/01 01:29:13.125229 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.7.1] Update settings file: 5.settings
waagent[741]: 2017/12/01 01:29:13.136950 INFO [Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0] Disable extension [./vmaccess.py -disable]
waagent[741]: Traceback (most recent call last):
waagent[741]:   File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/./vmaccess.py", line 27, in <module>
waagent[741]:     import Utils.HandlerUtil as Util
waagent[741]:   File "/var/lib/waagent/Microsoft.OSTCExtensions.VMAccessForLinux-1.4.6.0/Utils/HandlerUtil.py", line 66, in <module>
waagent[741]:     from waagent import LoggerInit
waagent[741]: ImportError: cannot import name LoggerInit
waagent[741]: 2017/12/01 01:29:14.151820 ERROR Event: name=Microsoft.OSTCExtensions.VMAccessForLinux, op=Download, message=[000003] Non-zero exit code: 1, ./vmaccess.py -disable, duration=0
```

Seems like waagent is getting updated automatically outside of the official Debian package because `journalctl -b | grep -i WALinux` outputs this

```
waagent[741]: 2017/12/01 01:26:26.109162 INFO Agent WALinuxAgent-2.2.18 is running as the goal state agent
waagent[741]: 2017/12/01 01:26:30.624063 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
waagent[741]: 2017/12/01 01:26:30.778530 INFO WALinuxAgent-2.2.18 running as process 774
waagent[741]: 2017/12/01 01:26:36.466727 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=, duration=5438
```

After 2 weeks, `daemon.log` size is more than 700 MB and **waagent** process uses 30 % of RAM ...

Any ideas?

**Comment by hglkrijger** [comment]
This might be a result of a dependency which was removed in Debian 8. Suggested fix is to remove the VMAccessForLinux extension, then re-install as required. Let us know if that does not work.

**Comment by AlexDaciuk** [comment]
For some reason, the package **python3-azure-storage** is not a dependency of **waagent** on Debian 9, installed that package and errors stopped
